### PR TITLE
enhanced the terms and conditions page

### LINKED ISSUE #1253: Enhancing the terms and conditions page
To give it a proper layout and styling

### PR DESCRIPTION
**Pull request by ayush-848**
## Screenshots
image
image
image
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil please check

**Comment by thestarsahil** [comment]
Remove the text hover effect animation

**Comment by ayush-848** [comment]
> Remove the text hover effect animation

Which one exactly can you give a screenshot

**Comment by ayush-848** [comment]
> Remove the text hover effect animation

Is it the one where the text slightly pops up on refresh

**Comment by ayush-848** [comment]
@thestarsahil I have removed the animations

**Pull request merged**
