### PR TITLE
NavBar Updated

### LINKED ISSUE #571: [Enhance]The Navbar
I would like to enhance the Navbar UI with animations and suitable changes that will align with the theme

### PR DESCRIPTION
**Pull request by sau-mili**
# Description
Check now, redo after pulling changes
Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #571 

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Working Good ! There are minor changes have to done , Don't worry we gonna fix this

**Comment by sau-mili** [comment]
Can you add the labels please?

**Comment by thestarsahil** [comment]
@sau-mili Issue in navbar 
Screenshot from 2024-05-29 22-26-07

While Implemetion in Hamburger , section hide 
Fix this !

**Comment by thestarsahil** [comment]
@sau-mili Can you again push the same changes !

**Comment by sau-mili** [comment]
yes one second

**Pull request merged**
