### PR TITLE
Resolved the bugs for toast notifications.

### LINKED ISSUE #636: Resolving some bugs when user tries to signup/login.
**Describe the bug**
When users are signing up or logging in on the website, proper error handling and alert displays are not implemented.

**Expected behavior**
- When I tried logging with a new email id which is not registered. The error is not handled properly, an alert should be prompting saying that the email is not registered.
> Screenshot (509)

- After a successful log-in, an alert displaying the message "You are logged in" should appear. This alert needs to be designed to be visually appealing and in harmony with the website's overall theme. Currently, there is no alert, and the homepage opens abruptly.

- When logging out successfully, there is no alert. However, the user should receive an alert even in this situation.

- When a user inputs an incorrect password or captcha, the default browser alert is displayed. I would like to modify this alert to be more appealing and match the website's theme.

**Additional context**
Kindly assign this issue to me under GSSOC'24.

### PR DESCRIPTION
**Pull request by yashi-15**
# Description

- Upon reloading the dashboard page, the toast notification does not repeatedly display. 
- The toast notifications are well-displayed on smaller devices as well.

Kindly review and merge this under GSSOC'24.

## Screenshots

Screenshot (556)
Screenshot (555)
Screenshot (557)

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Screenshot from 2024-06-15 10-31-17
Screenshot from 2024-06-15 10-31-27

Error Occured and Delay is to much taking time reduce that !

**Comment by thestarsahil** [comment]
As Many Time login and logout , the toaster notification incrementing 
Check on your system login 5 times and logout  5 times

**Comment by thestarsahil** [comment]
@yashi-15 Does it fixed ?

**Comment by yashi-15** [comment]
> @yashi-15 Does it fixed ?

NO.. I am working on it

**Comment by yashi-15** [comment]
@thestarsahil The error is solved now... You can review!

**Comment by thestarsahil** [comment]
I minor Change have need to be do , the pop message slighty change its position up when its appear 
Rest of the part okay , After that I am merging this

**Comment by thestarsahil** [comment]
@yashi-15 Did you fixed it ?

**Pull request closed without merging**
