### PR TITLE
Created edit profile with Blurred Background , added cross button

### LINKED ISSUE #1252: Upgrading the Edit profile section
Fix the gap bw navabar and college section(10)

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have make the background blurred while opening the edit profile modal  and also added a cross button functionality 

## Screenshots
image
image

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i have added the blurred background but little bit confusion with border like what kind of 3d border you want please elaborate

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-26 13-48-06

No exit in right up corner

**Comment by Ayushmaanagarwal1211** [comment]
Ok sir i will remove

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i removed that

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir can you please check this will work now

**Pull request merged**
