### PR TITLE
Updated About Us Page

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #587 

I redesigned the cards and added animation effects on hover. I have made the section responsive as well.

Screenshot 2024-05-24 140808

@thestarsahil please check and let me know if any changes are required.

### CODE REVIEW

**Comment by thestarsahil** [comment]
@Hemashree21 Yes you have to resolve this ! The Deepsource have to clear all test case you made you make more code readable and understable !

**Comment by Hemashree21** [comment]
@thestarsahil I resolved all conflicts and made each section of the code as a reusable component. Can you please assign level 3 to this PR? It took me a lot of time to resolve all the issues?

**Comment by thestarsahil** [comment]
Screenshot from 2024-05-25 14-13-33
Screenshot from 2024-05-25 14-13-26

Update and fix this ...
Font family should be "ABeeZee"
College card back side not visible

**Comment by Hemashree21** [comment]
@thestarsahil I updated the changes

**Comment by thestarsahil** [comment]
Reflecting the same issue ..

**Comment by Hemashree21** [comment]
image

Sir the font is changed and the background for cards, these were the only 2 changes right? Or were there anything else?

**Comment by Hemashree21** [comment]
image

I have made the changes in commit ccc8aa1 can you please check that as well? It's working correctly in my server.

**Review by thestarsahil — APPROVED** [review]
Good to merge !

**Comment by Hemashree21** [comment]
Thankyou!

**Pull request merged**
