### PR TITLE
Added Icons 

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Added Icons to Navbar and Footer - Solved #704
Kindly Please go through it @thestarsahil
I solved the issue and conflict please check it and see if it is still exists

hh

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
@thestarsahil Kindly please go through this PR

**Comment by thestarsahil** [comment]
@sailaja-adapa Due to this , whole pages effecting

**Comment by sailaja-adapa** [comment]
@thestarsahil Kindly Please go through this PR

**Comment by sailaja-adapa** [comment]
> @sailaja-adapa Due to this , whole pages effecting

is it? but it is working fine in my system

**Comment by thestarsahil** [comment]
Compare the difference 
The localhost and Live host

**Comment by sailaja-adapa** [comment]
@thestarsahil i think i solved that issue still it causing that problem?

**Comment by sailaja-adapa** [comment]
> Compare the difference The localhost and Live host

yeah okk @thestarsahil

**Comment by thestarsahil** [comment]
Yes !

**Comment by sailaja-adapa** [comment]
i solved conflicts just now

**Comment by sailaja-adapa** [comment]
okk then i will close this then @thestarsahil

**Comment by thestarsahil** [comment]
What i am trying to say, Just pull all the latest changes and make your branch uptodate according to master branch and then push it

**Comment by sailaja-adapa** [comment]
> What i am trying to say, Just pull all the latest changes and make your branch uptodate according to master branch and then push it

Yeah okk I will try it once @thestarsahil

**Pull request closed without merging**
