### PR TITLE
Add preloading screen

### PR DESCRIPTION
**Pull request by SubhamB2003**
# Description
issue solved: #196 

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Previous Preloading is conflicting with ours ones 

Have a look Ones you reload the site

**Comment by SubhamB2003** [comment]
> Previous Preloading is conflicting with ours ones
> 
> Have a look Ones you reload the site

@thestarsahil Hey, I checked actually here you also use lazy loading so both are run in their time you can check below video the 

https://github.com/Counselllor/Counsellor-Web/assets/94003231/7cdcfb48-4374-4e17-8652-f68d276051f7

**Comment by thestarsahil** [comment]
Resolve the conflict and generate once again !

**Comment by SubhamB2003** [comment]
@thestarsahil Can you merge this pr

**Pull request closed without merging**
