### PR TITLE
Created  Top University Responsive , Dark mode adaptable Page 

### LINKED ISSUE #988: Want to create the top universities page
**Is your feature request related to a problem? Please describe.**
I want to create the top universities page for the website 
For that i will fetch the real time api or user json format file to store the top universities and show the lists to the user 
I will show that in the form of cards with the name , description and location 

image

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have created a top university page 
It is responsive too 
It can adopt dark mode like i created this for dark mode as well

## Screenshots

https://github.com/user-attachments/assets/8ad30968-b882-4bf3-96b8-523175864d6f

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Pull the latest change and push again

**Comment by Ayushmaanagarwal1211** [comment]
Ok sir

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Done Sir

**Comment by thestarsahil** [comment]
Work on footer area it not been fixed yet

**Comment by Ayushmaanagarwal1211** [comment]
Ok sir

**Comment by Ayushmaanagarwal1211** [comment]
image
@thestarsahil  Sir i fixed that

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-14 19-57-22

Fix this

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Fixed Sir

**Comment by thestarsahil** [comment]
resolve conflict

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Done Sir Please check

**Comment by thestarsahil** [comment]
@Ayushmaanagarwal1211 Pull the latest changes and update the upstream

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir its already updated

**Comment by Ayushmaanagarwal1211** [comment]
image

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
