### PR TITLE
Email validation add on forgot password form

### LINKED ISSUE #288: Empty field check for forgot password form and email validation add
Email field should not be empty , if empty after submit generate error message to user
Email should be in correct format validation add 
Error message highlight below the field
Screenshot (26)

@thestarsahil I would like to work on it. Please assign this to me.

### PR DESCRIPTION
**Pull request by Geeta259**
## Fixes #288

# Description
Email should be in correct format validation add
Error message highlight below the field.

## Screenshots
Screenshot (75)
Screenshot (76)

## Checklist

- [x ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ x] Code follows the established coding style guidelines
- [ x] All tests are passing

@thestarsahil  Look out this PR linked with issue #288

### CODE REVIEW

**Comment by thestarsahil** [comment]
Actually it is working when empty block , Not when filling the wrong email 
I want show invalid while trying to type invalid email address
I hope you got the point , If you fell any query about this,  Raise question I am happy to help you 


<input
  type="email"
  value={email}
  onChange={(event) => {
    setEmail(event.target.value);
    if (!validEmail(event.target.value)) {
      setError("**Enter a valid E-mail!");
    } else {
      setError("");
    }
  }}
  placeholder="Enter your email address"
  className={`common-input ${error === '**Enter a valid E-mail!' ? 'error' : ''}`}
/>

**Comment by Geeta259** [comment]
@thestarsahil  Now check is it ok ?

**Review by thestarsahil — APPROVED** [review]
Now That's Working ! I hope you got to learn from mistake 
Keep Learning and Contributing 
Thank You

**Comment by Geeta259** [comment]
@thestarsahil yes Thank You :)

**Pull request merged**
