### PR TITLE
added tailwind

### LINKED ISSUE #718: Adding tailwind
**Is your feature request related to a problem? Please describe.**
I want to first try to replace the css by tailwind

### PR DESCRIPTION
**Pull request by ayush-848**
# Description

Updated the [ages with tailwind.

## Screenshots
image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil please merge this one first other wise people will change the css which I have removed to add tailwind

**Comment by thestarsahil** [comment]
How could i merge this , this change effecting the whole pages !

**Comment by ayush-848** [comment]
@thestarsahil Can u please Install tailwind in this project.

I will make a fresh PR.

Because in my server everything works, I don't know the problem in main website

**Comment by thestarsahil** [comment]
Okay , Resolve this I am checking ahead now

**Pull request closed without merging**
