### PR TITLE
Complete Backend Integration for Job Application page 

### LINKED ISSUE #1059: Want to write the backend of the Job Application Page
**Is your feature request related to a problem? Please describe.**
I want to write the backend of the job application page 
Thorough whihc it can fetch real time data where users can respond to it 

image

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have created the complete Backend For the Job Application page 
Here i am storing that data in the database and the live data will be visible to the jobs page 

## Fixes #1059 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

https://github.com/user-attachments/assets/c702106c-29ed-487c-90c2-833192a7b3b0

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Do a sort fun. according to date posted

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Ok

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Done sir 



https://github.com/user-attachments/assets/52b4e30b-b3bc-48d7-afae-11b0edf19ac5

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Removed

**Comment by thestarsahil** [comment]
Security level check : 

Database Security Rules:
```
{
  "rules": {
    "users": {
      "$uid": {
        ".read": "auth != null && auth.uid == $uid",
        ".write": "auth != null && auth.uid == $uid"
      }
    },
    "jobs": {
      ".read": "auth != null",
      ".write": "auth != null",
      "$job_id": {
        ".write": "auth != null && data.child('companyName').val() != 'Soft'"
      }
    }
  }
}
```

Sanitizing User Input:
```
import validator from 'validator';

const handleChange = (event) => {
  const { name, value } = event.target;
  const sanitizedValue = validator.escape(value); // Sanitize input
  setFormData((prevData) => ({
    ...prevData,
    [name]: sanitizedValue,
  }));
};
```

File Upload Validation:

```
const handleFileChange = (event) => {
  const file = event.target.files[0];
  const validFileTypes = ['application/pdf', 'application/msword'];
  const maxFileSize = 2 * 1024 * 1024; // 2 MB

  if (file && validFileTypes.includes(file.type) && file.size <= maxFileSize) {
    // Handle file upload
  } else {
    alert('Invalid file type or size. Please upload a PDF or Word document less than 2MB.');
  }
};
```

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil sir can you please explain little bit more i didn't understand correctly

**Comment by thestarsahil** [comment]
In you code  , the quality of code is low and security of your code easily crackable 
So , this i wrote you can modify in your code and try to run again

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i have optimized the code and did some changes can you please check again

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
