### PR TITLE
Tech stack

### LINKED ISSUE #1186: [Feat] : When user click on student tech stack display popup
**Is your feature request related to a problem? Please describe.**

@thestarsahil 

we can display pop up of tech stack when user click on tech stack in student profile

image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

@thestarsahil 

[Feat] : When user click on student tech stack display popup #1186

close #1186

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly please check this and merge it
if you need any modifications, please inform me

**Comment by thestarsahil** [comment]
Fix the gap bw navabar and college section(8)

Fix this

**Comment by dhruv8433** [comment]
@thestarsahil 

as you said i updated my routing path

**Comment by dhruv8433** [comment]
@thestarsahil 

check this out,

https://github.com/user-attachments/assets/30216a35-45ba-4794-87d9-d32584280a80

**Comment by dhruv8433** [comment]
@thestarsahil 

Also review #1191

**Comment by thestarsahil** [comment]
join the vc

**Comment by dhruv8433** [comment]
ok

**Comment by dhruv8433** [comment]
@thestarsahil 

please check this and merge it

student layout

image

tech stack 

image

**Pull request merged**
