### PR TITLE
fixed the help page

### LINKED ISSUE #1291: Fonts and colors of some part of Jobs page is not matching
image
image

### PR DESCRIPTION
**Pull request by ayush-848**
# Description

fixed the help page

## Screenshots

image
image
image
image
image
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil please check

**Comment by thestarsahil** [comment]
The changes effect to whole website

**Comment by ayush-848** [comment]
> The changes effect to whole website

Why it is happening??
I just changed the style

**Comment by ayush-848** [comment]
@thestarsahil please check now

**Comment by ayush-848** [comment]
@thestarsahil please check now

**Comment by thestarsahil** [comment]
Changes still effecting to login

**Comment by ayush-848** [comment]
> Changes still effecting to login

can you give me some suggestions. I don't know where it went wrong

**Comment by ayush-848** [comment]
@thestarsahil can you show me the error logs

**Pull request closed without merging**
