### PR TITLE
Changed Footer

### PR DESCRIPTION
**Pull request by Pranali3103**
# Description

## Screenshots
https://github.com/Counselllor/Counsellor-Web/assets/122550529/de0c73c3-6b67-4259-bde4-b144ebd72b53)

## Checklist
- [x] Footer has been added to this repository
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by Pranali3103** [comment]
@Avinash905 I have already worked on issue , please review it and merge into master branch

**Comment by thestarsahil** [comment]
Thanks for contributing but its effecting to all responsive part of webapp
Have a look 
Screenshot from 2024-05-15 10-25-02

**Comment by Pranali3103** [comment]
Hello @thestarsahil Now its working completely fine. please check out and merge the commit with responsive footer

**Comment by thestarsahil** [comment]
Before Merging please update the pull request then commit the changes again !
Branch is conflicting

**Pull request closed without merging**
