### PR TITLE
Navbar Updated on all existing pages

### LINKED ISSUE #677: Fix navbar on every page
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by sau-mili**
# Description
Added Navbar/ Fixed it in About, college, contact pages
Edited the default Navbar.jsx file to be used in all future pages

## Fixes #677 

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Working good but you actually added this property to specific pages but we want that navbar property work same for all pages 
Just as importing navbar into any pages and it will reflect to that pages !
Is it possible to do ?

**Comment by sau-mili** [comment]
Yes it is now possible, I have changed the Navbar file as well. I haven't modified esixting pages with the importation because those have a lot of dependencies, I am not sure of, since those are written in different format. Otherwise now you can add the navbar.jsx from navbar folder into any upcoming pages.

**Comment by thestarsahil** [comment]
That's Great !

**Comment by thestarsahil** [comment]
11:26:25 AM [vite] Failed to load source map for /workspaces/Counsellor-Web/src/components/About/About.css.
Error: An error occurred while trying to read the map file at main.css.map
Error: ENOENT: no such file or directory, open '/workspaces/Counsellor-Web/src/components/About/main.css.map'
    at async open (node:internal/fs/promises:636:25)
    at async Object.readFile (node:internal/fs/promises:1246:14)
    at async extractSourcemapFromFile (file:///workspaces/Counsellor-Web/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:20842:53)
    at async loadAndTransform (file:///workspaces/Counsellor-Web/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:52329:27)

**Comment by sau-mili** [comment]
can you check now?

**Pull request closed without merging**
