### PR TITLE
Contact Page

### LINKED ISSUE #421: Contact Page
## Description

I would like to add a Contact Page to the website

Please assign me this issue under IWOC

### PR DESCRIPTION
**Pull request by JiyaGupta-cs**
Closes #421 

image

### CODE REVIEW

**Comment by thestarsahil** [comment]
Can you use animation in this page , its so static
We want in dynamic

**Comment by JiyaGupta-cs** [comment]
@thestarsahil
I can build the website in parts, step by step sp that my number of PRs get increased as I am lagging behind in the Iwoc

**Review by thestarsahil — COMMENTED** [review]
Added Contact Page Successfully !
Totally Working Fine and Responsive

**Comment by JiyaGupta-cs** [comment]
@thestarsahil Please merge it

**Pull request merged**
