### PR TITLE
fixed the text-area in contact page

### LINKED ISSUE #600: The message text-are in the contact section is not fixed
**Describe the bug**
The text-area can be made smaller or larger by hold & drag

**Expected behavior**
It should remain fixed

image

image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave

### PR DESCRIPTION
**Pull request by ayush-848**
# Description
The text-area was variable and animation was not working. I fixed its position and made the animation to work. 

## Screenshots
image
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil If I change it to classname as per the tests, the Message area will start misbehaving. You can check the commits

**Review by thestarsahil — APPROVED** [review]
Working Good !

**Comment by ayush-848** [comment]
@thestarsahil which part has got affected??

**Comment by ayush-848** [comment]
> @thestarsahil which part has got affected??

Ohh yeah
Got it

**Comment by ayush-848** [comment]
@thestarsahil let me open a new issue and make a PR

**Comment by ayush-848** [comment]
@thestarsahil do something about the #620.

Because I have to refork the repo again.

**Comment by thestarsahil** [comment]
> @thestarsahil do something about the #620.
> 
> Because I have to refork the repo again.
> 

Okay ...First Push the About page changes 
Then push the next PR of FAQ

**Comment by ayush-848** [comment]
@thestarsahil About page?

> > @thestarsahil do something about the #620.
> > Because I have to refork the repo again.
> 
> Okay ...First Push the About page changes Then push the next PR of FAQ

**Comment by ayush-848** [comment]
@thestarsahil I have updated the #620, I have added margin-top in contact.css. It should do it.

**Pull request merged**
