### PR TITLE
Added Floating animation 

### LINKED ISSUE #683: Floating animation in the log in image
**Is your feature request related to a problem? Please describe.**
Implement floating animation to create a smooth, visually appealing movement for the input fields, captcha box, and login button. The elements should gently float or move slightly up and down, creating a dynamic and engaging user experience.

**Describe the solution you'd like**
The floating animation effect aims to improve the user interface (UI) by adding a subtle, engaging visual element to the login page. This will enhance the overall user experience (UX) by making the login process more enjoyable and visually appealing.

**Describe alternatives you've considered**
Community Engagement:

Enhanced Experience: Provides a pleasant and modern user experience, encouraging more frequent use.
Professional Appearance: Contributes to a more polished and professional appearance of the application.
Project Growth:

Attracting Users: A visually appealing login page can attract more users and increase sign-ups.
User Retention: Improves user satisfaction, potentially leading to higher retention rates.

**Additional context**
image

### PR DESCRIPTION
**Pull request by Damini2004**
# Description

Here i have added the floating animation to the home image to grab more number of user attention.

## Fixes  #683 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

Uploading Counsellor Portal and 2 more pages - Personal - Microsoft​ Edge 2024-06-19 12-38-02.mp4…

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by Damini2004** [comment]
@thestarsahil Kinldy review the PR.

**Review by thestarsahil — APPROVED** [review]
Working great

**Comment by thestarsahil** [comment]
I request to submit more PR containing level 3 and did you joined the discord channel ?

**Comment by Damini2004** [comment]
No kindly share discord link and add level label to this merged PR

**Comment by thestarsahil** [comment]
https://discord.com/channels/1231112132595028008/1239913420749410335
Join this

**Pull request merged**
