### PR TITLE
Created same navbar as dashboard and fixed the working of the links 

### LINKED ISSUE #903: The navbar links from the carrer support are not clickable
**Is your feature request related to a problem? Please describe.**
When i am clicking on any link the link is not clickable lie it is not routing to any url anymore 

https://github.com/Counselllor/Counsellor-Web/assets/118350936/f08339cf-b910-4aef-a639-30e5a4e9d721

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have created a same navbar for the carrers page as dashboard
I also fixed the linkks that are not working properly now its working properly 

## Screenshots

https://github.com/Counselllor/Counsellor-Web/assets/118350936/4255f18e-cdca-49c2-a214-12c06ee92ee5

https://github.com/Counselllor/Counsellor-Web/assets/118350936/9e0debd1-4674-4e69-b039-98e7a54e3ba5

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Please also check this

**Comment by thestarsahil** [comment]
Resolve the conflict

**Comment by Ayushmaanagarwal1211** [comment]
Ok solving

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Please check i removed the conflict

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
