### PR TITLE
Fixed showing the toast only one time and Given access to footer routes without login

### LINKED ISSUE #940: Want to show the toast only one time and GIving access to footer routes without login
**Is your feature request related to a problem? Please describe.**
I want some changes are as follows :- 

- Want to show the toast single time after login not multiple times 
- Want to give access to all routes to the user without login

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I Include multiple things in this pr are as follows : 
- I created a login for showing the toast only one time after loging
- I have given access to only those routes who are in footer without login 
- For accessing the routes in the navbar must have to logged in

## Screenshots

https://github.com/Counselllor/Counsellor-Web/assets/118350936/871ec8e1-202b-42a6-870d-294f6d2aba01

https://github.com/Counselllor/Counsellor-Web/assets/118350936/26e7d689-b0c1-4e1f-a7f3-cf2bc6143ea0

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  I included both toast and routes in this pr if possible please review it first because i changes many files so it will surely get conflict

**Comment by thestarsahil** [comment]
Toast wokring Rest of thing not working
try to pull latest changes and push again

**Comment by thestarsahil** [comment]
yes

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  

https://github.com/Counselllor/Counsellor-Web/assets/118350936/654e9b09-60d8-47d7-a33a-ded1782458eb

Sir i did that like this it will access footer routes for all other routes it will redirect to login 
are you seeing any other behavious in you laptop ?

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-08 19-32-57

How blog page showing logout without login 
work on it ,make it same as contact us page navbar

**Comment by Ayushmaanagarwal1211** [comment]
> Screenshot from 2024-07-08 19-32-57
> 
> How blog page showing logout without login work on it ,make it same as contact us page navbar

Ok sir doing actually I didn't change anything with navbar I used other logic that's why it is showing logout

**Comment by thestarsahil** [comment]
Do this I am merging this

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil done sir

**Comment by Ayushmaanagarwal1211** [comment]
> @thestarsahil done sir

I updated the code for blogs page

**Comment by Ayushmaanagarwal1211** [comment]
> > @thestarsahil done sir
> 
> I updated the code for blogs page

I am checking for other pages

**Comment by thestarsahil** [comment]
No other pages left 
I am merging this

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  

https://github.com/Counselllor/Counsellor-Web/assets/118350936/68cb6eaf-2efe-463e-a7f6-b8d7dd937d73

I have updated the code please check is it working now or not

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  I have already updated the code and getting conflict please review it

**Comment by thestarsahil** [comment]
I want the same navbar of contact page into blog page

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-08 21-52-58

**Comment by Ayushmaanagarwal1211** [comment]
Ok sir doing

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Done

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Done

**Comment by thestarsahil** [comment]
Remove the toast effect its done already , Only your footer routering changing merging right now

**Comment by Ayushmaanagarwal1211** [comment]
OK

**Comment by thestarsahil** [comment]
Look , I think you are not understanding what i am trying to say 
Conditon applies If user login already then show the navbar of dasbhboard navbar everywhere 
else if user not logout then show the navbar of contact us page everywhere

if login already show this : 
Screenshot from 2024-07-08 22-22-44

If not login then show this :
Screenshot from 2024-07-08 22-23-12

**Comment by Ayushmaanagarwal1211** [comment]
> Look , I think you are not understanding what i am trying to say Conditon applies If user login already then show the navbar of dasbhboard navbar everywhere else if user not logout then show the navbar of contact us page everywhere
> 
> if login already show this : Screenshot from 2024-07-08 22-22-44
> 
> If not login then show this : Screenshot from 2024-07-08 22-23-12

Ok sir now i understood but am i correct to apply navbar to only contact and blog page like i should leave other pages like terms and help

**Comment by thestarsahil** [comment]
> > Look , I think you are not understanding what i am trying to say Conditon applies If user login already then show the navbar of dasbhboard navbar everywhere else if user not logout then show the navbar of contact us page everywhere
> > if login already show this : Screenshot from 2024-07-08 22-22-44
> > If not login then show this : Screenshot from 2024-07-08 22-23-12
> 
> Ok sir now i understood but am i correct to apply navbar to only contact and blog page like i should leave other pages like terms and help

excatly !

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  I updated that i think its correct this time

**Comment by Ayushmaanagarwal1211** [comment]
Uploading bandicam 2024-07-08 22-44-55-356.mp4…

@thestarsahil  I have uploaded a video please have a look

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/Counselllor/Counsellor-Web/assets/118350936/37f8f90c-b145-4c7d-a43c-0c878647f7a1

> 
> @thestarsahil I have uploaded a video please have a look

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-11 18-30-42
Screenshot from 2024-07-11 18-30-56
Screenshot from 2024-07-11 18-31-04
Screenshot from 2024-07-11 18-30-42

Do the navbar for this

**Comment by Ayushmaanagarwal1211** [comment]
> Screenshot from 2024-07-11 18-30-42 Screenshot from 2024-07-11 18-30-56 Screenshot from 2024-07-11 18-31-04 Screenshot from 2024-07-11 18-30-42
> 
> Do the navbar for this

Ok

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Please check

**Comment by thestarsahil** [comment]
update the branch

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Please check i updated

**Comment by thestarsahil** [comment]
Working Good but one error 
[Screencast from 2024-07-11 19-57-57.webm](https://github.com/Counselllor/Counsellor-Web/assets/84167034/be9e580e-2e52-42fd-bfae-513888f2a98c)

As you can see in the video the navbar suddenly change when user already login 
See the navbar effect after login

**Comment by Ayushmaanagarwal1211** [comment]
> Working Good but one error [Screencast from 2024-07-11 19-57-57.webm](https://github.com/Counselllor/Counsellor-Web/assets/84167034/be9e580e-2e52-42fd-bfae-513888f2a98c)
> 
> As you can see in the video the navbar suddenly change when user already login See the navbar effect after login

I fixed that please see @thestarsahil

**Review by thestarsahil — APPROVED** [review]

**Comment by thestarsahil** [comment]
@Ayushmaanagarwal1211 Make a new PR , do the same for top university , job, courses and carrier page

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Ok doing

**Pull request merged**
