### PR TITLE
Want to Add Skeletons to profile cards, and Blogs page And any other page where Api is involved #1221

### LINKED ISSUE #1221: Want to Add Skeletons to  profile cards, and Blogs page And any other page where Api is involved
image
image

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

Added Skeletons in all necesarry places And they are responsive +darkmode

## Fixes #1221 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

Screenshot 2024-07-26 031534
Screenshot 2024-07-26 034922
Screenshot 2024-07-26 041643
Screenshot 2024-07-26 042432

## Checklist

- [x ] Tests have been added or updated to cover the changes
- [x ] Documentation has been updated to reflect the changes
- [x ] Code follows the established coding style guidelines
- [x ] All tests are passing

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @thestarsahil please merge pr  #1245  then this else it will cause conflicts

**Comment by thestarsahil** [comment]
create a new branch for this and Make a new PR

**Comment by thestarsahil** [comment]
Remove the increase contributor list from your side , we are happy with previous change

**Comment by nishant0708** [comment]
Hey @thestarsahil it's new branch only ..

**Comment by thestarsahil** [comment]
No i am not saying , i meant to say 
create a other branch , so i can checkout-branch-name and easily to merge

**Comment by nishant0708** [comment]
hey @thestarsahil done .its fixed

**Comment by thestarsahil** [comment]
@nishant0708 Do for all pages

**Comment by nishant0708** [comment]
> @nishant0708 Do for all pages

Which page ? In profile page I tried but it is quite difficult to make skeleton for that I will do that after fixing dark mode

**Pull request merged**
