### PR TITLE
Enhanced terms and condition page and Join us page 

### LINKED ISSUE #835: Want to enhance the Terms and condition and Joins us  page
**Is your feature request related to a problem? Please describe.**
I want to enhance the terms and condition page for the website 

**Describe the solution you'd like**
I want to add some animation
Want to add dark mode for that 
Want to add navbar and footer
want to change the color of heading so that heading looks different from the text
want to Enhance the formatting for this 

Screenshot 2024-07-03 005136

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have enhanced this in following ways :- 
- Added navbar
- added fade up animation
- Created dark mode for both pages 

sir i enhanced it according to me but if you want any other changes pelase let me know

## Screenshots

https://github.com/Counselllor/Counsellor-Web/assets/118350936/0f854b4a-5fdf-4658-8930-9dfe20373443

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
No need to add navbar here !

**Comment by Ayushmaanagarwal1211** [comment]
Ok removing

**Comment by Ayushmaanagarwal1211** [comment]
Should i remove this from both the pages

**Comment by thestarsahil** [comment]
yes

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  I  removed that

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-06 22-23-06
Same texture do with other pages also

**Comment by Ayushmaanagarwal1211** [comment]
> Screenshot from 2024-07-06 22-23-06 Same texture do with other pages also

@thestarsahil  sir means same type of color and animation i have to give all pages where the text is written am i correct

**Comment by thestarsahil** [comment]
@Ayushmaanagarwal1211 Yes do with all pages

**Comment by Ayushmaanagarwal1211** [comment]
Ok doing

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/Counselllor/Counsellor-Web/assets/118350936/e09171b5-907c-4511-bc0d-3c793b41e83a


@thestarsahil  I have added Animation to all texts

**Comment by thestarsahil** [comment]
Don't do any other Changes 
I want the  term page should as same as on help page, privacy page, join us page ! That's it

**Comment by Ayushmaanagarwal1211** [comment]
Ok ok doing

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir please check i have created same textures for Terms , Help , Join us and privacy page only

**Comment by Ayushmaanagarwal1211** [comment]
> @thestarsahil Sir please check i have created same textures for Terms , Help , Join us and privacy page only

Sir i got conflict so i just removed that if you see any unwanted change please let me know

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
