### PR TITLE
Contact us redesigned

### LINKED ISSUE #1151: Improve UI of contact us
**Is your feature request related to a problem? Please describe.**
I want to improve the ui of contact us page by adding images and good ui layout to form and content

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by komal-agarwal5**
# Description

I have redesigned the contact us page
- Added background cover
- Changed layout and alignment
- Fixed form
- Text effects added
- Provisional styling for both light and dark modes
- Mobile responsive

## Screenshots

https://github.com/user-attachments/assets/0b56dba7-8097-4fc1-8fbb-32bb4f8462e9

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
The quality of backgorund pic is too low grade , 
Try this :https://www.pexels.com/search/telephone/

**Comment by komal-agarwal5** [comment]
@thestarsahil pls check now once

**Comment by thestarsahil** [comment]
Fix the gap bw navabar and college section(9)

Replace it as mark via arrow

**Comment by thestarsahil** [comment]
First pull the latest changes .. recently updated the master branch

**Comment by komal-agarwal5** [comment]
@thestarsahil done

**Comment by komal-agarwal5** [comment]
@thestarsahil done

**Comment by thestarsahil** [comment]
Let me check !!

**Comment by thestarsahil** [comment]
It's not like that i am trying to convey , Come on VC i explain

**Comment by komal-agarwal5** [comment]
> It's not like that i am trying to convey , Come on VC i explain

Yes

**Comment by komal-agarwal5** [comment]
> Some of the changes have to be done , I will raise pr and issue to you the things i will mentioned there @komal-agarwal5

Ok do let me know what kind of changes are needed,I will make it

**Comment by komal-agarwal5** [comment]
@thestarsahil u can check
Made into single page visibility
Adjusted bg image transaparency with content
And remaining alignments also

**Comment by thestarsahil** [comment]
The previous change is fine you just have to slighty change , this was unexprected change 

Screenshot from 2024-07-25 22-56-49

**Comment by komal-agarwal5** [comment]
> The previous change is fine you just have to slighty change , this was unexprected change
> 
> Screenshot from 2024-07-25 22-56-49

Ok fixing it by eod

**Comment by komal-agarwal5** [comment]
image
Done
@thestarsahil can u pls merge it

**Comment by thestarsahil** [comment]
Fix the gap bw navabar and college section(11)

**Comment by komal-agarwal5** [comment]
https://github.com/user-attachments/assets/76705acc-8f08-40a7-b6a5-82b453305923

@thestarsahil check this recording once
Screen scroll when done only then footer coming with HD quality bg image

**Comment by thestarsahil** [comment]
In Dark Mode the Image quality too low do that also

**Comment by thestarsahil** [comment]
Footer section is not responsive

**Pull request closed without merging**
