### PR TITLE
College detailed

### LINKED ISSUE #860: [Feat] : Redesign college detailed page
**Is your feature request related to a problem? Please describe.**

@thestarsahil 

we can redesign college deatiled page

image

something like this

image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

[Feat] : Redesign college detailed page #860

## Fixes #860(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly please check this and merge it

**Comment by thestarsahil** [comment]
The color Pattern should be same as , no additional color 
and your branch is not updated , before push first check git status , if uptodate branch then push your changes

**Comment by thestarsahil** [comment]
https://counsellor.social/dashboard
This is not our latest branch updates 
Do first that

**Comment by dhruv8433** [comment]
@thestarsahil 

now you can merge this

image

**Comment by thestarsahil** [comment]
Your css changes effecting to other pages 
Carefully use classnames on css

**Pull request closed without merging**
