### PR TITLE
Icons in form Fields

### LINKED ISSUE #328: Add icons in signup and login form.
**feature**
We can add relatable icons in the form fields of the signup and login page to make the site UI more appealing and improve the aesthetics.

**Here is the example of a site where I have added the icons in the form fields:**

**Signup**

**Login**

If you think it would be worth implementing then please assign me this issue under gssoc23 label.

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
# Description
**Added Icons in form-fields of login and signup form and Fixed the uneven width of fields in form**

## Fixes #328 

closes #328 **Add icons in signup and login form.**

## Screenshots

**Sign up**

**Login**

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@thestarsahil please review this PR as early as possible

**Review by thestarsahil — APPROVED** [review]
Code Approved !

**Comment by thestarsahil** [comment]
Make Sure Raise PR as sson as possible ,  if you working on another issue 
END DAY GSSoc23

**Comment by AlfiyaSiddique** [comment]
> Make Sure Raise PR as sson as possible , if you working on another issue END DAY GSSoc23

Yes will be raising one more PR by 10 pm

**Pull request merged**
