### PR TITLE
Disallow Future date as birth date on sign-up page #614

### PR DESCRIPTION
**Pull request by mahak-juriani**
date_pics

Issue Solved #614

### CODE REVIEW

**Comment by thestarsahil** [comment]
Screenshot from 2024-05-27 18-12-15

Its DD/ MM / YYYY Fix it !

**Comment by mahak-juriani** [comment]
closes #614

**Comment by mahak-juriani** [comment]
Hey @thestarsahil 
I tried replicating the issue on both local and deployed branches, but no luck - 
image

image

Could there be a case that someone has already solved it?
Or could you provide me the steps to replicate, i've checked signup form by clicking Don't have an account? button.

Please suggest, thanks

**Comment by thestarsahil** [comment]
@mahak-juriani 

This is the reference , I think now you gonna fix this 


```
const ageCalculator = (dob) => {
  const birthDate = new Date(dob);
  const currentDate = new Date();
  let age = currentDate.getFullYear() - birthDate.getFullYear();

  const birthMonth = birthDate.getMonth() + 1; // Months are zero-indexed
  const currentMonth = currentDate.getMonth() + 1;

  if (
    currentMonth < birthMonth ||
    (currentMonth === birthMonth && currentDate.getDate() < birthDate.getDate())
  ) {
    age--;
  }

  // Return date in DD/MM/YYYY format
  return birthDate.toLocaleDateString('en-US', {
    day: 'numeric',
    month: 'numeric',
    year: 'numeric',
  });
};

// Example usage
const dob = "1980-12-31";
const birthDateStr = ageCalculator(dob);
console.log(birthDateStr); // Output: 31/12/1980

```

**Comment by thestarsahil** [comment]
@mahak-juriani Are you working on this ?

**Pull request closed without merging**
