### PR TITLE
Enhanced Cards Section in Dashboard 

### LINKED ISSUE #826: Enhancing college card for dark and light mode
**Is your feature request related to a problem? Please describe.**
I want to enhance the card design in the dark and light mode 

Screenshot 2024-07-02 193531

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description
I have enhanced the cards section in dashboard by following ways : -

1. Added Location with some new Type
2. Added box shadow for dark mode
3.Added Border for dark mode 
4. Changed the read more button with new css 
5. Added Hover Effect 

## Screenshots

https://github.com/Counselllor/Counsellor-Web/assets/118350936/71268903-9b4d-45fe-bd35-5652c529097f

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-03 21-08-05
Screenshot from 2024-07-03 21-08-20
Screenshot from 2024-07-03 21-08-38

Fix this !

**Comment by Ayushmaanagarwal1211** [comment]
Oh ya i i used the wrong class name

**Comment by Ayushmaanagarwal1211** [comment]
I am fixing this just wait a minute

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil i fixed that please check

**Review by thestarsahil — APPROVED** [review]
Working good but have to work more

**Pull request merged**
