### PR TITLE
Added social links in student sections

### LINKED ISSUE #1188: [Feat] : Add social link popup
**Is your feature request related to a problem? Please describe.**

@thestarsahil 

we can add social link pop up in student detailed

image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

@thestarsahil 

[Feat] : Add social link popup #1188

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #1188(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil sir,

kindly please review it and merge it
please add level 3

i think you forgot to add level in https://github.com/Counselllor/Counsellor-Web/pull/1191 pr
please add level sir

**Comment by thestarsahil** [comment]
Remove the social icon from background

**Comment by dhruv8433** [comment]
@thestarsahil 

removed 

image

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-25 23-05-35

Make like this , same

**Comment by dhruv8433** [comment]
@thestarsahil 

i updated my code now you can merge it
and make it same as tech stack page

image

**Comment by thestarsahil** [comment]
create a new branch for this and Make a new PR

**Pull request closed without merging**
