### PR TITLE
Want to Add Functionality To Seach blog by Author Name,Title ,Tag #1285

### LINKED ISSUE #1285: Want to Add Functionality To Seach blog by Author Name,Title ,Tag
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #1285

image

onclicking on search mode you can get option to 
image

## Checklist

- [X ] Tests have been added or updated to cover the changes
- [X ] Documentation has been updated to reflect the changes
- [X ] Code follows the established coding style guidelines
- [ X] All tests are passing

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @thestarsahil Done

**Comment by thestarsahil** [comment]
@nishant0708 I implemented this , but not fit for it unfortunately we have to close this

**Comment by thestarsahil** [comment]
yes , some light or easily hide in corner

**Comment by nishant0708** [comment]
> yes , some light or easily hide in corner

@thestarsahil  sir  i am not able to understand can you elobrate it i will do that

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-29 19-00-43
Screenshot from 2024-07-29 19-00-51
Screenshot from 2024-07-29 19-01-01

see this search icon , quite light in website

**Comment by thestarsahil** [comment]
is it possible to make like this ?

**Comment by nishant0708** [comment]
> is it possible to make like this ?

@thestarsahil  sir i can make   like on clicking on search item it will open modal and search like  in Image But our blog Ui is Quite Different it will Not look good . 
image

**Comment by nishant0708** [comment]
and sir its request please Add in pr #1292 .remove level 3 and assign it level 2

**Comment by nishant0708** [comment]
And Pr #1294  Please Add Gssoc Label and level 1

**Comment by thestarsahil** [comment]
try once how you gonna make

**Pull request closed without merging**
