### PR TITLE
Feat upgrade : Internship page created

### LINKED ISSUE #790: feat update : creating jobs page
**Is your feature request related to a problem? Please describe.**
currently there is no page for jobs section

**Describe the solution you'd like**
i want to make a complete jobs page that will increase the usability of the website as students can search job from there

**Describe alternatives you've considered**

**Additional context**
Screenshot 2024-06-28 145743
something like this
@sau-mili I am a gssoc'24 contributor please assign this to me

### PR DESCRIPTION
**Pull request by anwesha2002**
# Description

This PR adds a new feature. This adds an new internship page to the website along with jobs

## Fixes #790 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

Screenshot 2024-07-20 043913

## Checklist

- [ x] Tests have been added or updated to cover the changes
- [ x] Documentation has been updated to reflect the changes
- [x ] Code follows the established coding style guidelines
- [ x] All tests are passing

### CODE REVIEW

**Comment by anwesha2002** [comment]
@thestarsahil please check this merge it

**Comment by thestarsahil** [comment]
As our project follow color pattern , you have to work on that 

Reference : https://www.apple.com/careers/in/

**Comment by anwesha2002** [comment]
> As our project follow color pattern , you have to work on that
> 
> Reference : https://www.apple.com/careers/in/

Can i make it like the job page color pattern??

**Comment by thestarsahil** [comment]
@anwesha2002 Yes

**Comment by thestarsahil** [comment]
UI for Internship page Reference 

image
image
image

**Comment by thestarsahil** [comment]
create a New Branch and New PR

**Pull request closed without merging**
