### PR TITLE
subscribers data added to databse

### LINKED ISSUE #1278: [Feat] : Store Subsciber data in database
**Is your feature request related to a problem? Please describe.**

@thestarsahil 

we can store subscribe email in database and send mail using mailjs

image

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

@thestarsahil 

[Feat] : Store Subsciber data in database #1278

## Fixes #1278(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Its showing on console log , not on firebase database

**Comment by dhruv8433** [comment]
@thestarsahil 

now check that 
i am tested that by logging all emails in console and i got all subscribers data 
currently in code i removed console of all users

image

check this image i got all subscribers

**Comment by dhruv8433** [comment]
@thestarsahil 

please check this and merge it

**Comment by thestarsahil** [comment]
That's how data not stored in database @dhruv8433 
Attacker can easily read the code you written and showing all mail in console log

**Comment by dhruv8433** [comment]
@thestarsahil 

I removed that part of code
I just conform that data is stored or not in database

You can check live preview the console not displayed

**Comment by dhruv8433** [comment]
@thestarsahil 

please check this 
i fetched upstream and remove unnecessary console

it will store subscibers data in newsletter/emails table

**Comment by thestarsahil** [comment]
@nishant0708 Can you help me to get fetch data into database

**Comment by nishant0708** [comment]
hey @dhruv8433 @thestarsahil  i think its already working 
image
see

**Comment by nishant0708** [comment]
hey @dhruv8433 if task was different so please connect me on discord i will help you with this Vc

**Pull request closed without merging**
