### PR TITLE
Captcha Vulnerability

### LINKED ISSUE #516: Captcha Vulnerability
**Is your feature request related to a problem? Please describe.**
The captcha in the sign up page is simple text. It can viewed just by inspecting the webpage. This makes to website vulnerable to bot attacks.

Screenshot 2024-05-12 at 12 09 27 AM

**Describe the solution you'd like**
I would like to change it to using a captcha api like hcaptcha or reCaptcha.

### PR DESCRIPTION
**Pull request by Pranali3103**
# Description

Since earlier the captcha was more vulnerable to attack as text based captcha was showing , getting displayed on inspection of website , so I have added google reCaptcha , captcha authentication . This captcha has been added at signup page , by today it will be on login page also.
For verifying in both client and server side , I have created a server's side api for captcha and validated .
Also by this side "https://www.google.com/recaptcha/admin/create" I  have created recaptcha , if you want to use , you can also create you own site and secret key.

## Screenshots
Screenshot -01
Captcha

ScreenShot-02
captchaverification

## Checklist
- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by Pranali3103** [comment]
Please review this and merge the code.

**Comment by thestarsahil** [comment]
Variable used before definition

```
    }

    if (name === "dob") {
      **const calculateAge = ageCalculator(e.target.value);**
      setUserInfo(prev => ({ ...prev, age: calculateAge || "" }));
    }
  };
```

**Comment by Pranali3103** [comment]
Its inside the function call , its not individual , whenever there would be calling of function handleUserInfo , then it will be envoked.
 const handelUserInfo = (e) => {
    const { name, value } = e.target;
    setUserInfo(prev => ({ ...prev, [name]: value }));

    if (name !== "user-type" && name !== "gender") {
      const errObj = validate[name](value);
      setError(prev => ({ ...prev, ...errObj }));
    }

    if (name === "dob") {
      const calculateAge = ageCalculator(e.target.value);
      setUserInfo(prev => ({ ...prev, age: calculateAge || "" }));
    }
  };

**Comment by Pranali3103** [comment]
Please review it again , I changed it.

**Comment by thestarsahil** [comment]
Screenshot from 2024-05-22 21-23-24


Discard the Changes not working in our application !
Please work on another Issue !
Thank you !

**Comment by Pranali3103** [comment]
You have to our own captcha keys, on your google account.

**Comment by Pranali3103** [comment]
image
It is working completely at my side

**Comment by Pranali3103** [comment]
Try it doing it with your own keys @thestarsahil

**Comment by thestarsahil** [comment]
Okay But by this update all over the application responsive part effecting !
See the changes after and before updating the captcha

**Pull request closed without merging**
