### PR TITLE
Enhanced Contact us page

### LINKED ISSUE #849: Want to enhance join us page and Fix COntact us page design
**Is your feature request related to a problem? Please describe.**
I want to Enhance the join us page by following ways : 
1. By doing proper formatting
2. by giving proper margin it is looking messy right now 
3. by adding some colors to the heading 
4. by adding navbar 
5. Creating the dark mode for the website 

Also want to fix design issue in contact page  the message title and button is overlapping with the input field
**Describe the solution you'd like**
I want to do all these things

https://github.com/Counselllor/Counsellor-Web/assets/118350936/2987a977-c488-4b0f-8fba-fbad813e1dfe

Screenshot 2024-07-03 213224

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have enanced the contact us page in following ways :

- Added a gradient button 
- Added dark mode for contact page 
- Added border
- fix the positioning issues with overlappign of message and textarea

## Fixes #849

SIr i created contact us page as you said and also i fixed the navbar links in this pr so if you find level 3 suitable for this please 

## Screenshots

https://github.com/Counselllor/Counsellor-Web/assets/118350936/2e0eaf41-913c-49a0-a82c-b814f56603dd

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Remove the bubble and remove the black border and outer blue border should be same in size

**Comment by Ayushmaanagarwal1211** [comment]
> Remove the bubble and remove the black border and outer blue border should be same in size

Ok

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i am little bit confused like which black border i have to remove 
image
This one or 


image
this one

**Comment by Ayushmaanagarwal1211** [comment]
and for outer blue border are you talking about this 
image

**Comment by thestarsahil** [comment]
I am talking about both 
Remove the black border and reduce the size of blue outer element in message box 
Inside the text element should should some gap

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Ok

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  
image
Like that

**Comment by thestarsahil** [comment]
original-bcb0bb2a26e1af8d4fac4fc7225a94d0

Not looking good Can you try to make this same as ?

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  yes sir sure I can make it but can you please merge this I will surely make new pr for that because you know I am working from 2 days and I had given most of my time I hope you understand sir I will create new form exactly same as you want till now please merge it

**Comment by thestarsahil** [comment]
How could i merge this ?
This changes are not even working

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir can you please check is the mail you received or not i fixed its working

**Comment by thestarsahil** [comment]
Due you fixed it ?

**Comment by Ayushmaanagarwal1211** [comment]
Yes sir i fixed this But please check once it is working in my laptop

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Yes sir i fixed that

**Pull request closed without merging**
