### PR TITLE
fixing broken link

### LINKED ISSUE #1086: [Bug] : Cource image link broken
**Describe the bug**

@thestarsahil 

check this out,
the link of image for cources are broken

**To Reproduce**
1. Go to '/cources'
2. See error

**Expected behavior**

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description
@thestarsahil 

[Bug] : Cource image link broken #1086

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #1086(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly please check this and merge it

**Comment by dhruv8433** [comment]
@thestarsahil

kindly please check this and merge it

**Comment by thestarsahil** [comment]
we don't any other addition , just fix the path 
images are already there in folder

**Comment by dhruv8433** [comment]
@thestarsahil 

update and use images from folder
image

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
