### PR TITLE
Added Google & GitHub Auth

### LINKED ISSUE #973: SignIn/SignUp using Google & Github
**Is your feature request related to a problem? Please describe.**
Currently, our website don't have Google & Github authentication option 

**Describe the solution you'd like**
I would like to add this for signing in and signing up

03_Google_GitHub_Login@2x-1536x804

### PR DESCRIPTION
**Pull request by Asymtode712**
# Description

- Added Google & GitHub Sign in buttons
- Added Google & GitHub authproviders
- Added a separator for separating both the buttons from login form
- Added hovering effect for both the buttons

## Screenshots

https://github.com/user-attachments/assets/401834b7-264a-4f0f-9c12-a3edd8c1dab0

## Checklist

- [X] Tests have been added or updated to cover the changes
- [X] Documentation has been updated to reflect the changes
- [X] Code follows the established coding style guidelines
- [X] All tests are passing

### CODE REVIEW

**Comment by Asymtode712** [comment]
@thestarsahil Everything's done....the only thing remaining from your part is to add Google & GitHub as providers in Firebase Console and the functionality would work fine!!!

**Comment by thestarsahil** [comment]
> @thestarsahil Everything's done....the only thing remaining from your part is to add Google & GitHub as providers in Firebase Console and the functionality would work fine!!!

Add  the functionality and the icon should not in circle form , make a square type

**Comment by thestarsahil** [comment]
@Asymtode712 Let's talk on VC around 8pm ?

**Comment by thestarsahil** [comment]
https://app.netlify.com/login

**Comment by Asymtode712** [comment]
Hey @thestarsahil , looks fine??


https://github.com/user-attachments/assets/811242ee-823b-4caf-a9fb-2e0b73f63cca

**Comment by Asymtode712** [comment]
Hey @thestarsahil , I have add the functionality so that whenever an user logins with Google/Github and if the user is not an existing one then the user's associated email, username and profile picture will be added in the Profile

**Comment by Asymtode712** [comment]
@thestarsahil Please review and merge this PR

**Comment by Asymtode712** [comment]
> Auth Funct. not working Error Showing

Can you please share a video demo for it

**Comment by thestarsahil** [comment]
[Screencast from 2024-07-17 20-52-59.webm](https://github.com/user-attachments/assets/58717805-f68d-4b6f-b590-c66127312da8)

**Comment by Asymtode712** [comment]
> Screencast.from.2024-07-17.20-52-59.webm

@thestarsahil It is working fine for me, please check the video below


https://github.com/user-attachments/assets/a57fa969-d208-4fb9-a714-3535511a0092

**Comment by thestarsahil** [comment]
npm run build error 
and path file is incorrect 

import googleIcon from "../../assets/googleIcon.png";
import githubIcon from "../../assets/githubIcon.png"; 

In assests : it is googleicon , githubicon

**Comment by Asymtode712** [comment]
@thestarsahil Renamed the files, can you please reinitiate the build

**Comment by Asymtode712** [comment]
@thestarsahil Renamed the files, can you please rerun the build

**Comment by thestarsahil** [comment]
Same error showing

**Comment by Asymtode712** [comment]
@thestarsahil ok wait let me close this PR and create a new one

**Pull request closed without merging**
