### PR TITLE
redesigned the joinus page

### LINKED ISSUE #1074: redesigning the Join-Us page
image

I want to add styling to this page

### PR DESCRIPTION
**Pull request by ayush-848**
# Description
Fixed the styling and layout of the whole page

## Screenshots
image
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil please check

**Comment by thestarsahil** [comment]
Work on same Color pattern of this website

**Comment by ayush-848** [comment]
> Work on same Color pattern of this website

Can you explain ???

**Comment by thestarsahil** [comment]
image

See the color in boxes , its not that color

**Comment by ayush-848** [comment]
> image
> 
> See the color in boxes , its not that color

Oh yes,
Should give them a bluish colour??

**Comment by thestarsahil** [comment]
@ayush-848 Yes

**Comment by ayush-848** [comment]
> @ayush-848 Yes

image
@thestarsahil now check

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-17 13-51-11

Fix this

**Comment by ayush-848** [comment]
> Screenshot from 2024-07-17 13-51-11
> 
> Fix this

I changed the file name which was 'Joinus.cc' to 'JoinUs.css'

**Comment by ayush-848** [comment]
@thestarsahil understood. The filename is not case-sensitive

**Comment by thestarsahil** [comment]
Due to this , 
1.login page effected 
2. Make a same navbar , don't implement extra changes 
3. Same font will gonna used

**Comment by ayush-848** [comment]
> Due to this , 1.login page effected 2. Make a same navbar , don't implement extra changes 3. Same font will gonna used

Ok

**Comment by ayush-848** [comment]
@thestarsahil you can check it now. I have reverted the file name

**Comment by ayush-848** [comment]
@thestarsahil please check it

**Pull request closed without merging**
