### PR TITLE
Dashboard cards layout

### PR DESCRIPTION
**Pull request by komal-agarwal5**
# Description

The cards in dashboard were not perfectly aligned.I have redesigned the alignment using flex of 3 in each row.design is also responsive. 

## Fixes #(issue_no)

#893 

## Screenshots

Large screen
image

Mobile
Screenshot 2024-07-07 002146

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
[Screencast from 2024-07-07 19-23-01.webm](https://github.com/Counselllor/Counsellor-Web/assets/84167034/d87e0519-d64f-44ed-81c1-8aeb01517148)
Increase the gap the card colliding with each other when hover effect activated

**Comment by thestarsahil** [comment]
Rest of thing is working fine

**Comment by komal-agarwal5** [comment]
> [Screencast from 2024-07-07 19-23-01.webm](https://github.com/Counselllor/Counsellor-Web/assets/84167034/d87e0519-d64f-44ed-81c1-8aeb01517148) Increase the gap the card colliding with each other when hover effect activated

Ok correcting it

**Comment by thestarsahil** [comment]
@komal-agarwal5 Done ?

**Comment by komal-agarwal5** [comment]
@thestarsahil done

https://github.com/Counselllor/Counsellor-Web/assets/122633300/0e095410-a32c-4852-b546-cdccff522f0a

**Review by thestarsahil — APPROVED** [review]

**Comment by thestarsahil** [comment]
Next Raise of PR 
Fixing college pages 

Screenshot from 2024-07-08 00-27-11

**Comment by komal-agarwal5** [comment]
> Next Raise PR Fixing college pages
> 
> Screenshot from 2024-07-08 00-27-11

Yes doing

**Pull request merged**
