### PR TITLE
Want to Write Backend of Social Profile #1012

### LINKED ISSUE #1012: Want to Write Backend of Social Profile
image
want to write backend of this where links will be stored in database of that particular user

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

Added Backend of Social Profile 

## Fixes #1012 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

https://github.com/user-attachments/assets/b4aa5e3f-d42f-4a33-adb8-da0bf3ca0e98

## Checklist

- [X ] Tests have been added or updated to cover the changes
- [X ] Documentation has been updated to reflect the changes
- [X ] Code follows the established coding style guidelines
- [X ] All tests are passing

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @thestarsahil please review it whenever possible

**Comment by thestarsahil** [comment]
Their should be a unique profile id which can easily traced 

like 
Profile -> 2131sa3d45fggHH -> Name , college , year , email , links etc etc

**Comment by nishant0708** [comment]
Hey @thestarsahil the profile is storing only social media links

**Comment by nishant0708** [comment]
> Their should be a unique profile id which can easily traced
> 
> like Profile -> 2131sa3d45fggHH -> Name , college , year , email , links etc etc

i guess you are kinda asking for different functionality @thestarsahil

**Comment by thestarsahil** [comment]
> > Their should be a unique profile id which can easily traced
> > like Profile -> 2131sa3d45fggHH -> Name , college , year , email , links etc etc
> 
> i guess you are kinda asking for different functionality @thestarsahil

I am trying to say make a normalization 
As working in database always make normalization by due to this we can set a primary attribute to trace the whole data from another database server 
Got my point ?

**Comment by nishant0708** [comment]
Yaa I am getting what you are asking but see whenever users login his data is getting stored in users where his name lastname these details are storing okay now if user is trying to add suppose his insta profile link so it will be stored in users only no.. if I create one more profile section what will happens to user? 


Like I got your point that you want me to trace profile I'd with user id and that profile I'd will contain user info 
So that user can have multiple profiles 


Or you want users->... details , social links:I'd

Social links->I'd ->instagram something like that?

**Comment by thestarsahil** [comment]
@nishant0708 Yes

**Comment by nishant0708** [comment]
Sir I have kinda written 2 things which one you want @thestarsahil

**Comment by thestarsahil** [comment]
want users->... details , social links:I'd

**Comment by nishant0708** [comment]
Yaa okay

**Comment by nishant0708** [comment]
hey @thestarsahil should be fine now please check it

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
