### PR TITLE
Signup login style fix

### LINKED ISSUE #223: Style Bug :Sign up button is not visible
**Describe the bug**
The signup button is not visible on some screens as shown in the screenshot section and also the screen cannot be scrolled to reach the button.

Because of this, the user is not able to create an account.

**To Reproduce**
Need to look into styles and change some style properties.

**Expected behavior**
The signup button must be visible for creating an account on all-size screens.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser: Chrome

**Request
Please assign me this issue under gssoc23 label.**

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
# Description
Fixed the style bug in the layout of the signup and login page which cause the content to hide by adding the scroll behavior.

## Fixes #223 
closes #223 **Style Bug: Sign up button is not visible**

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@thestarsahil created a new PR and made some changes . Please Review.

**Comment by AlfiyaSiddique** [comment]
@thestarsahil  please review this PR!!

**Comment by AlfiyaSiddique** [comment]
@thestarsahil please review this PR.

**Comment by AlfiyaSiddique** [comment]
@thestarsahil , did some changes and here's the result

**Deployed Site**


**My PR changes**


The width of input might be slightly different from the deployed one because I add the scrollbar that takes up some space.

Please provide your review

**Comment by thestarsahil** [comment]
Can we a meet right now !
I need to discuss more further

**Comment by AlfiyaSiddique** [comment]
> Can we schedule a meet ! I need to discuss more further

Okay @thestarsahil , Share the link and mention me I'll join

**Comment by AlfiyaSiddique** [comment]
@thestarsahil  what do you want to discuss about in meet?

**Comment by thestarsahil** [comment]
The Code you implemented is Affecting to other pages !

**Comment by AlfiyaSiddique** [comment]
> The Code you implemented is Affecting to other pages !

Okay, can we have google meet tomorrow at 5 pm?? Also, let me know which pages that are affected I'll look into it before hand.

**Comment by thestarsahil** [comment]
Ya sure !

**Comment by thestarsahil** [comment]
9pm ?

**Comment by thestarsahil** [comment]
https://meet.google.com/vmz-uwhp-vbh

Join the meeting

**Comment by thestarsahil** [comment]
Thanks for your lovely Contribution !

**Comment by AlfiyaSiddique** [comment]
> Thanks for your lovely Contribution!

My pleasure.
Also @thestarsahil can you please add gssoc23 label on this as I have contributed in this issue as a gssoc23 contributor

**Comment by AlfiyaSiddique** [comment]
And @thestarsahil  for the footer thing I will create an issue and also change the form side in that issue only.

**Pull request merged**
