### PR TITLE
Join us redesigned

### LINKED ISSUE #1138: Redesign Join Us Page
**Is your feature request related to a problem? Please describe.**
The join us page looks simple with only plain text i want to improve it using images hover effects and good styling

**Describe the solution you'd like**
Redesign UI of join us page to give good UI look

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by komal-agarwal5**
# Description

I have redesigned the join us page
- Added list styling component to display points with a better UI 
- Putted testimonials in card with image hover effect
- Improved overall alignment and colour scheme

## Screenshots

https://github.com/user-attachments/assets/d9c2457e-0705-4557-ad98-541f99a922a4

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Sonething more simple and premium look !

Reference :; https://www.apple.com/in/contact/

**Comment by komal-agarwal5** [comment]
> Sonething more simple and premium look !
> 
> Reference :; https://www.apple.com/in/contact/

Ok changing it accordingly

**Comment by komal-agarwal5** [comment]
https://github.com/user-attachments/assets/c17502a2-8d0e-4090-8678-b816dcb06c7e

@thestarsahil simplified UI

**Comment by thestarsahil** [comment]
The Text weight is too heavy to read and this is not responisve as for mobile devices

**Comment by komal-agarwal5** [comment]
> The Text weight is too heavy to read and this is not responisve as for mobile devices

Ok correcting it

**Comment by komal-agarwal5** [comment]
@thestarsahil done,check now

**Comment by thestarsahil** [comment]
Remove : BackToHomeButton  and fix the css for this 
Mobile reponsive is not good , work on css and same for footer section

div class whynew  -> inside the element are not properly aligned 
border should slightly curved 
Testimonials aslo not responsive

**Comment by komal-agarwal5** [comment]
https://github.com/user-attachments/assets/5794a23b-bd8b-4f41-98e1-348f85e30cd3

@thestarsahil check out this recording once pls
I have fixed all issues now

**Pull request merged**
