### PR TITLE
Career Support Pg fixed

### LINKED ISSUE #866: navbar and footer missing in this page
**Describe the bug**
navbar and footer missing in career support page,it is difficult for user to go back to home page or any other page.
Hence I want to add this.
**To Reproduce**
1. Go to website
2. Click on Career support

**Expected behavior**

**Screenshots**
Screenshot 2024-07-04 144352
Screenshot 2024-07-04 144402

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by komal-agarwal5**
# Description

I have added the footer which was missing in career support page.
I have added fragmentation and then added footer to ensure proper alignment

## Screenshots

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Review by thestarsahil — APPROVED** [review]

**Comment by thestarsahil** [comment]
@komal-agarwal5 Make a new PR for college page upgrdation , still need to work more

**Comment by komal-agarwal5** [comment]
> @komal-agarwal5 Make a new PR for college page upgrdation , still need to work more in css

Yes I will do it
Tell me what what changes you want I will make accordingly
@thestarsahil

**Comment by thestarsahil** [comment]
Let have a meeting on VC

**Comment by komal-agarwal5** [comment]
> Let have a meeting on VC

Okay

**Comment by thestarsahil** [comment]
Drop your discord id here

**Comment by komal-agarwal5** [comment]
> Drop your discord id here

komal#6579

**Pull request merged**
