### PR TITLE
Improved UI of signup and login page

### LINKED ISSUE #145: [FIX]: Update Signup Page
### Issue Description:
We need to update the signup page to improve user experience and increase conversion rates. This issue serves as a tracker for all the tasks related to the signup page update.

### PR DESCRIPTION
**Pull request by sumitkr2000**
# Description

Hey @omkarguravv I have improved the UI of the signup and login page. It's responsive also and looks the same as the mobile version you have provided in the readme. Please review my pr and merge it. Thank you!

## Screenshots

Screenshot (857)

Screenshot (858)

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Review by thestarsahil — COMMENTED** [review]
Changes : 
1. Don't have an account? [Sign up] include this in login page just below [ Login
[Forgot Your password? ]

2. The redirection from the main Counsellor page to the login page is based on the server's response to the initial request. After successful authentication, subsequent requests include an authentication token that allows the server to identify the user and provide the appropriate content, such as the user's homepage.
So include Main page and navigate (user) to login page , After that login page (redirect) to homepage 

3.  Navbar.jsx and home.jsx shouldn't be appear when user entry towards webapp that should appear after the login and signup 

4. Why haven't used lazy loader functionality ?

**Comment by sumitkr2000** [comment]
1st point ill do it.
2nd point I don't know the authentication part. 
3rd point is already done. 
4th point is why do we need lazy loading on login and signup pages???

**Comment by thestarsahil** [comment]
4th point : https://react.dev/reference/react/lazy#lazy
Go through this documentation Get to know ! 

Review this issue : https://github.com/Counselllor/Counsellor-Web/pull/150
You will get to know with lazy loading how Webapp work and without ?

**Comment by sumitkr2000** [comment]
> 4th point : https://react.dev/reference/react/lazy#lazy Go through this documentation Get to know !
> 
> Review this issue : #150 You will get to know with lazy loading how Webapp work and without ?

Yeah bro saw it. But this pr has not been merged yet.

**Comment by thestarsahil** [comment]
Did You changed the package lock json ?

**Comment by thestarsahil** [comment]
till now I am accepting this issue We have to work a lot in this area !

**Comment by sumitkr2000** [comment]
@thestarsahil meri tabiyat khrb hai 2 dino se sorry!

**Comment by sumitkr2000** [comment]
I can make the changes in another pr

**Comment by thestarsahil** [comment]
Sure No problem @sumitkr2000 
And make sure the next changes have to pass the netlify deploy
Check previous PR merges

**Comment by sumitkr2000** [comment]
@thestarsahil I have added point 1 in another pr. Please check that out.

**Comment by sumitkr2000** [comment]
@omkarguravv Bro you should have given level 3 tag to this pr. The issue also had level 3 tag in it and it really took me time to make the UI. Can you please add level 3 tag?

**Pull request merged**
