### PR TITLE
College Detailed page

### LINKED ISSUE #860: [Feat] : Redesign college detailed page
**Is your feature request related to a problem? Please describe.**

@thestarsahil 

we can redesign college deatiled page

image

something like this

image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

[Feat] : Redesign college detailed page #860

## Fixes #860(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil 

i fetched upstream and make fresh pr
kindly check this and merge it

**Comment by thestarsahil** [comment]
Same issue with job page

**Comment by dhruv8433** [comment]
@thestarsahil 

i resolve theme issue
please check this and merge it

image

**Comment by thestarsahil** [comment]
Still not working

**Comment by dhruv8433** [comment]
ok i reclone whole repo and make another pr

**Pull request closed without merging**
