### PR TITLE
Added 404 Error page 

### LINKED ISSUE #836: Want to add 404 error page not found
**Is your feature request related to a problem? Please describe.**
I want to add the 404 page not found on entering any url that is not in website 

**Describe the solution you'd like**
I want to show an individual page for this 

Screenshot 2024-07-03 005536

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have added a 404 Error page which will open when user go to any unwanted route then the user will see this page  instead of any error

@thestarsahil  I have implemented this day before yesterday but yesterday i got to know that i have to implement the design as in readme but i already created whole component by write whole jsx and css 
SO please merge it after that i will try to convert it into the design as in readme file 

## Screenshots

https://github.com/Counselllor/Counsellor-Web/assets/118350936/0eba7c32-d5d4-459d-b8e2-5d2760af52aa

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-06 17-46-52
[Screencast from 2024-07-06 17-47-36.webm](https://github.com/Counselllor/Counsellor-Web/assets/84167034/d0f4a826-3a89-4f8a-bb33-0bc1c82f01bc)

In video clip , when error page occur why to direct dashboard page until login
If user went to error page direct to login page not dashboard page 
work on that

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  i directed the user to login please check

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  ok doing

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Please check i changed it and i changes the class name it must not conflict with other css but if you find any please send ss i will fix that

**Comment by thestarsahil** [comment]
Its not working as expected you can work on another , the simple error page is fine enough !

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  sir i did like when user logged in then it will redirecting to dashboard and when not logged in it will redirecting to login page But if you want any other change please let me know i will do that .

**Comment by thestarsahil** [comment]
Okay do one thing make new PR 
when user logged in then it will redirectto dashboard and when not logged in it will redirect to login page 
No need to make new error page 
old one is working fine

**Comment by Ayushmaanagarwal1211** [comment]
> Okay do one thing make new PR when user logged in then it will redirectto dashboard and when not logged in it will redirect to login page No need to make new error page old one is working fine

Okay sir i am doing

**Pull request closed without merging**
