### PR TITLE
[Feature] : Resposive Nav Bar

### LINKED ISSUE #838: [Feature] : Resposive `Nav Bar`
Hello @thestarsahil ,

- In this project mobile site cannot proper Responsive `nav bar`.
- please see the below video.

### Error  Video

[Screencast from 2024-07-03 07-10-06.webm](https://github.com/Counselllor/Counsellor-Web/assets/121082414/52ff7380-debf-4c7d-a196-de4e87d54b02)

### Expected working Video

[Screencast from 2024-07-03 07-15-46.webm](https://github.com/Counselllor/Counsellor-Web/assets/121082414/5e472eb3-5f34-4841-a49b-435345a4946b)

### PR DESCRIPTION
**Pull request by sivaprasath2004**
# Description

[Feature] : Resposive Nav Bar

### Before

[Screencast from 2024-07-03 07-10-06.webm](https://github.com/Counselllor/Counsellor-Web/assets/121082414/52ff7380-debf-4c7d-a196-de4e87d54b02)

### After

[Screencast from 2024-07-03 20-36-32.webm](https://github.com/Counselllor/Counsellor-Web/assets/121082414/da63a66e-68a6-4c6e-b74e-38fbe461664e)

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
where is the university section ?

**Comment by sivaprasath2004** [comment]
Hello @thestarsahil , I will finished it..

Screenshot from 2024-07-05 06-53-27

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-05 17-09-30

The Hamburger should not move from its place Fix this

**Comment by thestarsahil** [comment]
@sivaprasath2004 Fix this

**Comment by sivaprasath2004** [comment]
@thestarsahil sure

**Comment by sivaprasath2004** [comment]
[Screencast from 2024-07-06 17-47-39.webm](https://github.com/Counselllor/Counsellor-Web/assets/121082414/5d5d8612-90d4-4bd0-b3b1-126b5ca1ff16)

**Comment by thestarsahil** [comment]
> @thestarsahil i will fixed it..

If you already been fixed then say I had fixed it kindly checked it !
Good job

**Review by thestarsahil — APPROVED** [review]
Working good

**Pull request merged**
