### PR TITLE
Help page Updated Successfully

### LINKED ISSUE #925: Help Page integration
**Is your feature request related to a problem? Please describe.**
If anyone wanted help it will shown
**Describe the solution you'd like**
If anyone wanted help it will shown

**Describe alternatives you've considered**
If anyone wanted help it will shown

**Additional context**
image

### PR DESCRIPTION
**Pull request by Damini2004**
# Description

Help page Updated Successfully

## Fixes  #925 

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Don't use gif animation 

You can try to copy from career page

**Comment by Damini2004** [comment]
@thestarsahil yup i use those and add some more too. Kindly Review the PR.

**Review by thestarsahil — APPROVED** [review]

**Comment by Damini2004** [comment]
@thestarsahil  Kindly add the gssoc label too. The points has not been added.

**Comment by Damini2004** [comment]
@thestarsahil  Kindly add the gssoc label too. The points has not been added.

**Pull request merged**
