### PR TITLE
Inline Validation in  SignUp/Login

### LINKED ISSUE #222: Inline Validation in Login And signup
**Is your feature request related to a problem? Please describe.**
yes, There is no validation system in the login and signup form, which can lead to the submission of invalid data.

**Describe the solution you'd like**
I want to implement inline validation for each field in the login and signup form. Also, there are no constraints for fields in the frontend, I want to implement the following constraints :
Name: Min 6 characters
Email: Valid Regex
Password: Min 8 characters with at least 1 uppercase, 1 lowercase,1 symbol, and 1 digit. 

**Sample Video**
I want to implement functionality similar to the below video:

https://github.com/agamjotsingh18/pollitup/assets/86224794/b3d8c27f-da3b-4b82-9ea2-e4db3c710923

**Request**
Please assign me this issue under gssoc23 label.

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
# Description
Added inline validation in login and signup form

## Fixes #222
**Inline Validation in Login And signup**

## Sample Output 

https://github.com/Counselllor/Counsellor-Web/assets/86224794/c1ebdbba-b653-4764-9ea3-24026c591063

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
While implementing inline authentication part is not working Check out this issue !

**Comment by AlfiyaSiddique** [comment]
> While implementing inline authentication part is not working Check out this issue !

@thestarsahil which issue ??

**Comment by thestarsahil** [comment]
> > While implementing inline authentication part is not working Check out this issue !
> 
> @thestarsahil which issue ??

When We click to signup its redirect to dashboard page 
but after implementing inline validation and checking your deploy PR  it does'nt even signup 
Check whole the signup page till you redirect to dashboard page

**Comment by AlfiyaSiddique** [comment]
> When We click to signup its redirect to dashboard page but after implementing inline validation and checking your deploy PR it does'nt even signup Check whole the signup page till you redirect to dashboard page

Okay understood, will look into this issue soon.

**Comment by AlfiyaSiddique** [comment]
@thestarsahil I have made the changes to fix the issue , can you please review now

**Comment by thestarsahil** [comment]
Okay !
Now Explain the Codebase How you implemented 
Will it be fine to take on meet ?

**Comment by AlfiyaSiddique** [comment]
> Okay ! Now Explain the Codebase How you implemented Will it be fine to take on meet ?

Yes fine, but is it working properly on the deployment preview??

**Comment by AlfiyaSiddique** [comment]
Share the link

**Comment by thestarsahil** [comment]
https://meet.google.com/ghi-pbti-qeb

**Comment by AlfiyaSiddique** [comment]
Hey @thestarsahil, again a friendly reminder to add gssoc23 labels on this PR. 😂

**Pull request merged**
