### PR TITLE
Added Feature Details of Contributor 

### LINKED ISSUE #1062: Feature Details of Contributors
Fix the gap bw navabar and college section(2)

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have added a feature details of the contributor 
I am fetching the official github api for each user 
@thestarsahil  Sir i added all main  details of the contributor  provided by github Other details github will not provide like social like through api

## Fixes #1062 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

https://github.com/user-attachments/assets/a20fa81b-2e9a-4159-bc2d-713f58f1cee3

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
This is not working , do mannually 
Visit their linkdein Profile and exctract data to show 
as datatype should same in any how

**Comment by thestarsahil** [comment]
@Ayushmaanagarwal1211 This is  not working 
What i said you have to implement that

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i am doing but i didn't find details of many contributor on their linkedin

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Many of them didn't entered their linkedin profile link on their github and those who entered i am not getting their social links and other details

**Comment by thestarsahil** [comment]
Just mentioned College Name

**Comment by thestarsahil** [comment]
The information you got feed , rest of the information left it

**Comment by Ayushmaanagarwal1211** [comment]
> The information you got feed , rest of the information left it

Ok sir so i will raise pr for this today

**Pull request closed without merging**
