### PR TITLE
Want to Improve Performance by Using Common Navbar #1136

### LINKED ISSUE #1136: Want to Improve Performance by Using Common Navbar
Currently various files have their own Nav  tag for Navbar but we should use Common Navbar Component .which we be easier for us to handle and modify NavBar Component

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

Used Common Navbar Component for all the pages

## Fixes #1136 

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [X ] Tests have been added or updated to cover the changes
- [ X] Documentation has been updated to reflect the changes
- [X ] Code follows the established coding style guidelines
- [X ] All tests are passing

### CODE REVIEW

**Comment by nishant0708** [comment]
Hey @thestarsahil  please review this whenever possible

**Comment by thestarsahil** [comment]
All the footer links broken when user not logged in
Also fix this

**Comment by nishant0708** [comment]
hey @thestarsahil  its should work fine now. hey @thestarsahil its a small request can you assign it **level 3** because it was a big task and i have fixed additional bugs as well like when user was signing up he was getting navigate to home page but in local storage his login was not set to true .

**Comment by thestarsahil** [comment]
resolve conflict and pull the latest changes and push again

**Comment by nishant0708** [comment]
Yaa sir  @thestarsahil done

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
