### PR TITLE
Enhancement-centered-the-text

### LINKED ISSUE #612: The text in the college page is to be centered .
**Is your feature request related to a problem? Please describe.**
If the text in the responsive screen like mobile is aligned at the  centered then it may increase the UI/UX of the user .

Before : -
Screenshot 2024-05-26 003952

After This feature :- 
Screenshot 2024-05-26 004225

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have changed some css for making the all text for small screen sizes to the center .

## Screenshots

Screenshot 2024-05-27 195746

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Changes , Not statisfied 
image

We want this change , Kindly Work on that

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil sir from where i can get these images .
Screenshot 2024-05-29 104320

**Comment by thestarsahil** [comment]
> @thestarsahil sir from where i can get these images . Screenshot 2024-05-29 104320

/src/assets/10.png
You can find more avatar like this , its already in assets folder

**Comment by Ayushmaanagarwal1211** [comment]
ok sir

**Comment by Ayushmaanagarwal1211** [comment]
Screenshot 2024-05-29 181113
Sir is this alright

**Comment by thestarsahil** [comment]
@Ayushmaanagarwal1211 We will discuss this in discord VC at 10pm

**Comment by Ayushmaanagarwal1211** [comment]
I did some changes please check 

https://github.com/Counselllor/Counsellor-Web/assets/118350936/bc227362-8d33-498a-b31c-9c9eee8e6e0d

**Comment by thestarsahil** [comment]
Screenshot from 2024-05-30 09-00-19

Responsive part not done yet !

**Comment by Ayushmaanagarwal1211** [comment]
Ok will do

**Comment by Ayushmaanagarwal1211** [comment]
Done 

https://github.com/Counselllor/Counsellor-Web/assets/118350936/9d7ff67b-ab7d-4847-8573-6d39a50cbbf2

**Comment by thestarsahil** [comment]
@Ayushmaanagarwal1211 reduce the font size and change the font style to ABeeZee

**Comment by Ayushmaanagarwal1211** [comment]
Screenshot 2024-05-30 203756
Can you check it again

**Comment by thestarsahil** [comment]
Right Now , I'm merging 
Raise Another PR to Fix this CSS property again !
Well done @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
Ok and as i see on discord that PR's is not counted for leaderboard i think this is due to not added GSSOC and level label on PR's merged so please add level . And if you think that this PR is capable of getting level 3 so please add it .

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  please put gssoc and level label

**Pull request merged**
