### PR TITLE
Enhanced the privacy policy page

### LINKED ISSUE #1101: Redesigning the Terms and Conditions page
This page is too basic and does not follow the theme of the other pages

### PR DESCRIPTION
**Pull request by ayush-848**
# Description

Enhanced the privacy policy page

## Screenshots

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil please merge this one if works. So that I can fix the Join us

**Comment by thestarsahil** [comment]
You should work on css part , even how it look good ?
Text font and styling ok

Take a reference : https://privacycenter.instagram.com/policy/?entry_point=ig_help_center_data_policy_redirect

**Comment by ayush-848** [comment]
image
@thestarsahil please this is the best I could have done, I hope you will like it

**Comment by thestarsahil** [comment]
Fix the gap bw navabar and college section(5)

Fix this all

**Comment by ayush-848** [comment]
> Pull the lastest changes and push again

I have pulled all the latest changes and I will work on your instructions

**Comment by ayush-848** [comment]
image
image
@thestarsahil now see

**Comment by ayush-848** [comment]
@thestarsahil please check it now

**Comment by thestarsahil** [comment]
Changes effected to login page

**Comment by ayush-848** [comment]
> Changes effected to login page

Ok let me create a fresh PR

**Pull request closed without merging**
