### PR TITLE
Issue#896 fixed. Modified the UI of the contact page.

### LINKED ISSUE #896: Improve the UI of the contact us page
**Is your feature request related to a problem? Please describe.**
The send button and the message text gets overlapped as in the below ss. I want to improve this. 

Screenshot 2024-07-06 203515

I can design a contact page like this sample one I did before. 
Screenshot 2024-03-30 121955

**Describe the solution you'd like**
I want to provide a better design of the contact page. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ParnaRoyChowdhury777**
# Description

I have changed the UI of the contact page.

## Screenshots

Screenshot 2024-07-09 191357

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
image

Try to make this contact page

**Comment by thestarsahil** [comment]
@ParnaRoyChowdhury777 Did you made it ?

**Comment by ParnaRoyChowdhury777** [comment]
> @ParnaRoyChowdhury777 Did you made it ?

I will send the PR within tomorrow

**Comment by thestarsahil** [comment]
@ParnaRoyChowdhury777 Updates ?

**Comment by ParnaRoyChowdhury777** [comment]
> @ParnaRoyChowdhury777 Updates ?

My laptop has crashed. If u can, then give me time upto Thursday night, I will give u the PR.

**Comment by thestarsahil** [comment]
@ParnaRoyChowdhury777 Dear it build now , you can look onto for further changes

**Pull request closed without merging**
