### PR TITLE
Added Icons

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Added Icons to Navbar and Footer - Solved #704
Kindly Please go through it @thestarsahil

bn

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
@thestarsahil Kindly Please go through this PR

**Comment by thestarsahil** [comment]
Update the latest changes , then push again !

**Comment by sailaja-adapa** [comment]
Yeah okkk @thestarsahil

**Comment by thestarsahil** [comment]
Still Conflict ,first pull the latest changes and then push your changes

**Comment by sailaja-adapa** [comment]
Yeah okkk @thestarsahil

**Comment by sailaja-adapa** [comment]
@thestarsahil is it okay now?

**Comment by thestarsahil** [comment]
import FAQS from "../FAQs/FAQs";
@sailaja-adapa 
Modify this !

**Comment by sailaja-adapa** [comment]
> import FAQS from "../FAQs/FAQs"; @sailaja-adapa Modify this !

You mean should I remove that ? Or what @thestarsahil

**Comment by thestarsahil** [comment]
Screenshot from 2024-06-22 17-10-45
This is what i am trying to say !

**Comment by sailaja-adapa** [comment]
Yeah okk understood @thestarsahil

**Comment by sailaja-adapa** [comment]
I will update you soon

**Pull request closed without merging**
