### PR TITLE
radio button fixed

### LINKED ISSUE #240: Simultaneous Selection of Student and Counselor
**Describe the bug**

The student and counselor roles were both selected simultaneously and cannot be deselected.

**To Reproduce**

**Expected behavior**
only one should be selected at a time

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by RitiChandak**
# Description

the radio button is fixed and now only one option is selected at a time

## Fixes #240 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

https://github.com/Counselllor/Counsellor-Web/assets/96969496/00cf7e5e-bf6e-4df6-bb19-a6e98f31a0d8

## Checklist

- [✅ ] Tests have been added or updated to cover the changes
- [✅ ] Documentation has been updated to reflect the changes
- [✅ ] Code follows the established coding style guidelines
- [✅ ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
After checking all the code base 

No problems have been found till now. So, successfully merging this issue

**Comment by RitiChandak** [comment]
Thank you @thestarsahil

**Comment by thestarsahil** [comment]
Make sure join on discord channel for more details and community

**Comment by RitiChandak** [comment]
sure @thestarsahil

**Pull request merged**
