### PR TITLE
[Feature]: contact us mail Announce Isn't work

### LINKED ISSUE #938: [Feature]:  contact us `mail` Announce Isn't work
- Hello @thestarsahil ,
- I will trying to contactus mail to announce will be work to check but that cannot work.
- I will waiting for  3 or 4 min but this not responding .
- there is something miss.
- please assign me..

### Proof

[Screencast from 2024-07-08 08-37-38.webm](https://github.com/Counselllor/Counsellor-Web/assets/121082414/72a88d91-7c8f-48f0-a703-b72df28cdef1)

### Expected
- In my portfolio How it will be work within sended faster ..

[Screencast from 2024-07-08 08-43-36.webm](https://github.com/Counselllor/Counsellor-Web/assets/121082414/411b9835-a7fd-412a-bae9-c3c6ced4d1e5)

### PR DESCRIPTION
**Pull request by sivaprasath2004**
# Description

Hello @thestarsahil ,
If you i will add the backend same project please add the `.env` in the `/backend` folder .
- please add this and deploy 

```
SERVICE=gmail
HOST=smtp.gmail.com
PORT=587
USER_MAIL_ADDRESSS='Your Mail Address'
PASS=Your Password 

```

### How to create App Password
[How to create Password](https://www.hostpapa.com/knowledgebase/how-to-create-and-use-google-app-passwords/)

## Fixes #(issue_no)

closes #938 

## Screenshots

[Screencast from 2024-07-09 08-36-14.webm](https://github.com/Counselllor/Counsellor-Web/assets/121082414/c7882fb1-7d45-427c-9f36-91b3e3278fab)

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by sivaprasath2004** [comment]
@thestarsahil ,
change this line into the  `src/components/Contact.jsx` file  `34`  th line   `const url = 'CHANGE BACKEND URL /contactUs';`

make deploy on backend then backend url to give the frontend `Contact.jsx` file and add the  Enviornment in the vercel .env.example format make sure is it work ...

**Comment by sivaprasath2004** [comment]
If you anything doubt please feel free to ask...

**Comment by thestarsahil** [comment]
As preivous we are working with emaijs , is it not working properly ?

**Comment by sivaprasath2004** [comment]
@thestarsahil please deploy the back-end and enter back-end url on the Contact.jsx 34 th line  change I hope this is work . In my portfolio back-end asities same code that currently working please make the changes this is will be proper work if you can any doubt please ask...

**Comment by thestarsahil** [comment]
Let have a meet on Discord to discuss this @sivaprasath2004

**Comment by sivaprasath2004** [comment]
@thestarsahil `https://discord.com/channels/1099745007172329592` not working give as a discord link

**Comment by thestarsahil** [comment]
@sivaprasath2004 check your discord i mssged you on gsssoc channel

**Comment by thestarsahil** [comment]
Resolve the conflict now

**Comment by sivaprasath2004** [comment]
@thestarsahil please merge..

**Comment by thestarsahil** [comment]
I having doubt , Does i have modify from my side also ?

**Comment by sivaprasath2004** [comment]
@thestarsahil  Yes ,

**Comment by sivaprasath2004** [comment]
please give me a Discord link we will discuss about this.

**Comment by thestarsahil** [comment]
thestarsahil

**Comment by sivaprasath2004** [comment]
@thestarsahil please merge this..

**Comment by sivaprasath2004** [comment]
I'll send the friend request please accept..

**Comment by sivaprasath2004** [comment]
I'll send the friend request please accept..

**Comment by sivaprasath2004** [comment]
I'll send the friend request please accept..

**Comment by thestarsahil** [comment]
@sivaprasath2004 Can you update the PR I am trying to merging this

**Comment by sivaprasath2004** [comment]
@thestarsahil please merge this.. 

If there any doubt please message on discord

**Comment by sivaprasath2004** [comment]
@thestarsahil please merge this...

**Comment by nishant0708** [comment]
hey @sivaprasath2004 you know right its firebase project and you have created whole backend for this one simple task

**Comment by nishant0708** [comment]
> hey @sivaprasath2004 you know right its firebase project and you have created whole backend for this one simple task
hey @sivaprasath2004  can you make it work using Firebase services or email js your choice see forgot password functionality for reference

**Comment by nishant0708** [comment]
const handleSubmit = (e) => {
    e.preventDefault();
    let params = {
      name: form.current.firstname.value +" " +form.current.lastname.value,
      email: form.current.email.value,
      feedback: form.current.feedback.value,
      created_date: new Date().toISOString() // Adding created_date
    };
    
    emailjs.send('service_kszura2', "template_u8shl9d", params, {
      publicKey: "rSYpY_RsF76o4MgcA",
    }).then(() => {
      // Send acknowledgment email
      emailjs.send('service_kszura2', "template_acknowledgment", {
        user_email: form.current.email.value,
        user_name: form.current.firstname.value
      }, {
        publicKey: "rSYpY_RsF76o4MgcA",
      });
    });

    // Store form data in Firebase Realtime Database
    const db=getDatabase();
    const queriesRef = ref(db, 'queries');
    const newQueryRef = push(queriesRef);
    set(newQueryRef, params)
      .then(() => {
        setIsModalOpen(true); // Open modal on successful submission
        form.current.reset();
      })
      .catch((error) => {
        console.error('Error submitting query: ', error);
      });
  };
  
  
  Create One Template in Email js and use this function and remove that whole backend

**Comment by sivaprasath2004** [comment]
@nishant0708 yes,But we will  our `own backend` customize the mail . If you tell about this simple task , but use in our own backend more safty and It can notice our `gamil` Invalid mail address  and more..

**Comment by nishant0708** [comment]
> @nishant0708 yes,But we will our `own backend` customize the mail . If you tell about this simple task , but use in our own backend more safty and It can notice our `gamil` Invalid mail address and more..
> 
> use `smtp` backend customize to mail using HTML ,CSS .

Yaa I know that but @sivaprasath2004 but your code is making website heavier.and he needs to create one backend server for production as well right

**Comment by sivaprasath2004** [comment]
sure, Is possible...

**Comment by nishant0708** [comment]
So please do that @sivaprasath2004

**Comment by sivaprasath2004** [comment]
> > @nishant0708 yes,But we will our `own backend` customize the mail . If you tell about this simple task , but use in our own backend more safty and It can notice our `gamil` Invalid mail address and more..
> > use `smtp` backend customize to mail using HTML ,CSS .
> 
> Yaa I know that but @sivaprasath2004 but your code is making website heavier.and he needs to create one backend server for production as well right . So can you do it without any backend server?

If you work on simplest method , but we will trying to our best and  more important `UI`. so we will more imporve the project  `user attraction`.

**Comment by sivaprasath2004** [comment]
@nishant0708  I'll try to avoid backend use , but this is not possible.

**Pull request closed without merging**
