### PR TITLE
Implemented authorization using firebase

### LINKED ISSUE #229: Add firebase authentication to the project
**Is your feature request related to a problem? Please describe.**

Hey @thestarsahil  I want to add Firebase authentication to the login and signup page. Please assign me this issue. Thank you!

**Describe the solution you'd like**

Use firebase to login and signup the user.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by sumitkr2000**
# Description

Hey @thestarsahil I have successfully implemented authorization using firebase. When a user is not logged in then he automatically gets redirected to the login page. But when he is logged in he is redirected to the home page. It took a lot of effort to implement firebase so please consider it a level 3. Thank you!

## Screenshots

[screen-capture.webm](https://github.com/Counselllor/Counsellor-Web/assets/100675296/ba81313b-6cfe-4763-b43f-154f8fcfd64b)

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Actaully , After the login credential user have to direct into dasboarad page #193 
Have a check !

**Comment by sumitkr2000** [comment]
@thestarsahil First merge that pr then i will be able to make the changes.

**Comment by thestarsahil** [comment]
Thank you for working on the auth feature. I understand that it was discarded due to conflict auth.

I'm writing to ask if you would be able to work on auth advanced security. This is a set of features that can help to protect user accounts from being compromised.
Please let me know if you are interested in working on this project. I look forward to hearing from you.

**Comment by sumitkr2000** [comment]
@thestarsahil I would be happy to work on this issue. Can you elaborate the feature, please?

**Comment by sumitkr2000** [comment]
Please merge the auth first otherwise I would have to resolve the conflicts again and again. The advanced features can be implemented later.

**Comment by thestarsahil** [comment]
@sumitkr2000 Dear as previous i said this feature is no longer 
Signup with Google , So you hav to work on auth advanced security . Providing Security codebase with attacker can get the credential data

**Comment by sumitkr2000** [comment]
@thestarsahil Don't assign the same issue to different people. I wasted time implementing authentication using email and Google also. But you merged pr of someone else. Please respect others' time.

**Pull request closed without merging**
