### PR TITLE
Blog Should be Fetched even if User is not Logged in +if he tries to login then he should get toast that please login first (same for comment) #1180

### LINKED ISSUE #1180: Blog Should be Fetched even if User is not Logged in +if he tries to login then he should get toast that please login first (same for comment)
image

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

For make This Work Please Update Firebase Rules i have Updated Documentation As well

## Fixes #1180 

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [ X] Tests have been added or updated to cover the changes
- [X ] Documentation has been updated to reflect the changes
- [X ] Code follows the established coding style guidelines
- [X ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-23 20-03-50

Main server live :
Showing nothing , if user not login in

**Comment by nishant0708** [comment]
Hey @thestarsahil can we do this in vc?

**Comment by nishant0708** [comment]
> Hey @thestarsahil can we do this in vc?

Have you updated database rules?

**Comment by thestarsahil** [comment]
No tell me how to do this ?

**Comment by nishant0708** [comment]
Hey @thestarsahil can you come in vc?

**Comment by thestarsahil** [comment]
Sure

**Pull request merged**
