### PR TITLE
Fixed the Overflowing of the text from the blog page 

### LINKED ISSUE #1167: Want to fix the overflowin the content from the blogs card
**Describe the bug**
I want to fix the bug where the for large content it is overflowing from the blogs card 

**To Reproduce**
1. Go to Blogs page 
2. Create any blog with long title and description
3. See error

**Expected behavior**
I must clip after some charachters 

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have fixed the overflowing of the text 
I have added the elipsis at the end of the text 
The text is also overflowin the the reading page 
But when i will enhance the blog reading page under #1120  Then i will make this according to handle this case as well

## Screenshots

image

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-21 20-57-01
Set a word limit  on title and tag

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i have added the limit like no user can able to enter more than 80 words title and 8 length of tag

**Comment by thestarsahil** [comment]
Include a notification , that word limit is exceed so that user get to know and after submittting also implement a notification that sucessfully blog created

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Done sir i have added the toast 

https://github.com/user-attachments/assets/304d0c3b-2131-40bc-a7ec-c83a2403cea6

**Comment by thestarsahil** [comment]
You can do i thing , in title section you can stop the word at a certain word limit 
For example
  if ( count i=0 : <=80 ; count++ )   
  then stop ;
  
  work on this

**Comment by thestarsahil** [comment]
and first pull the latest changes

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Done 

https://github.com/user-attachments/assets/e61d736a-89a0-415e-9432-8dcb22aa69fe

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
