### PR TITLE
Footer Enhancement Added

### LINKED ISSUE #740: Hover Effect advancement In FAQ and Footer section
**Is your feature request related to a problem? Please describe.**
Advancement 
**Describe the solution you'd like**
User engagement 
**Describe alternatives you've considered**

**Additional context**
image
Screenshot 2024-06-22 185952

### PR DESCRIPTION
**Pull request by Damini2004**
# Description

- Added Typewriter Effect ON FAQ statement.
- Hover effect to the social icon.
- Text visibility enhancement.

## Fixes #740 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image
Screenshot 2024-06-25 130225
Screenshot 2024-06-25 130237

https://github.com/Counselllor/Counsellor-Web/assets/119414762/0b75025f-6b38-4d84-8cef-d2cc54114862

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by Damini2004** [comment]
@thestarsahil Kindly gothrough it

**Comment by thestarsahil** [comment]
@Damini2004 You added too much we just want simple as much as possible

**Comment by Damini2004** [comment]
@thestarsahil tell me the changes what should I eliminate in the above following code.

**Comment by thestarsahil** [comment]
Just visible the social icons that's it !

**Comment by Damini2004** [comment]
Ohk the typewriter effect ?
And the hover?

**Comment by Damini2004** [comment]
@thestarsahil Review it

**Comment by thestarsahil** [comment]
@Damini2004 You can work on different problem its been solved already !

**Comment by Damini2004** [comment]
Sure

**Pull request closed without merging**
