### PR TITLE
Added Text editor for the create and read blog page 

### LINKED ISSUE #1193: Want to Add the text editor for formatting the text in create blog
**Is your feature request related to a problem? Please describe.**
I want to add the text editor in the create blog page where user can do formatting on the text and fill see the formatted text 

image

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have added the text editor for the create blog page with this we can edit the text like bold the text italic the text like we can do text formatting 
I also redendered this text to everywhere 

## Screenshots

https://github.com/user-attachments/assets/62aeb193-c2f7-4bdb-b217-53e01ef87be0

sir please mark lvl 3 if suitable because for that i have to use other library and it is very complex to use 
## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
1.Screenshot from 2024-07-24 21-29-28
2.Screenshot from 2024-07-24 21-33-19
3.Screenshot from 2024-07-24 21-33-29
4.Screenshot from 2024-07-24 21-33-34
5.Screenshot from 2024-07-24 21-33-38

Do this

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir actually this is impossible to do this alone because they user their own text editor and wrote the different html css for each command but i can edit this like that  
Can i please do like that 

https://github.com/user-attachments/assets/2051f620-18e7-4d1e-b526-8b532788bfd2

**Comment by thestarsahil** [comment]
Content isn't stroring in database !

**Comment by Ayushmaanagarwal1211** [comment]
> Content isn't stroring in database !

Sir it is storing like in the video i uploaded when i am doing the content bold then it will be shown as bold in the card as well as the read blog page

**Comment by thestarsahil** [comment]
Showing a thing is different , the data has to be stored inside the database not jsut to reflect into display

**Comment by Ayushmaanagarwal1211** [comment]
> Showing a thing is different , the data has to be stored inside the database not jsut to reflect into display

Yes sir i am storing it to database

**Comment by Ayushmaanagarwal1211** [comment]
> > Showing a thing is different , the data has to be stored inside the database not jsut to reflect into display
> 
> Yes sir i am storing it to database

Like it will be only shown the text if it is stored in the database so i am storing that html to show the content if it will not stored in the database then it won't render the title and the description

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i am storing all the data in the database

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir please see this

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil Sir why are you not seeing this please have a look

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil sir do you want to review that

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i am storing all the data to the database as if i didn't store then it is impossible to render the same data as database in the blogs page

**Comment by thestarsahil** [comment]
I am checking it , why your changes not storing to database

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil sir can you please check once like it is storing the data like that  <p>Hlo</p> in the html form 
And sir please also send one sc of the data of firebase so that i can understand the bug i raied a new blog with title text editor please send sc of that data

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-30 17-13-03

Title are in HTML displayed

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil YEs sir i can fix that i did that to show you wait a second i am fixing that

**Comment by Ayushmaanagarwal1211** [comment]
image

@thestarsahil  Sir i fixed that

**Comment by thestarsahil** [comment]
Fix the gap bw navabar and college section(12)

Check out the hasnode website visit the blog area section then compare what you made

**Pull request closed without merging**
