### PR TITLE
Fix/improper linkage fixed

### LINKED ISSUE #1146: improper linking from some pages
**Describe the bug**
from top university and support career page, the dashboard page is not accessible on clicking upon the logo on top left corner

**To Reproduce**
1. Go to 'https://counsellor.social/dashboard'
2. Click on 'top university / career support'
3. click on the logo on top left corner

**Expected behavior**
the logo should navigate to the dashboard page 

**Screenshots**

https://github.com/user-attachments/assets/a50c4992-41bf-468d-97df-7c34cbbe40db

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
i am a gssoc'24 contributor please assign this to me

### PR DESCRIPTION
**Pull request by anwesha2002**
# Description

This PR fixes some improper linkage

## Fixes #1146

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [x ] Tests have been added or updated to cover the changes
- [x ] Documentation has been updated to reflect the changes
- [ x] Code follows the established coding style guidelines
- [ x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
You didn't work on auth.js part then why you modified just implementing space ?

**Comment by anwesha2002** [comment]
> You didn't work on auth.js part then why you modified just implementing space ?

@thestarsahil 
It was not for adding space, 
I needed to write my firebase config of my own firebase app in order to authenticate into that website as I dont have the access to your firebase web app for this project . 
At last I removed my config and left with the original config, in that process 2 extra spaces remained there.

**Comment by anwesha2002** [comment]
> > You didn't work on auth.js part then why you modified just implementing space ?
> 
> @thestarsahil It was not for adding space, I needed to write my firebase config of my own firebase app in order to authenticate into that website as I dont have the access to your firebase web app for this project . At last I removed my config and left with the original config, in that process 2 extra spaces remained there.

And same reason goes with my other PRs as well

**Comment by anwesha2002** [comment]
@thestarsahil please merge it now otherwise someone else fixing the same issue and getting merged

**Pull request closed without merging**
