### PR TITLE
added jobs page with fetched upstreaam

### LINKED ISSUE #889: [Feat] : Missing Jobs page
**Is your feature request related to a problem? Please describe.**

@thestarsahil 

check this out,
there are missing `/jobs` page

image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

[Feat] : Missing Jobs page #889

close #889

## Fixes #889(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

- added new route `/jobs`
- list available jobs
- make it repsonsive

## Screenshots

image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly check this and inform me if you need any modifications

**Comment by dhruv8433** [comment]
@thestarsahil 

please review it and merge it so i can make another pr

**Comment by thestarsahil** [comment]
Navbar Links are not clickable and i want same structure as same as contact us page 
!
https://counsellor.social/careersupport

**Comment by dhruv8433** [comment]
@thestarsahil 

check this out ,
as you said i update and make it same as careersupport page

image

image

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly please check this and merge it

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
