### PR TITLE
Enhanced the Contributors page 

### LINKED ISSUE #806: Enhancing the  Contributors Page  And implementing dark mode for that
**Is your feature request related to a problem? Please describe.**
I will enhance it by adding following things : -

1. Will add fade up animation when user scrolls down then the card will be shown with an animation 
2. Implementing Dark mode for that 
3. Will add number of contributions did by different contributors 
4. Will Filter Category wise like top contributors then i will show top 3 contributors and then all contibutors .
5. I will also add navbar because navbar is missing from the page from there user doesn't able to seeing a way to navigate to other pages of the website .
6. And also improve the design of this page where ever possible 

**Describe the solution you'd like**
I want to create a new contributors page and integrate it with the website so that everyone can access it

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I did many changes like 
1. Implemented dark mode for the page 
2. Added navigation bar to the top of the page 
3. Added top contributors heading 
4. Added fade up animation to the cards 
5. Created this by keeping responsiveness in mind 

## Screenshots

https://github.com/Counselllor/Counsellor-Web/assets/118350936/efa1dae0-8d57-4723-b1ab-e461dbbe2b95

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Please review this and want any changes let me know

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-01 19-09-38

There is a Gap b/w Navbar and page work on that !

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  I solved this Please review

**Comment by thestarsahil** [comment]
Do I things remove the nvabar

**Comment by Ayushmaanagarwal1211** [comment]
Ok I will remove but can you please tell me where j can put mode toggling button

**Comment by Ayushmaanagarwal1211** [comment]
Because I also developed dark mode for the website

**Comment by thestarsahil** [comment]
Not need to use toogle button ! We will see later !
First Change this  !

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Done

**Comment by thestarsahil** [comment]
I m merging this , but next changes have to be done !

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Review by thestarsahil — APPROVED** [review]
Working Good !

**Comment by Ayushmaanagarwal1211** [comment]
> I m merging this , but next changes have to be done !

And can you please tell me the next changes

**Pull request merged**
