### PR TITLE
Added hovering effect for FAQ and enhanced the UI

### LINKED ISSUE #947: Feat: Want to display the answer for each Frequently Asked Questions and add hover effect for subscribe button
Instead of clicking on '+' button to view the answer for each FAQ, I want to display those answers on hovering on the respective questions

Also, I want to add hover effect to the lower subscribe button 

FAQ

### PR DESCRIPTION
**Pull request by Asymtode712**
# Description

- Added hovering effect for each question of FAQ section, such that the component displays answers on hover instead of clicking a particular question
- Added hovering effect for Subscribe button
- Added hovering effect for footer social links 

## Screenshots

https://github.com/user-attachments/assets/9aed1015-612b-4a5c-b70a-25475f6deb2b

## Checklist

- [X] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [X] Code follows the established coding style guidelines
- [X] All tests are passing

### CODE REVIEW

**Comment by Asymtode712** [comment]
@thestarsahil Please review and merge this PR

**Comment by thestarsahil** [comment]
Not , looking perfect for website 
We want simpler as much simpler, as you saw most top MNCs website they make their simple !

**Comment by Asymtode712** [comment]
@thestarsahil Can you please specify any details so that I can change it accordingly

**Comment by thestarsahil** [comment]
This area work is done now, you can shift to another problem statement 
Thanks , looking fresh new bugs

**Pull request closed without merging**
