### PR TITLE
Jobs pages

### LINKED ISSUE #889: [Feat] : Missing Jobs page
**Is your feature request related to a problem? Please describe.**

@thestarsahil 

check this out,
there are missing `/jobs` page

image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

[Feat] : Missing Jobs page #889

close #889

## Fixes #889(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

- added new route `/jobs`
- list available jobs
- make it repsonsive

## Screenshots

image

image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil 

i pulled upstream and make fresh pr 
kindly check this and merge it

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-08 00-06-14
Screenshot from 2024-07-08 00-08-28


This is not a actual website , this is how your changes effecting to others pages

**Comment by dhruv8433** [comment]
@thestarsahil 

i resolve theme issue

image

**Comment by thestarsahil** [comment]
Still not working

**Pull request closed without merging**
