### PR TITLE
Added Dark Mode Toggle

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #586 

image

@thestarsahil please check and let me know if any changes are required

### CODE REVIEW

**Comment by Hemashree21** [comment]
@thestarsahil I resolved all conflicts

**Comment by thestarsahil** [comment]
https://dribbble.com/shots/21043765-UI-Components
Take some refrence , Or we gonna talk in eve at 9pm in discord !
id = thestarsahil#0568

**Comment by Hemashree21** [comment]
Sure, we'll have a call at 9!

**Comment by thestarsahil** [comment]
Today @10pm meeting at discord , we will discuss this !

**Comment by Hemashree21** [comment]
Okay

**Comment by thestarsahil** [comment]
References: 

image
image
image
image
image
image

**Comment by Hemashree21** [comment]
@thestarsahil I have changed the CSS, can you please check and let me know if any changes are required?

image

image

image

image

**Review by thestarsahil — CHANGES_REQUESTED** [review]
background-color: #0FFFC6; 
  Apply all Change to 
    background-color: #3c38b9;

**Pull request closed without merging**
