### PR TITLE
Display subscribed msg using react toastify

### PR DESCRIPTION
**Pull request by Amruta7203**
# Description

Display subscribed msg using react toastify

## Fixes #822 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

## Checklist

- [ x] Tests have been added or updated to cover the changes
- [ x] Documentation has been updated to reflect the changes
- [ x] Code follows the established coding style guidelines
- [ x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-04 23-08-21
Screenshot from 2024-07-04 23-08-34

It's error on toast message , and toast mesaage stick after appearing and suddenly show the error page 
After reloading the page , then its working normal but you have to fix this !

**Comment by Amruta7203** [comment]
now its working fine @thestarsahil 

[email.webm](https://github.com/Counselllor/Counsellor-Web/assets/116087736/1287a946-19b7-4b84-837f-6ad1373e5e98)

pls check and merge this. Thank you!

**Comment by thestarsahil** [comment]
Can you also do with authentication aur login part !

**Comment by Amruta7203** [comment]
Could you pls elaborate @thestarsahil

**Comment by thestarsahil** [comment]
@Amruta7203 Not working dear , same problem still

**Comment by thestarsahil** [comment]
https://github.com/Counselllor/Counsellor-Web/assets/84167034/dc3c6607-d717-4056-80ca-4bba38a61997

**Comment by Amruta7203** [comment]
I am not getting the problem @thestarsahil ..Could you help me with it?

**Comment by thestarsahil** [comment]
Come on discord VC I'll explain it

**Pull request closed without merging**
