### PR TITLE
Want To Fix Ui of Contact Us Page #1099

### LINKED ISSUE #1099: Want To Fix Ui of Contact Us Page
image

The Contact Us page Ui is broken want to Fix it

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

Fixed UI of Contact Us Page

## Fixes #1099 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

Screenshot 2024-07-17 201340

## Checklist

- [ X] Tests have been added or updated to cover the changes
- [X ] Documentation has been updated to reflect the changes
- [X ] Code follows the established coding style guidelines
- [X ] All tests are passing

### CODE REVIEW

**Review by thestarsahil — APPROVED** [review]

**Comment by Ujjawal18023** [comment]
image
image
image
image

Hey @thestarsahil  I see that you are giving all level 3 levels to this user just for adding extra 5-6 lines of css in just a tablet view and this contributor increase the number of lines by just adding .contact selector these classes are running nice without .contact 
It's my request please review pr's by paying attention and check the code thoroughly 
Otherwise i have to mention sanjay-kv sir to take an action against the contributor and you

**Comment by Ujjawal18023** [comment]
And their are many peoples like 
image
image
 
i see that these are the some pr's where user gave sufficient amount of time and give proper effort so you gave level2 
Kindly Please assign labels on the basis of complexity

**Comment by thestarsahil** [comment]
@Ujjawal18023 Sorry I Don't checked yet 
Thanks for informing

**Comment by Ujjawal18023** [comment]
> @Ujjawal18023 Sorry I Don't checked yet Thanks for informing

My please thanks for understanding and if you have time please checkout other pr's as well

**Pull request merged**
