### PR TITLE
Enhanced Texts in Terms and Conditions Pages to Ensure Legal Compliance and Added Dynamic Date Functionality

### LINKED ISSUE #1057: Enhance and Fix The "Terms and Conditions" Bugs and Issues
Hey @thestarsahil 

- The terms and conditions page is not properly aligned 
- it has dummy texts 
- The navbar is of after login page (you can see profile navlink and log out link even tho it is already logged out!)
- Improper Alignments

image

image

### PR DESCRIPTION
**Pull request by MastanSayyad**
# Description

Hey @thestarsahil 

- Issue closes #1057 

I have removed the old dummy texts of the terms and conditions page and added many more legal compliance texts to the page 
Additionally, I have also added Dynamic date functionality which updates weekly, (to maintain consistency across legal pages)

## Screenshots

image

image

image

image

image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Code follows the established coding style guidelines

### CODE REVIEW

**Comment by thestarsahil** [comment]
Text is too heavy in mobile devices , look the font weight and size

**Comment by MastanSayyad** [comment]
> Text is too heavy in mobile devices , look the font weight and size

@thestarsahil I have made the changes

image


https://github.com/user-attachments/assets/fab7e284-a749-4293-9a52-d42cf1c2efbe

**Comment by thestarsahil** [comment]
Not proprly aligned , text taking their space to capture reponsive and even in mobile 
Navbar should be small in size

**Comment by MastanSayyad** [comment]
> Not proprly aligned , text taking their space to capture reponsive and even in mobile Navbar should be small in size

okay I will fix it!

**Comment by MastanSayyad** [comment]
> Not proprly aligned , text taking their space to capture reponsive and even in mobile Navbar should be small in size

@thestarsahil I have fixed it

image

image

**Comment by MastanSayyad** [comment]
@thestarsahil please take a look and review it!

**Comment by thestarsahil** [comment]
https://www.apple.com/in/contact/

try to work like this

**Comment by MastanSayyad** [comment]
> https://www.apple.com/in/contact/
> 
> try to work like this

Its not working it is affecting the other part of the code and alignments @thestarsahil

**Comment by MastanSayyad** [comment]
> > > https://www.apple.com/in/contact/
> > > try to work like this
> > 
> > 
> > Its not working it is affecting the other part of the code and alignments @thestarsahil
> 
> It is possible , you can do it Try and research more

Yes I will

**Comment by thestarsahil** [comment]
All

**Pull request closed without merging**
