### PR TITLE
Added College detailed page with beautiful styling

### LINKED ISSUE #860: [Feat] : Redesign college detailed page
**Is your feature request related to a problem? Please describe.**

@thestarsahil 

we can redesign college deatiled page

image

something like this

image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

[Feat] : Redesign college detailed page #860

## Fixes #860(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly please review this pr
if you need any modification then please inform me

**Comment by dhruv8433** [comment]
@thestarsahil 

i fetched upstream 

kindly please review this pr
if you need any modification then please inform me

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly review it and merge it
if you need any modifications please inform me

**Comment by thestarsahil** [comment]
I am waiting for @komal-agarwal5 Changes 
As your changes are required inside the students section

**Comment by dhruv8433** [comment]
ok thank you for response @thestarsahil sir

**Comment by dhruv8433** [comment]
@thestarsahil sir,

currenly i am working on redux issue 
i will create pull request till tommorow 

Thank you :)

**Comment by komal-agarwal5** [comment]
> I am waiting for @komal-agarwal5 Changes As your changes are required inside the students section

Yes I will complete by tonight

**Comment by dhruv8433** [comment]
@thestarsahil
i fetched upsteram and resolve all conflicts
now you can merge this detailed page

image

if you need any modifications please inform me

**Comment by thestarsahil** [comment]
@dhruv8433 You don't have to do this , 
Look when user see the list of students , they will click to see the profile of student and that you have to make the section inside the student profile

**Comment by dhruv8433** [comment]
@thestarsahil 

i designed college detailed page as mention in issue #860
i will do student particualr page in another issue is it ok...? 

can you please merge this ...

**Comment by thestarsahil** [comment]
This is not we want how can i merge this !

**Comment by dhruv8433** [comment]
Ok i will update my code

**Comment by dhruv8433** [comment]
@thestarsahil 

I need your help 
Can you please tell me where the list of students will be shown?

**Comment by dhruv8433** [comment]
@thestarsahil 

I need your help 
Can you please tell me where the list of students will be shown?

**Comment by thestarsahil** [comment]
> @thestarsahil
> 
> I need your help Can you please tell me where the list of students will be shown?

Let's talk in vc for briefly , join it

**Comment by dhruv8433** [comment]
can i join in discord ?

**Comment by thestarsahil** [comment]
> can i join in discord ?
 i am talking about discord

**Comment by dhruv8433** [comment]
ok

**Comment by thestarsahil** [comment]
I am in VC join now !

**Comment by dhruv8433** [comment]
@thestarsahil 

can you please share me join link

**Comment by thestarsahil** [comment]
https://discord.com/channels/1231112132595028008/1231120910027722823

**Pull request closed without merging**
