### PR TITLE
Added Courses page

### LINKED ISSUE #717: To add a course page
**Is your feature request related to a problem? Please describe.**
I want to add course page so that the website is one more step closer to being professional.

### PR DESCRIPTION
**Pull request by ayush-848**
# Description

Added the Courses Page

## Screenshots
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil please check this

**Comment by thestarsahil** [comment]
@ayush-848 Resolve conflict

**Comment by ayush-848** [comment]
@thestarsahil conflict resolved

**Review by thestarsahil — APPROVED** [review]
Working Good !

**Pull request merged**
