### PR TITLE
feat: Added ScrollToTop

### LINKED ISSUE #319: Scroll to top
**Is your feature request related to a problem? Please describe.**
There should scroll to top button to the website
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Assign this issue to me under GSSOC'23

### PR DESCRIPTION
**Pull request by JiyaGupta-cs**
# Description

I have added the Scroll To Top Button

## Screenshots

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
The ScolltoTop component work only for dashboard page to another page also ?

**Comment by JiyaGupta-cs** [comment]
For now it works on dashboard
Since it's the only lengthy page in the website

**Comment by thestarsahil** [comment]
if we later on add pages for jobs and courses does it will work there as same now ?

**Comment by thestarsahil** [comment]
okay , if you work on job page section , We'll provide you highest point = Hard 
and by this we can check the working for scroll top feature also

**Comment by thestarsahil** [comment]
Yes , since in jobpage no one yet contributed till 
If you wanna work on that page , you are welcome

**Comment by JiyaGupta-cs** [comment]
@thestarsahil But what's the task to do there?

**Comment by thestarsahil** [comment]
Build UI and create the page

**Comment by JiyaGupta-cs** [comment]
@thestarsahil Ok, I would love to create the frontend.
Please assign me there also
And merge this PR

**Comment by thestarsahil** [comment]
Creat a issue for Jobpage Creation I'll assign you !

**Comment by JiyaGupta-cs** [comment]
@thestarsahil

I have opened the issue
As well as I have created an issue for Contact Page also
Please assign me there also.
And please merge it today as I need to create a pull request , so I need to have free branches to open new PRs
Since at a time only one PR can be opened from on branch

**Comment by JiyaGupta-cs** [comment]
@thestarsahil Please merge this also

**Comment by thestarsahil** [comment]
The Scroll Function work good !

**Pull request merged**
