### PR TITLE
Backend Integration for COmment feature on the blog page 

### LINKED ISSUE #1096: Want to add the functionality to comment the blog
**Is your feature request related to a problem? Please describe.**
I want to add the functionality where user can do comment on the blog

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have created a feature for comment where user can do comment on any blog 
I have integrated this with the backend where anyone will be able to see the comment done by any user 

## Screenshots

https://github.com/user-attachments/assets/9e96ef46-a3c8-4acb-ba50-0d1ce5cab9c6

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-21 12-22-43
Screenshot from 2024-07-21 12-23-04

Make like this

**Comment by Ayushmaanagarwal1211** [comment]
> Screenshot from 2024-07-21 12-22-43 Screenshot from 2024-07-21 12-23-04
> 
> Make like this
@thestarsahil  Ok sir i will do this like that but can i please make only text editor in other pr because for that i have to use react quill new library for that i have to change the whole code once again

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i have updated the design 

https://github.com/user-attachments/assets/514223b6-d252-406c-8648-02bf8ad0b0a9

And sir i will implement text editor to all the input field in other pr Like while creating or editing the blogs as well

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-21 19-03-12

Screenshot from 2024-07-21 19-03-04

After Commenting this text not disappear , and font size is too heavily make it light

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Done sir please check

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
