### PR TITLE
College page redesigned

### LINKED ISSUE #926: Fix college pages layout
**Is your feature request related to a problem? Please describe.**
The alignment is improper in college pages

**Describe the solution you'd like**
I want to realign this and make ui proper

**Describe alternatives you've considered**

**Additional context**
image

### PR DESCRIPTION
**Pull request by komal-agarwal5**
# Description

The cards in college page were not aligned properly.I have improved the overall layout,fixed alignment of both left college card and right student card with avatar image.

## Screenshots

Screenshot 2024-07-09 013033
Screenshot 2024-07-09 013053

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Huge gap b/w the navbar and college page from top area 
and design is not looking as expected

**Comment by komal-agarwal5** [comment]
> Huge gap b/w the navbar and college page from top area and design is not looking as expected

@thestarsahil 
Ok i can change it,please tell me what type of design you want , i will do it

**Comment by thestarsahil** [comment]
@komal-agarwal5 As you can see in readme file the same i want 
Left side we can adjust some parts , but in right side i want same !
image

**Comment by komal-agarwal5** [comment]
> @komal-agarwal5 As you can see in readme file the same i want Left side we can adjust some parts , but in right side i want same ! image

Ok i will redo it and make it like this

**Comment by komal-agarwal5** [comment]
Screenshot 2024-07-12 020806

I have redone it and made it like the ui of the readme as much was possible
I hope you will like it now

@thestarsahil

**Comment by thestarsahil** [comment]
Fix the gap bw navabar and college section

Do this all changes

**Comment by komal-agarwal5** [comment]
> Fix the gap bw navabar and college section
> 
> Do this all changes

On left side college image will be like small box or cover full left side ?

**Comment by thestarsahil** [comment]
Don't cover make a card

**Comment by thestarsahil** [comment]
As make sure check before pushing , first pull the latest changes and then push it 
Also make sure your changes not gonna effect to other pages

**Comment by komal-agarwal5** [comment]
> As make sure check before pushing , first pull the latest changes and then push it Also make sure your changes not gonna effect to other pages

Yes

**Comment by komal-agarwal5** [comment]
Screenshot 2024-07-12 213737

@thestarsahil All fixed finally!!!

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-13 09-47-52

Make a footer so , that the whole college cover the whole screen of device 


One thing the change effected to login page 
See the Difference 

Our Live Site : 
Screenshot from 2024-07-13 09-50-21

Your Changes : 
Screenshot from 2024-07-13 09-50-12

**Comment by komal-agarwal5** [comment]
@thestarsahil fixed
Please check and if alright then merge

**Comment by komal-agarwal5** [comment]
@thestarsahil If any more such alignment redesigning work then u can tell me like previous time,I will be happy to do it.

**Comment by thestarsahil** [comment]
@komal-agarwal5 Sorry Dear , We had to revert your PR because of your changes effecting to login page area and due to this login button stuck in problem 
I request to create a same PR but this make sure not to effect any other page

**Comment by komal-agarwal5** [comment]
> @komal-agarwal5 Sorry Dear , We had to revert your PR because of your changes effecting to login page area and due to this login button stuck in problem I request to create a same PR but this make sure not to effect any other page

Ok I am making another without those effects

**Pull request merged**
