### PR TITLE
Enhancement: Sign Up (Issue #224)

### LINKED ISSUE #224: Enhancement: Sign Up (GSSoC'23)
**Is your feature request related to a problem? Please describe.**
I will enhance the sign up page by making it responsive. I will also utilize Chakra UI to change the layout of the page by using it's components. I will replace the current fields with more optimized components.

image

### PR DESCRIPTION
**Pull request by abrehan2**
# Description
Hello, I have implemented Chakra UI and enhanced the appearance of the Sign up page by substituting the components and revamping the design, resulting in improved performance. It should be a level 3 issue as I did a lot of work!

## Fixes #224 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots
**Before:**

image

**After:**

Screenshot 2023-07-02 225050

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
BUGS : 

1. The codebase was not responsive in multiple devices, which meant that the layout of the page would change depending on the size of the device. This could cause problems for users who were viewing the page on a mobile device or a tablet.

2.The design layout of the page has changed. However, we do not want to change the codebase to reflect the new design layout. This is because it would be a lot of work, and it would also be difficult to maintain. Instead, we will be using more efficient code to render the new layout. This code will use the <Stack> component, which is a more efficient way to layout elements.

**Comment by abrehan2** [comment]
What should I do now?

**Comment by abrehan2** [comment]
Should I do it responsive? Will then the PR get merged?

**Comment by thestarsahil** [comment]
@abrehan2 

Upon reviewing the PR, We have noticed that there are certain areas that require attention. Additionally, we should assess the efficiency of the code to optimize its performance and eliminate any potential bottlenecks. 
From your Codebase Structure 88% performance level coming instead of 92% performance coming from our codebase 

Moreover, the design layout appears to be significantly different from the intended vision. We should carefully analyze the design requirements and ensure that the implemented layout aligns with the project's goals and aesthetics.

We suggest conducting a comprehensive evaluation of the codebase, implementing responsive design principles, and revisiting the design specifications.

**Pull request closed without merging**
