### PR TITLE
When User SignUP he is only Getting Authenticated but his Data Not Getting Stored In RTDB #950

### LINKED ISSUE #950: When User SignUP he is only Getting Authenticated but his Data Not Getting Stored In RTDB
**Is your feature request related to a problem? Please describe.**
When User SignUP he is only Getting Authenticated but his Data Not Getting Stored In RTDB because of that we Cant make Anything dynamic 

**Describe the solution you'd like**

His Data Should Get Stored In Database
**Describe alternatives you've considered**

**Additional context**

https://github.com/Counselllor/Counsellor-Web/assets/101548649/12659c39-0035-49ba-ae3a-e6824c6e9ea3

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

When User SignUP he is only Getting Authenticated but his Data Not Getting Stored In RTDB 
Storing data as well as Id Which will act as primary key for over Blogs and any other feature
the older function was not storing id properly so fixed that

Okay Major issue with the Login was it is Signing in user by verifying auth details not the rtdb details which was causing a problem because we will need database id which was setuped in signup code so what i have done is mapped emails and databse id now whenever user try to sign in he will first access emails database and get database id from there and after that 
he will be able to access user database

## Fixes #950 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

https://github.com/Counselllor/Counsellor-Web/assets/101548649/feb1e30d-1fac-4f39-bd57-e8b0e0fff1e7

## Checklist

- [X ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [X ] Code follows the established coding style guidelines
- [X ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-12 20-42-32

As you can see that , the changes already implemented before how it is different from that

**Comment by nishant0708** [comment]
> Screenshot from 2024-07-12 20-42-32
> 
> As you can see that , the changes already implemented before how it is different from that

Sir the difference is  trying loging in and you will not able to see you database id any where ..

**Comment by nishant0708** [comment]
> > Screenshot from 2024-07-12 20-42-32
> > As you can see that , the changes already implemented before how it is different from that
> 
> Sir  @thestarsahil  the difference is trying loging in and you will not able to see you database id any where ..

And It is necessary for blogs and profile page so we definitely need that database id in our local storage

**Comment by thestarsahil** [comment]
Got it , you has implement id to extract the date via id

**Comment by nishant0708** [comment]
Yaa mainly and and for signup it was quite easy but when we login it was quite tough because first I mapped email with database id and then when you first try to log in it first get id of database using and email and then extract information from database

**Comment by nishant0708** [comment]
> Yaa @thestarsahil  mainly and and for signup it was quite easy but when we login it was quite tough because first I mapped email with database id and then when you first try to log in it first get id of database using and email and then extract information from database. And added one function which provides better ids

**Comment by nishant0708** [comment]
hey @thestarsahil please merge this pr asap if found appropriate because i need to make blog and profile page as well

**Comment by thestarsahil** [comment]
@nishant0708 Good Job bruh !

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
