### PR TITLE
added alerts on UI when user log-in/log-out, enters wrong password/captcha or unregistered email.

### LINKED ISSUE #636: Resolving some bugs when user tries to signup/login.
**Describe the bug**
When users are signing up or logging in on the website, proper error handling and alert displays are not implemented.

**Expected behavior**
- When I tried logging with a new email id which is not registered. The error is not handled properly, an alert should be prompting saying that the email is not registered.
> Screenshot (509)

- After a successful log-in, an alert displaying the message "You are logged in" should appear. This alert needs to be designed to be visually appealing and in harmony with the website's overall theme. Currently, there is no alert, and the homepage opens abruptly.

- When logging out successfully, there is no alert. However, the user should receive an alert even in this situation.

- When a user inputs an incorrect password or captcha, the default browser alert is displayed. I would like to modify this alert to be more appealing and match the website's theme.

**Additional context**
Kindly assign this issue to me under GSSOC'24.

### PR DESCRIPTION
**Pull request by yashi-15**
# Description

I have added **ALERTS/ TOAST NOTIFICATION** on UI for,
1. User successfully loged-in or logged-out
2. Enters unregistered email while login.
3. Enters wrong password or captcha

## Screenshots

Screenshot (517)
Screenshot (518)
Screenshot (514)
Screenshot (515)
Screenshot (519)

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Screenshot from 2024-05-30 20-17-12

As you can see logged in pop message hiding under navbar , Shift down downwards navbar so , we can see two pop message clearly !
Thanks

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
Yes he have done the toasters, I will be implementing the autocomplete and other stuffs to get rid of the warnings and errors from the console

**Comment by yashi-15** [comment]
> Screenshot from 2024-05-30 20-17-12
> 
> As you can see logged in pop message hiding under navbar , Shift down downwards navbar so , we can see two pop message clearly ! Thanks

I have made the changes. Please review them ... @thestarsahil.

**Comment by thestarsahil** [comment]
Screenshot from 2024-05-30 22-26-16

It should be same as Logout pattern !

**Comment by yashi-15** [comment]
Done! @thestarsahil 
Screenshot (522)
Screenshot (524)

**Pull request merged**
