### PR TITLE
fixed the joinus page

### LINKED ISSUE #1268: Parts of join us page are not readable in light mode
Parts of join us page are not readable in light mode

image
image

### PR DESCRIPTION
**Pull request by ayush-848**
## Screenshots
image
image
image
image
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Do as same as privacy page Screenshot from 2024-07-27 09-40-24

Reference for font size : Top University Page
Screenshot from 2024-07-27 09-41-45

**Comment by ayush-848** [comment]
> Do as same as privacy page Screenshot from 2024-07-27 09-40-24
> 
> Reference for font size : Top University Page Screenshot from 2024-07-27 09-41-45

From the privacy page should I do the Coloring??

**Comment by thestarsahil** [comment]
> > Do as same as privacy page Screenshot from 2024-07-27 09-40-24
> > Reference for font size : Top University Page Screenshot from 2024-07-27 09-41-45
> 
> From the privacy page should I do the Coloring??

Yes , I meant to say the way of structure given in privacy same i want same kind of structure in join us page , Include High Quality Image

**Comment by ayush-848** [comment]
> > > Do as same as privacy page Screenshot from 2024-07-27 09-40-24
> > > Reference for font size : Top University Page Screenshot from 2024-07-27 09-41-45
> > 
> > 
> > From the privacy page should I do the Coloring??
> 
> Yes , I meant to say the way of structure given in privacy same i want same kind of structure in join us page , Include High Quality Image

Well both of them have left centred text
1 thing missing is that the box type contain in terms and conditions page

**Comment by thestarsahil** [comment]
https://www.apple.com/careers/us/
This is the actual reference

**Comment by thestarsahil** [comment]
let connect on VC briefly discuss

**Comment by ayush-848** [comment]
> let connect on VC briefly discuss

Sure
Should I connect now?

**Comment by thestarsahil** [comment]
yes

**Comment by ayush-848** [comment]
> yes

Sure
Well which one one should I connect 
I am not well versed in discord

**Comment by thestarsahil** [comment]
in gssoc channel

**Comment by thestarsahil** [comment]
https://discord.com/channels/1231112132595028008/1231120910027722823

**Comment by thestarsahil** [comment]
https://www.apple.com/privacy/

**Comment by ayush-848** [comment]
@thestarsahil see the layout
image

**Comment by thestarsahil** [comment]
Ya that work's

**Pull request closed without merging**
