### PR TITLE
Enhanced the privacy policy page

### LINKED ISSUE #1102: Redesigning the Privacy Policy page
Same reason as #1101
and here the font used is also not same as other pages

### PR DESCRIPTION
**Pull request by ayush-848**
# Description
Enhanced the privacy page.

## Screenshots
image
image
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil if any problem occur give me a screen shot and let me know. Since my clg is started I only have limited time for contributions. I hope you understand my problem

**Comment by thestarsahil** [comment]
@ayush-848 We are also done with contribution part !
Now , Focus on your cllg time ,  if you happy to contribute on weekend time i shall look forward to you

**Comment by ayush-848** [comment]
> @ayush-848 We are also done with contribution part ! Now , Focus on your cllg time , if you happy to contribute on weekend time i shall look forward to you

So is this PR good??

**Comment by thestarsahil** [comment]
> > @ayush-848 We are also done with contribution part ! Now , Focus on your cllg time , if you happy to contribute on weekend time i shall look forward to you
> 
> So is this PR good??

this area is done !

**Comment by ayush-848** [comment]
> > > @ayush-848 We are also done with contribution part ! Now , Focus on your cllg time , if you happy to contribute on weekend time i shall look forward to you
> > 
> > 
> > So is this PR good??
> 
> this area is done !

Oh I have been working on it for nearly a week. But if you don't want this you can close the PR

**Comment by thestarsahil** [comment]
You can work on term and help page 
No one yet assigned 
Do the same as privacy page

**Comment by ayush-848** [comment]
> You can work on term and help page No one yet assigned Do the same as privacy page

Ok let me create an issue.
And should I close this PR?

**Comment by thestarsahil** [comment]
yes

**Pull request closed without merging**
