### PR TITLE
Dark Mode toogle button is added

### LINKED ISSUE #311: DarkMode toogle
**Is your feature request related to a problem? Please describe.**
Change to darkMode button in website
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Assign this issue to me under GSSOC'23

### PR DESCRIPTION
**Pull request by shraddha761**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #311 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image
## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by shraddha761** [comment]
@thestarsahil Please review

**Comment by thestarsahil** [comment]
Good , but Try to build from this Project 
Want Source Reference Find it on my REPO !
https://book-finder-sahil.netlify.app/

**Comment by thestarsahil** [comment]
Not , Working as Expected !
Check Netlify Bot Deploy

**Comment by shraddha761** [comment]
Actually I forced push the change that's why in deployment you are seeing previous changes

**Comment by shraddha761** [comment]
image


This is changes I had done in darkMode

**Comment by thestarsahil** [comment]
By the way Did  you made the Navbar?

**Comment by shraddha761** [comment]
Yahh I am working on it

**Comment by thestarsahil** [comment]
Take a reference my the link i shared !

**Comment by shraddha761** [comment]
Branches are conflicting  and code also  That's why i thought completing this one first

**Comment by thestarsahil** [comment]
It's Okay , I'll Do that 
You work on that

**Comment by shraddha761** [comment]
so In this I'll add button inside navbar , anything else?

**Comment by thestarsahil** [comment]
Show the prototype first

**Comment by shraddha761** [comment]
@thestarsahil Please review

**Comment by shraddha761** [comment]
@thestarsahil please review this pr so that I can work on navbar

**Comment by shraddha761** [comment]
image

**Pull request closed without merging**
