### PR TITLE
adding the blog section

### PR DESCRIPTION
**Pull request by Khushi-Shar**
# Description
Hi, I have created a blog section for the website which has blogs related to scolarships, finance, career guidence, technology, productivity, planning and higher education. I have tried to incorporate all the modifications listed by @thestarsahil.    

## Screenshots
BlogHomeC

BlogHome2C

SearchBoxC

The search box provides the blog which is searched in search box.

SinglePostC

The single post option provides the first blog of blog section.

All blogs contains categories section, related post section and a comment section aswell.
## Checklist

- [x] Tests have been added or updated to cover the changes
- [x ] Documentation has been updated to reflect the changes
- [x ] Code follows the established coding style guidelines
- [x ] All tests are passing

### CODE REVIEW

**Comment by VGandhi27** [comment]
Once it's done please make a pull request

**Comment by Khushi-Shar** [comment]
> Thank you @Khushi-Shar for your contribution. But you don't need to create a separate folder for this blog section khushi
> 
> Please merge your changes with the existing ones, till then I'm putting this in draft

Hi, Do I have to merge the css file with the exsisting css file of master branch as well ?

**Comment by thestarsahil** [comment]
@Khushi-Shar Till now This feature can't be included at this moment!
But I am keeping this in a draft to make this have to merge.
Since Now , Work more in this blog section area more user interaction 
Make better CSS using Tailwind and active responsiveness to mobile users
I am happy to see your hard work towards this project!

**Comment by thestarsahil** [comment]
Hello @Khushi-Shar 
Now we gonna impliment Blog section page , will you able to contribute of this?

**Comment by Khushi-Shar** [comment]
> Hello @Khushi-Shar Now we gonna impliment Blog section page , will you able to contribute of this?

@thestarsahil Sorry, I will not be able to contribute further. Thanks for considering !

**Pull request closed without merging**
