### PR TITLE
enhanced the privacy page

### LINKED ISSUE #1101: Redesigning the Terms and Conditions page
This page is too basic and does not follow the theme of the other pages

### PR DESCRIPTION
**Pull request by ayush-848**
# Description

Enhanced the privacy policy page

## Screenshots

image
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
image
@thestarsahil now it is not affecting the login page

**Comment by thestarsahil** [comment]
check again it's affecting

**Comment by ayush-848** [comment]
> check again it's affecting

Can u give a screenshot?

**Comment by ayush-848** [comment]
@thestarsahil by affecting do you mean, it is creating error while logging in??

**Comment by thestarsahil** [comment]
> @thestarsahil by affecting do you mean, it is creating error while logging in??

No, css part effecting 
maybe some same classname

**Comment by ayush-848** [comment]
> > @thestarsahil by affecting do you mean, it is creating error while logging in??
> 
> No, css part effecting maybe some same classname

image
are these the one??

**Comment by thestarsahil** [comment]
Different

**Comment by ayush-848** [comment]
> Different

@thestarsahil please give me a screenshot to identify the class. From my side the error is not showing

**Comment by ayush-848** [comment]
@thestarsahil check now. I am trying to debug since 2 hrs and at last I have put the original Privacy function.
Please see now does it work

**Comment by ayush-848** [comment]
@thestarsahil have you checked my latest commit?

**Comment by thestarsahil** [comment]
We implemented some new changes , can you work on that 
Privacypage

**Comment by ayush-848** [comment]
> We implemented some new changes , can you work on that Privacypage

Ok sure

**Pull request closed without merging**
