### PR TITLE
Want to Add Functionality to Like Blogs #1044

### LINKED ISSUE #1044: Want to Add Functionality to Like Blogs
image
something like this

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

**hey @thestarsahil  in This i Have Solved (Extra Issues as well)
fixed blog content Alignment Issue
fixed Footer Overflowing 
now user can Click on Card to redirect to blog read page
Also Fixed Image Overflowing issue of Content**

## Fixes #1044 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

https://github.com/user-attachments/assets/e0a5de13-0556-4b5b-bd38-5bd21175f88f

## Checklist

- [X ] Tests have been added or updated to cover the changes
- [ X] Documentation has been updated to reflect the changes
- [X ] Code follows the established coding style guidelines
- [X ] All tests are passing

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @thestarsahil please review it whenever possible

**Comment by thestarsahil** [comment]
No working

**Comment by nishant0708** [comment]
Oo I have pushedy credentials wait

**Comment by nishant0708** [comment]
hey @thestarsahil  sorry for that it should work fine now just create new blog and test like functionality on that

**Comment by nishant0708** [comment]
It should Work Fine Now @thestarsahil

**Comment by thestarsahil** [comment]
> hey @thestarsahil sorry for that it should work fine now just create new blog and test like functionality on that

As a developers , we shoudl check before pushing it's a set of rules Remebers this !
MNC's doesn't accept this kind of faults

**Comment by thestarsahil** [comment]
[Screencast from 2024-07-18 15-12-25.webm](https://github.com/user-attachments/assets/a704eb18-4f0f-4aab-841b-656537eb3763)

As you can see the storing content in database quite difficult to trace in proper manner 
Work on this

**Review by thestarsahil — APPROVED** [review]

**Comment by nishant0708** [comment]
Hey @thestarsahil can you suggest something for this because even If I add normalisation data will be stored in this way only there as well

**Pull request merged**
