### PR TITLE
Want Fetch profile Pic for blogs from Database #1134

### LINKED ISSUE #1134: Want Fetch profile Pic for blogs from Database
image
Currently it is Static Image i Want If User Have Selected different Avtaar or Profile Pic it Should get Displayed everywhere

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #1134
Added Profile pic and if user update his profile pic from profile then new profile pic will be shown

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

Screenshot 2024-07-23 024634
Screenshot 2024-07-23 025258

## Checklist

- [X ] Tests have been added or updated to cover the changes
- [X ] Documentation has been updated to reflect the changes
- [X ] Code follows the established coding style guidelines
- [ X] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Your branch is not updated , pull the latest changes and push again

**Comment by nishant0708** [comment]
Hey @thestarsahil i wanted to discuss something can we connect in discord?

**Comment by thestarsahil** [comment]
Ya sure come on vc

**Comment by nishant0708** [comment]
Hey @thestarsahil done

**Comment by nishant0708** [comment]
> It's not working

Hey sir can you create new blog and check it there it will work

**Comment by nishant0708** [comment]
> > It's not working
> 
> Hey @thestarsahil  sir can you create new blog and check it there it will work

**Comment by nishant0708** [comment]
image
see this @thestarsahil  blog its newest that i have created

**Pull request merged**
