### PR TITLE
fixed the college cards by adding proper responsiveness

### LINKED ISSUE #846: Feat: Make the Dashboard properly responsive for mobile and tablet screens
**Is your feature request related to a problem? Please describe.**
Currently, the website's dashboard college cards are not properly responsive for mobile and tablet screens

**Describe the solution you'd like**
I would like to add responsiveness to these cards with the help of media queries

**Additional context**

https://github.com/Counselllor/Counsellor-Web/assets/115717746/32f39514-bc85-4ec8-bb56-fc4ca2795103

### PR DESCRIPTION
**Pull request by Asymtode712**
# Description

- Added proper responsiveness to the college cards on `Dashboard`

## Screenshots

https://github.com/Counselllor/Counsellor-Web/assets/115717746/7a3800c8-56a3-4211-8c1e-52131df1b401

## Checklist

- [X] Tests have been added or updated to cover the changes
- [X] Documentation has been updated to reflect the changes
- [X] Code follows the established coding style guidelines
- [X] All tests are passing

### CODE REVIEW

**Comment by Asymtode712** [comment]
@thestarsahil Please review and merge this PR

**Comment by thestarsahil** [comment]
As you can see that , the left portion of card is cover border , which is right having a gap 
So from both their will be equal gap portion !

**Comment by thestarsahil** [comment]
also resolve conflict occured !

**Comment by Asymtode712** [comment]
Hey @thestarsahil , I have fixed the spacing you can see the video below:


https://github.com/Counselllor/Counsellor-Web/assets/115717746/e6c65e1e-9a54-40ec-a742-7e214a11032d



Please review and merge this PR

**Review by thestarsahil — APPROVED** [review]
Working Good !

**Pull request merged**
