### PR TITLE
Get Started Button Should Redirect to Choose Plan Section #1005

### LINKED ISSUE #1005: Get Started Button Should Redirect to Choose Plan Section
image
This button Should redirect to Choose Plan Button

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

now it is scrolling to pricing Section

## Fixes #1005 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

https://github.com/user-attachments/assets/3a627d78-7884-43fa-ad89-978d2d739a48

## Checklist

- [ X] Tests have been added or updated to cover the changes
- [ X] Documentation has been updated to reflect the changes
- [X ] Code follows the established coding style guidelines
- [X ] All tests are passing

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @thestarsahil please review this pr and let me know changes if any

**Comment by thestarsahil** [comment]
update your branch

**Comment by nishant0708** [comment]
hey @thestarsahil branch updated with latest changes

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-14 18-53-32

<button className="career-support__cta-button" onClick={scrollToPricing} >
Not working and in base mode the bottom area css is in dark mode

**Comment by nishant0708** [comment]
Wait looking into it

**Comment by nishant0708** [comment]
Hey @thestarsahil please check discord

**Comment by thestarsahil** [comment]
Its now working , but fixed the dark mode css

**Comment by nishant0708** [comment]
Yeah wait

**Comment by nishant0708** [comment]
done sir @thestarsahil

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
