### PR TITLE
Enhanced the Navbar 

### LINKED ISSUE #571: [Enhance]The Navbar
I would like to enhance the Navbar UI with animations and suitable changes that will align with the theme

### PR DESCRIPTION
**Pull request by sau-mili**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
Changed the UI of navbar
made it sticky on scroll
added hover effects
made it more responsive overall

## Fixes #571 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots
video

https://github.com/Counselllor/Counsellor-Web/assets/146661411/c3f01878-caa5-4277-aae1-03af92703aed

I increased the border radius to 10px after the capture of the video. so that's more sleek looking now

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by sau-mili** [comment]
@thestarsahil can you please check this?

**Comment by thestarsahil** [comment]
@sau-mili Please update this fix ...have'nt done yet

**Comment by sau-mili** [comment]
Which one do you want me to check?

**Comment by thestarsahil** [comment]
> Which one do you want me to check?

The navbar is not impressive , We will gonna discuss tomorrow in discord after 11am via VC somepoints have to cover !

**Comment by sau-mili** [comment]
sure, pkease share your discord id with me

**Comment by thestarsahil** [comment]
Thestarsahil#0568

**Comment by sau-mili** [comment]
I couldn't find you by your id. Please Text me when you are available tomorrow... on discord.. I might not be available at around 11, but I will check your message.

**Comment by thestarsahil** [comment]
@sau-mili I mentioned you ! Kindly Check Gssoc channel in discord

**Pull request closed without merging**
