### PR TITLE
Created full working form 

### LINKED ISSUE #702: Adding Contact Form
**Describe the solution you'd like**
I will implement a contact form for the website using emailjs

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have created the whole working Contact form using email js 

## Screenshots

https://github.com/Counselllor/Counsellor-Web/assets/118350936/1656b523-dfd3-4012-9d73-f6713210b5e8

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
All the email should get into 
sahilali88827@gmail.com for now

**Comment by thestarsahil** [comment]
and update the latest branch up to date it

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil for that can you please send your template id , service id and public api key of email js so that i will enter that and it will start working

**Comment by Ayushmaanagarwal1211** [comment]
> and update the latest branch up to date it

Ok

**Comment by thestarsahil** [comment]
Do it now , i m merging this !

**Comment by Ayushmaanagarwal1211** [comment]
Ok Doing

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Please check

**Comment by thestarsahil** [comment]
> @thestarsahil for that can you please send your template id , service id and public api key of email js so that i will enter that and it will start working

We will do that I m merging this 
Thanks Look more PR from you !
Well Done @Ayushmaanagarwal1211

**Comment by thestarsahil** [comment]
Screenshot from 2024-06-22 17-58-01
The message is showing on Emailjs not on main mails 
@Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
Yes yes this is due to the name field in inout fields i am sending my details on emails js please enter same fields

**Comment by Ayushmaanagarwal1211** [comment]
Screenshot 2024-06-22 180257

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Please change fields like that

**Pull request merged**
