### PR TITLE
Rearrange assets and pages in components

### LINKED ISSUE #1046: Rearrange assets and profile
**Is your feature request related to a problem? Please describe.**
The images are not in order and properly placed and pages also not in component

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by komal-agarwal5**
# Description

I have added all images in assets
I have shifted pages to components
I have modified imports corresponding to the changed paths

## Screenshots

Screenshot 2024-07-14 212633
Screenshot 2024-07-14 212643
Screenshot 2024-07-14 212706

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Pull the upstream latest changes and then push

**Comment by komal-agarwal5** [comment]
> Pull the upstream latest changes and then push

Yes yes I have done that

**Comment by thestarsahil** [comment]
Well you shifted the resource , but the other folder fetching from it 
As path changed , work on it 

Course Page

**Comment by komal-agarwal5** [comment]
> Well you shifted the resource , but the other folder fetching from it As path changed , work on it
> 
> Course Page

Yes, actually I saw that the course page was not working from beforehand hence I didn't add anything there
I am changing the path now

**Comment by komal-agarwal5** [comment]
@thestarsahil check now please

**Comment by komal-agarwal5** [comment]
image
in some pages the link is not working due to typo will i fix this ?

**Comment by thestarsahil** [comment]
@komal-agarwal5 Yes fix this

**Comment by komal-agarwal5** [comment]
> @komal-agarwal5 Yes fix this

Ok completing this in an hour or two

**Comment by komal-agarwal5** [comment]
@thestarsahil done

**Comment by komal-agarwal5** [comment]
@thestarsahil for college page navbar will be this logged in one 
image
or this?
image
since yesterday there were problems happening in login

**Comment by thestarsahil** [comment]
> @thestarsahil for college page navbar will be this logged in one image or this? image since yesterday there were problems happening in login

When user not logged in then show login navbar , when user logged in then show logged out navbar 
Both are different

**Comment by komal-agarwal5** [comment]
@thestarsahil can u pls merge this
then by tonight i can raise the college pr

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
