### PR TITLE
Redux integration

### LINKED ISSUE #859: [Feat] : Display real time profile from `Redux`
**Is your feature request related to a problem? Please describe.**

@thestarsahil 

we can add redux store for state management
from redux we can login and display user data in `/profile` route

image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

@thestarsahil 

[Feat] : Display real time profile from Redux #859

## Fixes #859(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly check this and merge it

**Comment by thestarsahil** [comment]
resolve conflict

**Comment by dhruv8433** [comment]
@thestarsahil 

i resolve all conflicts 
now you can merge it

**Comment by thestarsahil** [comment]
/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:59
                throw new Error(
                      ^

Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:59:9)
    at Object.<anonymous> (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:68:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
  Require stack:
  - /workspaces/Counsellor-Web/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
      at Module._load (node:internal/modules/cjs/loader:986:27)
      at Module.require (node:internal/modules/cjs/loader:1233:19)
      at require (node:internal/modules/helpers:179:18)
      at requireWithFriendlyError (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:41:10)
      at Object.<anonymous> (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:68:76)
      at Module._compile (node:internal/modules/cjs/loader:1358:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
      at Module.load (node:internal/modules/cjs/loader:1208:32)
      at Module._load (node:internal/modules/cjs/loader:1024:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [ '/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js' ]
  }
}

Node.js v20.15.1



Npm run build failed

**Comment by dhruv8433** [comment]
@thestarsahil 

i removed node modules and package lock and after that i try `npm install`
please review it

**Comment by dhruv8433** [comment]
@thestarsahil sir,

when you become free please review it and merge it
if you face any issue please inform me

**Comment by dhruv8433** [comment]
@thestarsahil sir,

when you become free please review it and merge it
if you face any issue please inform me

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
