### PR TITLE
added icons in profile card

### LINKED ISSUE #848: To add social icons to the profile cards that on click will redirect
image

Out of the three social site options, the user can add 0-3 any number of social site and there will be the icons displayed on his profile card that after clicking will take us to his/her socials.

### PR DESCRIPTION
**Pull request by ayush-848**
# Description
Added icons in profile cards

## Screenshots
image
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil now check, it should work good

**Comment by thestarsahil** [comment]
@ayush-848 
Why dd you removed this ? Overlapping occur and no cancel button on edit profile pop message when adding the link

**Comment by ayush-848** [comment]
> @ayush-848 Why dd you removed this ? Overlapping occur and no cancel button on edit profile pop message when adding the link

Well I have n't removed the cancel or save button

**Comment by ayush-848** [comment]
> @ayush-848 Why dd you removed this ? Overlapping occur and no cancel button on edit profile pop message when adding the link

this one is while adding a new profile

**Comment by ayush-848** [comment]
image

@thestarsahil see

**Comment by ayush-848** [comment]
image
this one is while editing profile

**Comment by ayush-848** [comment]
image
before pressing the add button

**Comment by thestarsahil** [comment]
Okay that good !

**Review by thestarsahil — APPROVED** [review]
Working Good !

**Pull request merged**
