### PR TITLE
Fixed Login 

### LINKED ISSUE #1018: Login is not working properly
**Describe the bug**
When i am trying to do login and clicking on login button then nothing happens 

https://github.com/user-attachments/assets/a295595f-6e4a-49cb-a507-07e145a24539

**To Reproduce**
1. Go to login page 
2. Click on login

**Expected behavior**
It must logged in

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have fixed the login problem in the website now the user can be easily loging 

## Fixes #1018 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

https://github.com/user-attachments/assets/d457733d-6352-48e2-b342-f24693fdcac4

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i have fixed the login problem of the website

**Review by thestarsahil — APPROVED** [review]

**Comment by thestarsahil** [comment]
Well Done  @Ayushmaanagarwal1211 
Kudos !

**Comment by Ayushmaanagarwal1211** [comment]
Thank you sir

**Comment by thestarsahil** [comment]
We have to need that data from user end 
So need that part user.database

     localStorage.setItem("userUid", userData.id);

**Comment by Ayushmaanagarwal1211** [comment]
> We have to need that data from user end So need that part user.database
> 
> ```
>  localStorage.setItem("userUid", userData.id);
> ```

Sir i am only setting the is 

> We have to need that data from user end So need that part user.database
> 
> ```
>  localStorage.setItem("userUid", userData.id);
> ```

sir for the signing with email and pass the code taking data from localstorage  here localStorage.getItem(userUid) 
image

And if user already logged in so i am just storing that uid because it is getting undefined so we need to store userUid in the localstorage

**Comment by Ayushmaanagarwal1211** [comment]
> We have to need that data from user end So need that part user.database
> 
> ```
>  localStorage.setItem("userUid", userData.id);
> ```

Ok sir i am finding another way

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir is the login is fixed now can you pelase check again actually in my laptop i am still unable for login

**Pull request merged**
