### PR TITLE
feat: Hamberger feature

### LINKED ISSUE #310: Navbar
**Describe the bug**
There is black dot in navbar which look very inappropiate
**To Reproduce**

**Expected behavior**

**Screenshots**
image
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Assign  this issue to me under GSSOC'23

### PR DESCRIPTION
**Pull request by shraddha761**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #310 

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by shraddha761** [comment]
@thestarsahil Please review

**Comment by thestarsahil** [comment]
Not Worked exactly

**Comment by thestarsahil** [comment]
Can you make the same Navbar which i made on Book Finder Project

**Comment by shraddha761** [comment]
@thestarsahil it is exactly same as you have created in book finder project

**Comment by thestarsahil** [comment]
Ya ...check Css part

**Comment by shraddha761** [comment]
you were talking about whole website mobile view or just hamberger feature

**Comment by thestarsahil** [comment]
Look when we open the same Website in mobile the Navbar Comes under Hamburger features
So make that for all device's

**Comment by shraddha761** [comment]
okk got it thankyou

**Comment by thestarsahil** [comment]
are you still working on this issue !

**Pull request closed without merging**
