### PR TITLE
Added Our Contributors page

### LINKED ISSUE #617: Naming the 'Help' to 'FAQs'
**Is your feature request related to a problem? Please describe.**
image

for issue #616

### LINKED ISSUE #642: Adding "Our Contributors" page
**Is your feature request related to a problem? Please describe.**
I want to add the "Our Contributors" page

### PR DESCRIPTION
**Pull request by ayush-848**
# Description
Added out contributors page

## Screenshots
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil merge this

**Comment by ayush-848** [comment]
@thestarsahil check it

**Comment by thestarsahil** [comment]
[plugin:vite:import-analysis] Failed to resolve import "./FAQs/FAQs.jsx" from "src/components/index.js". Does the file exist?
/workspaces/Counsellor-Web/src/components/index.js:7:19
5  |  import Navbar from "./Navbar/Navbar.jsx";
6  |  import SignUpForm from './SignUp/SignUp.jsx';
7  |  import FAQs from './FAQs/FAQs.jsx'
   |                    ^
8  |  import Contribute from "./Contributors/Contribute.jsx";

fix this

**Comment by ayush-848** [comment]
> [plugin:vite:import-analysis] Failed to resolve import "./FAQs/FAQs.jsx" from "src/components/index.js". Does the file exist? /workspaces/Counsellor-Web/src/components/index.js:7:19 5 | import Navbar from "./Navbar/Navbar.jsx"; 6 | import SignUpForm from './SignUp/SignUp.jsx'; 7 | import FAQs from './FAQs/FAQs.jsx' | ^ 8 | import Contribute from "./Contributors/Contribute.jsx";
> 
> fix this

ok

**Comment by ayush-848** [comment]
@thestarsahil now check and see

**Comment by thestarsahil** [comment]
@ayush-848 Tell me one thing after the changes , does it working fine ?

**Comment by ayush-848** [comment]
> @ayush-848 Tell me one thing after the changes , does it working fine ?

It does work from my end.

**Comment by thestarsahil** [comment]
Minor Changes , Replace the name of file FAQS.jsx to FAQs.jsx

**Comment by ayush-848** [comment]
@thestarsahil done

**Review by thestarsahil — APPROVED** [review]
Okay , working fine !

**Pull request merged**
