### PR TITLE
Added password show feature in both password and confirm password field

### LINKED ISSUE #308: In Signup page there is only one show password field in password but not in confirm password [GSsoc'23]
**Describe the bug**
As you can see that there is only one eye button/password shower which handles both the password and confirm password field.
It is not a convenient way to show password both password and confirm password must have its own password shower.

I will add that functionality to confirm password field and will make it more user friendly!!

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome

Active contributor [GSsoc'23]

### PR DESCRIPTION
**Pull request by Monilprajapati**
Fixes #308 
Preview ::

https://github.com/Counselllor/Counsellor-Web/assets/99136041/163e6986-00fd-41ce-83d2-d59fa4267b10

### CODE REVIEW

**Comment by Monilprajapati** [comment]
Hey @thestarsahil please check this out

**Comment by thestarsahil** [comment]
Hello Developer @Monilprajapati 
I just tested the code you gave me for the password show feature. It works great!
Congrats and Welcome

**Comment by Monilprajapati** [comment]
> Hello Developer @Monilprajapati I just tested the code you gave me for the password show feature. It works great! Congrats and Welcome

That's great but it'll not count in GSsoc contribution now! Am i right ?  or I can still do something

**Comment by thestarsahil** [comment]
No Count Sorry for that !

**Pull request merged**
