### PR TITLE
Added tailwind

### LINKED ISSUE #718: Adding tailwind
**Is your feature request related to a problem? Please describe.**
I want to first try to replace the css by tailwind

### PR DESCRIPTION
**Pull request by ayush-848**
# Description

Updated the [ages with tailwind.

## Screenshots
image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil completed perfectly

**Comment by ayush-848** [comment]
@thestarsahil please check it. I think this will work

**Comment by thestarsahil** [comment]
Screenshot from 2024-06-30 09-09-35

**Comment by ayush-848** [comment]
> Screenshot from 2024-06-30 09-09-35

@thestarsahil I have not touched the login page, I only worked with the Contribute and courses page

**Comment by ayush-848** [comment]
@thestarsahil try to merge it. if the problem remains I will try to fix it

**Comment by ayush-848** [comment]
@thestarsahil There were some issues, I have resolved it

**Pull request closed without merging**
