### PR TITLE
added help page with beautiful styling

### LINKED ISSUE #644: [Feature] : Add Help page
**Is your feature request related to a problem? Please describe.**
@Counselllor

we can add help page
when user click on `help` link from footer they will redirect to `/help` route

image

and it will look like
image

please assign it to me, i would like to work on this issue.

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

@thestarsahil 

[Feature] : Add Help page #644

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #644(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

- added new route `/help`
- when user click on help option from footer they will redirected to `/help` route
- where user got required help

## Screenshots

image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly please check this and merge it

**Comment by thestarsahil** [comment]
This the color theme : For Bold -> #3C38B9 
For Paragraph and semibold -> #00073e

**Comment by dhruv8433** [comment]
@thestarsahil 

as per you theme, i changed font color 
please check this and merge it

**Comment by dhruv8433** [comment]
image

**Comment by thestarsahil** [comment]
Do with other pages also and make another PR 
Great work !

**Comment by dhruv8433** [comment]
sure

**Pull request merged**
