### PR TITLE
Fixed many Errors and also included some features 

### LINKED ISSUE #808: Want to fix many things
**Is your feature request related to a problem? Please describe.**
I saw many things in the website that can be improved like 
1. Adding of navigation bar and implementing the dark mode for that
2. Adding tilt effect to the login page 
3. Adding Footer to every page 
4. Increasing the size of the cards in mobile view 

**Describe the solution you'd like**
I want to fix all these i wrote above 

### Screenshots 
Screenshot 2024-06-30 222001
Screenshot 2024-06-30 221911
Screenshot 2024-06-30 222140

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have fixed many errors and also include some features : 

1. Adding of navigation bar and implementing the dark mode for that
2. Adding tilt effect to the login page
3. Adding Footer to every page
4. Increasing the size of the cards in mobile view
5. Fixed navbar css
6. Responsive of contributors page 

## Screenshots

https://github.com/Counselllor/Counsellor-Web/assets/118350936/eb9d6fda-9d5f-42fe-92f8-ad8a3aa005d0

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing- [ ]

### CODE REVIEW

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-03 16-46-50

Fix this !

**Comment by Ayushmaanagarwal1211** [comment]
Ok fixing

**Comment by Ayushmaanagarwal1211** [comment]
FIxed Please check

**Comment by thestarsahil** [comment]
Pull the latest changes right now , then check status : on branch 
then push again !

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Done can you please check

**Review by thestarsahil — APPROVED** [review]
Working Good !

**Pull request merged**
