### PR TITLE
Jobs page

### LINKED ISSUE #889: [Feat] : Missing Jobs page
**Is your feature request related to a problem? Please describe.**

@thestarsahil 

check this out,
there are missing `/jobs` page

image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

[Feat] : Missing Jobs page #889

close #889

## Fixes #889(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

- added new route `/jobs`
- list available jobs
- make it repsonsive

## Screenshots

image

image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly please check this and merge it

**Comment by thestarsahil** [comment]
Your branch is not uptodate  Please pull the lastest changes and then push it

**Comment by dhruv8433** [comment]
@thestarsahil 

now you can merge it

**Comment by thestarsahil** [comment]
Your branch is not uptodate  Please pull the lastest changes and then push it
Check this website : https://counsellor.social/dashboard

**Comment by dhruv8433** [comment]
@thestarsahil 

image

image

**Comment by thestarsahil** [comment]
Your changes are effecting to whole website 
First check from yourside on whole website

**Pull request closed without merging**
