### PR TITLE
added join us page

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

@thestarsahil 

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #654 (issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil 

please check this and merge it

**Comment by thestarsahil** [comment]
Resolve Conflict

**Comment by dhruv8433** [comment]
@thestarsahil 

now you can merge it

**Comment by dhruv8433** [comment]
@thestarsahil 

please check this and merge it

**Comment by dhruv8433** [comment]
@thestarsahil

please check this and merge it
so i can make another pr

**Comment by thestarsahil** [comment]
Good Working !

**Pull request merged**
