### PR TITLE
Privacy policy page Updated

### LINKED ISSUE #1142: Redesigning Privacy Policy Page
**Is your feature request related to a problem? Please describe.**
Redesigning Privacy Policy Page
**Describe the solution you'd like**
Redesigning Privacy Policy Page
**Describe alternatives you've considered**
Redesigning Privacy Policy Page
**Additional context**
image

### PR DESCRIPTION
**Pull request by Damini2004**
# Description

Privacy policy page Updated

## Fixes #1142 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image
image
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Can you modify your changes into current change ?

**Comment by Damini2004** [comment]
@thestarsahil  didn't get it ?
You didn't like the changes ?

**Comment by thestarsahil** [comment]
Actually we updated the privacy page , see the latest privcay page 
and modify some changes if it possible

**Comment by Damini2004** [comment]
okayy Did You Like the design or not ?
Or i have to do some more modification ?

**Comment by thestarsahil** [comment]
> okayy Did You Like the design or not ? Or i have to do some more modification ?

do modification

**Pull request closed without merging**
