### PR TITLE
Added google & github authentication

### LINKED ISSUE #973: SignIn/SignUp using Google & Github
**Is your feature request related to a problem? Please describe.**
Currently, our website don't have Google & Github authentication option 

**Describe the solution you'd like**
I would like to add this for signing in and signing up

03_Google_GitHub_Login@2x-1536x804

### PR DESCRIPTION
**Pull request by Asymtode712**
# Description

- Added Google & GitHub Sign in buttons
- Added Google & GitHub authproviders
- Added a separator for separating both the buttons from login form
- Added hovering effect for both the buttons

## Screenshots

https://github.com/user-attachments/assets/8edc5cc6-204a-4879-aa34-d1925fe764a2

## Checklist

- [X] Tests have been added or updated to cover the changes
- [X] Documentation has been updated to reflect the changes
- [X] Code follows the established coding style guidelines
- [X] All tests are passing

### CODE REVIEW

**Comment by Asymtode712** [comment]
@thestarsahil Please check it now

**Comment by thestarsahil** [comment]
Not working , Let's have a meet on vc

**Comment by thestarsahil** [comment]
@Asymtode712 Did you fixed this

**Comment by Asymtode712** [comment]
@thestarsahil I have done with every change from my side, and it is also working fine for me!!!

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-22 12-26-46

**Comment by Asymtode712** [comment]
> Screenshot from 2024-07-22 12-26-46

@thestarsahil  Can you please try to add the domain in OAuth redirect as given in the message below

auth

**Comment by thestarsahil** [comment]
@Asymtode712 Auth domain activated now ?

**Pull request closed without merging**
