### PR TITLE
Enhanced and Recreated "Privacy Policy" Page for "Professional and Legal" Compliance

### LINKED ISSUE #834: Enhance and Recreate "Privacy Policy" Page for "Professional and Legal" Compliance
Hey @thestarsahil 

The current Privacy Policy page on the website appears to be a placeholder and contains dummy text such as "Lorem ipsum dolor, sit amet consectetur adipisicing elit." This undermines the professionalism and legal compliance of the website.

image

image

- The Privacy Policy page should contain comprehensive and accurate information regarding the website's data privacy practices.
- The content should be professionally written, clear, and legally compliant to build trust with users and meet legal requirements.

could you please assign this issue to me under gssoc?

### PR DESCRIPTION
**Pull request by MastanSayyad**
# Description

Hey @thestarsahil 

- issue fixes #834

I have created and enhanced the privacy policy page to look more professional and formal 

## Screenshots

image

https://github.com/user-attachments/assets/c48eb8a4-e323-4a87-9101-9606a3b045a4

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

Please take a look and review it,thank you!

### CODE REVIEW

**Comment by thestarsahil** [comment]
Do this : 
Dynamic Date update weekly
Make a page like contributor page or blog page

**Comment by MastanSayyad** [comment]
> Do this : 
> Dynamic Date update weekly
> Make a page like contributor page or blog page 

Yeah sure

**Comment by MastanSayyad** [comment]
Hey @thestarsahil 

I have formated the page and added Dynamic Date update weekly 
With this implementation, the date displayed will automatically update every week to show the most recent update date.

**Comment by thestarsahil** [comment]
Remove line from footer 
Screenshot from 2024-07-15 01-15-53

Same background with same text weight !
Screenshot from 2024-07-15 01-15-26


Fix that both part

**Comment by MastanSayyad** [comment]
> Remove line from footer Screenshot from 2024-07-15 01-15-53
> 
> Same background with same text weight ! Screenshot from 2024-07-15 01-15-26
> 
> Fix that both part

I can remove the line from footer but the background color is not looking good for privacy policy page, I suggest not to change background color for legal pages

**Comment by thestarsahil** [comment]
Remove the home button from left side , and add navbar 
When user not login show that login navbar , when user logged in show logged out navbar

**Comment by MastanSayyad** [comment]
@thestarsahil Is it okay??

image

**Comment by MastanSayyad** [comment]
> Remove the home button from left side , and add navbar When user not login show that login navbar , when user logged in show logged out navbar

Yes

**Comment by thestarsahil** [comment]
> @thestarsahil Is it okay??
> 
> image

No  , Remove counsellor / Privacy 
White background is okay

**Comment by MastanSayyad** [comment]
> > @thestarsahil Is it okay??
> > image
> 
> No , Remove counsellor / Privacy White background is okay

@thestarsahil Done the changes!

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-15 02-09-36

Same navbar i want

**Comment by thestarsahil** [comment]
Footer line not removed yet

**Comment by MastanSayyad** [comment]
> Footer line not removed yet

@thestarsahil Removed it already!

**Comment by MastanSayyad** [comment]
> Screenshot from 2024-07-15 02-09-36
> 
> Same navbar i want



@thestarsahil I tried it but I am unable to do it right now, it will take time, if you permit can I add this in another PR? can you please merge this for now?

**Review by thestarsahil — APPROVED** [review]

**Comment by MastanSayyad** [comment]
@thestarsahil can you increase the label? for dynamic date functionality

**Pull request merged**
