### PR TITLE
feat #559 : Build An Profile Page

### LINKED ISSUE #559: Build a Profile Page
**Is your feature request related to a problem? Please describe.**
here's no central place to view and manage users personal information, preferences, and activity history within the application. This makes it hard to update users details, see user past interactions, and customize my experience.

**Describe the solution you'd like**
I would like to have a comprehensive profile page where users can:

View and edit their personal information such as name, email, and profile picture.
Customize their preferences and settings.
View their activity history, including interactions, saved streams/branches, and chosen colleges.
Access personalized recommendations based on their profile data.

**Describe alternatives you've considered**

**Additional context**

please assign me this issue i want to work on this

### PR DESCRIPTION
**Pull request by CoderSwarup**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
building an the profile page for the website where the user can see their personal profile details and other details also 

## Fixes #(issue_no)
close #559 

## Screenshots

p2

p1

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Found the usage of undeclared variables

      if (user) {
        console.log("");
      } else if (!user) {
        navigate("/");
      }
    });
  }, [ ] );

**Comment by CoderSwarup** [comment]
> Found the usage of undeclared variables
> 
> ```
>   if (user) {
>     console.log("");
>   } else if (!user) {
>     navigate("/");
>   }
> });
> ```
> 
> }, [ ] );

no need to declare this variable 
this is an the passed buy the firebase authentication method as a callback data 

as you see same in the dashboard page 

image

**Comment by thestarsahil** [comment]
Screenshot from 2024-05-25 14-26-44
Screenshot from 2024-05-25 14-26-37

Your Updates effecting to whole dashboard page 

- Effecting to increase in size 
- Responsive side 
- College Card compressed

**Comment by CoderSwarup** [comment]
ok i will fix that

**Comment by CoderSwarup** [comment]
@thestarsahil  check it now

**Review by thestarsahil — APPROVED** [review]
For now, it's fine working but we need to improve the code

**Comment by CoderSwarup** [comment]
> For now, it's fine working but we need to improve the code

Sure

**Pull request merged**
