### PR TITLE
Captcha

### LINKED ISSUE #235: Add Captcha feature
**Is your feature request related to a problem? Please describe.**
No

 **Feature** 
I want to implement Captcha functionality in the signup and login form. The aim of CAPTCHA is to differentiate between human users and automated bots, hence it is an important field in such forms. I would implement a text captcha.

 **Request** 
If you find this issue worth implementing then Please assign me this issue under gssoc23.

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
# Description
Added Captcha in login and Signup form

## Fixes #235
**Add Captcha feature**
closes #235

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Well Done @AlfiyaSiddique Impressive !
But there are few changes need to done 
1. Display should little bit plane as human can able to see and type 
2. Text inside should be copy and paste , It's work like a image having text inside it 

This might help : https://developers.google.com/recaptcha/

**Comment by AlfiyaSiddique** [comment]
Also @thestarsahil , could you please review PR #290 before this one cause even if we merge this code it won't be visible due to style issues which I solved through PR #290.

**Comment by thestarsahil** [comment]
Ya I checked over it ....
It's looking too different from previous one 

You can also have a look on latest deploy on you PR 
Netlify Bot

**Comment by AlfiyaSiddique** [comment]
> Also @thestarsahil , could you please review PR #290 before this one cause even if we merge this code it won't be visible due to style issues which I solved through PR #290.

Yes I checked the preview it reflects all the changes that I made in that PR, But sorry I didn't get you, **Do I need to change anything in that ??**

**Comment by thestarsahil** [comment]
> > Ya I checked over it .... It's looking too different from previous one
> > You can also have a look on latest deploy on you PR Netlify Bot
> 
> Yes I checked the preview it reflects all the changes that I made in that PR, But sorry I didn't get you, **Do I need to change anything in that ??**

It doesn't look similar according to previous one !
Compare both the Responsive 
Made by you with present codebase deployed

**Comment by thestarsahil** [comment]
> Thanks for your feedback @thestarsahil .
> 
> To solve the first issue, I Will try to change the background of the captcha text or make the captcha text more readable. And sure I will make the captcha text copyable.

One mistake from my side 
Its Text inside should not be copy and paste , It's work like a image having text inside it

**Comment by AlfiyaSiddique** [comment]
> It doesn't look similar according to previous one ! Compare both the Responsive Made by you with present codebase deployed


Yes @thestarsahil , I did the comparison but unfortunately, I could not find any error in my implementation, Here's what I'm trying to say:

The current code does not display all the fields of the form which is the issue, as shown below from the hosted site URL:

https://github.com/Counselllor/Counsellor-Web/assets/86224794/81d43c8e-bfa4-4441-812c-79b3c4f9b42d

In order to see all the fields we need to reduce the chrome tab zoom percentage which is generally not considered as good practice.

**So as the solution**, I added the scroll bar on the left side which is the form side to make the form scrollable hence the entire form is visible to the user and it also attains responsiveness, as shown below from my PR deployment preview:


https://github.com/Counselllor/Counsellor-Web/assets/86224794/634608a5-3fa4-4120-a1e8-5ac13b6b5a60

**So now, Can you please describe in a more descriptive way that what exactly I have to change in this ???**

**Comment by AlfiyaSiddique** [comment]
@thestarsahil Increase the readability of the captcha by increasing the font size and weight. Also changed the color.




In my opinion, this much readability is good enough cause the purpose and strategy of the captcha is to have hard-to-read text to prevent the site from automated bots.

Looking forward to your reply.

**Comment by thestarsahil** [comment]
Screenshot 2023-08-01 105446
Screenshot 2023-08-01 105431

These two pic creating a difference , in look wise 
First pic you made

**Pull request merged**
