### PR TITLE
Privacy policy

### LINKED ISSUE #641: [FEATURE] : Design Privacy Page
**Is your feature request related to a problem? Please describe.**
@Counselllor

there are dummy footer link,
it doesn't redirect us to any page

image

**Describe the solution you'd like**

when user click privacy link from footer we can redirect them to `/privacy`

### PR DESCRIPTION
**Pull request by dhruv8433**
@Counselllor
@thestarsahil 

# Description
[FEATURE] : Design Privacy Page #641
Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

when user click on footer link `privacy` they will be redirected to `/privacy-policy`

## Fixes #641

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Previous 
Screenshot from 2024-05-30 09-04-51

After your update !
Screenshot from 2024-05-30 09-04-46
Screenshot from 2024-05-30 09-05-52

-> Problem occur Footer size increased and weight , Padding and margin effecting 
You just need to redirect to page , not to change the footer css

**Comment by dhruv8433** [comment]
@thestarsahil 

now you can check it 

image

**Comment by dhruv8433** [comment]
@thestarsahil 

please check this and merge it

**Comment by thestarsahil** [comment]
@dhruv8433 Same as previous 
Have a look into https://counsellor.social/ then compare it from your changes !

**Comment by thestarsahil** [comment]
Your Changes : 
Screenshot from 2024-05-30 21-02-22

Live : 
Screenshot from 2024-05-30 21-02-27

The Changes Effecting to Login Page , Forgot page and Signup page 
Look into Css property of your changes , might some directing to another properties

**Comment by dhruv8433** [comment]
@thestarsahil 

thank you for response i will check it and solve it

**Comment by dhruv8433** [comment]
@thestarsahil 

now you can check it and merge it
i resolve login form 

image

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly, please check this and merge it 
so i can design terms page

and if you need any kind of changes then please inform me

**Comment by thestarsahil** [comment]
> @thestarsahil
> 
> if you need any changes than please inform me please merge it and close #641

Changes won't Reflecting Work on !
Same issue occuring , the form area replaced and width stretch

**Comment by dhruv8433** [comment]
@thestarsahil 

you can check out this i already pull from upstream

image


and login's width is working properly in my code 

image


can you please give me access of this deployment  so i can check that

**Comment by dhruv8433** [comment]
@thestarsahil 

please give me access of this `privacy-policy` code developement
so i can check that and do as you say

**Comment by dhruv8433** [comment]
@thestarsahil 

Kindly please check it and merge it

If you face any kinf of issue please inform me or send me screenshot

I will do it quickly

**Comment by dhruv8433** [comment]
@thestarsahil 

i already build `terms` page kindly merge it so i can make another pr for that

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly please chel merge it 
i alredy completed terms page so i can create another pr for that

**Comment by thestarsahil** [comment]
@dhruv8433 Update the latest changes Pull the changes and try to push again , Let's see now

**Comment by dhruv8433** [comment]
@thestarsahil 

please check this and merge it 
i designed privacy page and login fixed as per design 

image

image

**Comment by thestarsahil** [comment]
@dhruv8433 
Why did you Modify the codebase of login page , even your work to navigate the page and create the privacy page !
Due to this it effect's
Best thing you gonna do , just undo the changes expect  privacy page !
Do the changes , push it Today i'll gonna merge it !

**Comment by dhruv8433** [comment]
@thestarsahil 

as you say, i revert the changed and now you can merge it
if you want any modification please inform me

**Comment by dhruv8433** [comment]
please merge this so i can make another pr for terms page
also add labels as per #641

**Comment by dhruv8433** [comment]
@thestarsahil 

Please check this and merge it
So i can make new pr for terms page

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly please check this and merge it 
if you need any modifications then please inform me

merge this so i can make new pr for terms page

**Comment by dhruv8433** [comment]
@thestarsahil 

as you said, i revert login page code
please check this and merge it

also `terms` page ready
please merge this so i can make new pr for that

**Comment by dhruv8433** [comment]
@thestarsahil 

as you said, i revert login page code
please check this and merge it

also `terms` page ready
please merge this so i can make new pr for that

**Review by thestarsahil — APPROVED** [review]
Working Good !

**Comment by thestarsahil** [comment]
I request to raise more PR containing level 3

**Pull request merged**
