### PR TITLE
installed tailwind

### LINKED ISSUE #718: Adding tailwind
**Is your feature request related to a problem? Please describe.**
I want to first try to replace the css by tailwind

### PR DESCRIPTION
**Pull request by ayush-848**
# Description

Applied tailwind to few pages

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil check

**Comment by thestarsahil** [comment]
/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:87
                throw new Error(
                      ^

Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:87:9)
    at Object.<anonymous> (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:96:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
  Require stack:
  - /workspaces/Counsellor-Web/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
      at Module._load (node:internal/modules/cjs/loader:986:27)
      at Module.require (node:internal/modules/cjs/loader:1233:19)
      at require (node:internal/modules/helpers:179:18)
      at requireWithFriendlyError (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:69:10)
      at Object.<anonymous> (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:96:76)
      at Module._compile (node:internal/modules/cjs/loader:1358:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
      at Module.load (node:internal/modules/cjs/loader:1208:32)
      at Module._load (node:internal/modules/cjs/loader:1024:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [ '/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js' ]
  }
}

Node.js v20.14.0

**Comment by ayush-848** [comment]
@thestarsahil The error is not because of my side. I haven't used the workspace folder. My working folder is src

**Comment by ayush-848** [comment]
@thestarsahil 
image
it works perfectly

**Comment by thestarsahil** [comment]
Its is not looking as expected ! Have to work more

**Comment by ayush-848** [comment]
@thestarsahil is it about the features you are telling??

**Comment by ayush-848** [comment]
@thestarsahil please see the conflicts, the resolve option isn't available to me

**Pull request closed without merging**
