### PR TITLE
Created New Job Modal 

### LINKED ISSUE #1058: Want to add create job modal to give the form for real time jobs
**Is your feature request related to a problem? Please describe.**
I want to add the modal or the form from which any organization can fill in the details required for that 

image

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have created a new Job Modal which takes all the necessary information from the organization so that user can know the exact information about the organization 

## Screenshots

https://github.com/user-attachments/assets/a3e0a75a-29b1-4af5-a991-4da7799a8e3c

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir please review this

**Comment by thestarsahil** [comment]
These cridentials are under Admin , not on public state as no only able to post jobs form
So we have to wait for it until admin

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Ok sir but please review these pr's as well #1112  and #1091

**Comment by thestarsahil** [comment]
Update this PR , pull the latest changes and push again

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Done Sir

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-22 13-43-28
Fix dark mode 

Is this not connected with firebase data?

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil Sir i have fixed the dark mode

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir please reivew this

**Comment by Ayushmaanagarwal1211** [comment]
So that i can start working on backend

**Comment by thestarsahil** [comment]
@Ayushmaanagarwal1211 We are shifting database to Azure 
Are you comfortable ?

**Comment by Ayushmaanagarwal1211** [comment]
Sir i can't previously worked on that but yes i will learn and then will attach it to database but for that i need that modal so that i can work on backend

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i have raised 4 pr's please review these

**Comment by thestarsahil** [comment]
Login page effected

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil ok sir i am checking

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir can you please share a small video or sc so that i can know where it is affecting in my laptop i am not able to see its affected part

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-26 19-28-06

See the login area remeber area , and scroll bar appeared

**Comment by thestarsahil** [comment]
Check the CSS part

**Comment by thestarsahil** [comment]
still happening

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil sir actually due to internet issue it was not pushed so i just pushed it again so please check or else you can also see screenshot

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir please review once again

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil Sir i fixed that already please see again

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir only 2 days are left i want to integrate the backend with that please merge it so that i will complete backed asap

**Pull request merged**
