### PR TITLE
Want to add Blog Reading Page #1003

### LINKED ISSUE #1003: Want to add Blog Reading Page
When User Clicks on Blog He Should Able to Read Full Blog Page
Something Like this 
Screenshot 2024-07-13 043058

image

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

Added Blog Reading Page and Added Markdown Support In Blogs

## Fixes #1003 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

https://github.com/user-attachments/assets/8b86c239-fc28-46b9-9673-8ddb902c312e

## Checklist

- [X ] Tests have been added or updated to cover the changes
- [ X] Documentation has been updated to reflect the changes
- [ X] Code follows the established coding style guidelines
- [ X] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Update you branch now

**Comment by nishant0708** [comment]
hey @thestarsahil branch updated with latest changes

**Comment by thestarsahil** [comment]
Not working and even the previous changes also not working 
Save button not working

Screenshot from 2024-07-14 19-38-52

**Comment by nishant0708** [comment]
Yaa actually I checked it's all about firebase rules  it will be fixed after that automatically wait

**Pull request merged**
