### PR TITLE
Added Delete BLog Functionality 

### LINKED ISSUE #1087: Want to add Backend Integration  for delete the blog
**Is your feature request related to a problem? Please describe.**
I want to add the delete blog feature so that user can delete the blog

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have created  a blog functionlaity where user can delete the blogs created by him
Delete option will only be display to that user who created that blog 

## Screenshots

https://github.com/user-attachments/assets/5627fa8a-e86f-429f-949a-84c7dd007b09

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Icon should inside the blog page near the edit section

**Comment by Ayushmaanagarwal1211** [comment]
Done sir

**Comment by Ayushmaanagarwal1211** [comment]
image

**Comment by thestarsahil** [comment]
Pull the latest changes and push again

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Done Please check

**Comment by Ayushmaanagarwal1211** [comment]
DOne Sir

**Review by thestarsahil — APPROVED** [review]

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir please also add labels

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir during the conflict solving i did a small mistake that everyone can see the delete icon on the other blog that doesn't belongs to him so i fixed that you can merge and please not give any level on that pr 
#1126

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir you didn't assigned level please assign level

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil Sir you didn't assigned level please assign level

**Pull request merged**
