### PR TITLE
Terms

### LINKED ISSUE #643: [Feature] : Design Terms Page
**Is your feature request related to a problem? Please describe.**
@Counselllor

**Describe the solution you'd like**
we can design Trems and condition page for this website

when user click on footer `Terms` link, they will redirect to `/terms-condtions` path
and it will look like 

image

please assign it to me, i would like to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

@thestarsahil 

[Feature] : Design Terms Page #643

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #643 (issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly please check this and merge it

**Comment by thestarsahil** [comment]
/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:87
                throw new Error(
                      ^

Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:87:9)
    at Object.<anonymous> (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:96:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
  Require stack:
  - /workspaces/Counsellor-Web/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
      at Module._load (node:internal/modules/cjs/loader:986:27)
      at Module.require (node:internal/modules/cjs/loader:1233:19)
      at require (node:internal/modules/helpers:179:18)
      at requireWithFriendlyError (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:69:10)
      at Object.<anonymous> (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:96:76)
      at Module._compile (node:internal/modules/cjs/loader:1358:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
      at Module.load (node:internal/modules/cjs/loader:1208:32)
      at Module._load (node:internal/modules/cjs/loader:1024:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [ '/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js' ]
  }
}

Node.js v20.14.0

Still again >?

**Comment by thestarsahil** [comment]
update the lastest branch in your system then push

**Comment by dhruv8433** [comment]
ok

**Comment by dhruv8433** [comment]
@thestarsahil 

now you can merge this
`Build Success` 

i removed node modules, package.json and pull from master

image

**Comment by thestarsahil** [comment]
packjson conflict !
resolve it

**Comment by dhruv8433** [comment]
@thestarsahil 

now you can merge it

**Comment by dhruv8433** [comment]
@thestarsahil 

please  check this and merge it

**Comment by thestarsahil** [comment]
Not working try again

**Comment by dhruv8433** [comment]
@thestarsahil 

can you please send me screenshort of deployment error ?

**Comment by thestarsahil** [comment]
Screenshot from 2024-06-22 18-10-58

**Comment by dhruv8433** [comment]
@thestarsahil 

i pulled from upstream and it open perfectly in my browser
can you please try `npm i` again after removing both package-lock.json and node_modules directory in your directory

because website open perfectly in my browseer

image

image

**Comment by thestarsahil** [comment]
Do one thing just pull the latest change and  create a new PR , then push all !

**Pull request closed without merging**
