### PR TITLE
Added icons in profile cards

### LINKED ISSUE #848: To add social icons to the profile cards that on click will redirect
image

Out of the three social site options, the user can add 0-3 any number of social site and there will be the icons displayed on his profile card that after clicking will take us to his/her socials.

### PR DESCRIPTION
**Pull request by ayush-848**
# Description
Added icons in profile cards

## Screenshots
image
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil please if it is ok, then merge it before other PRs

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-06 21-24-15

Overlapping occur and no cancel button on edit profile pop message when adding the link

**Comment by ayush-848** [comment]
> Screenshot from 2024-07-06 21-24-15
> 
> Overlapping occur and no cancel button on edit profile pop message when adding the link

Thats very strange, it didn't occur when i was making it.
let me check

**Comment by ayush-848** [comment]
@thestarsahil can you show me the console message

**Comment by ayush-848** [comment]
@thestarsahil 
image
see now

**Pull request closed without merging**
