### PR TITLE
I have made a dashboard page

### LINKED ISSUE #155: I will be creating landing page
## Issue

I will be creating the first page of the website

## Screenshot

Please assign me this task so that I can create the above mentioned page 

I am in GSSOC'23

### PR DESCRIPTION
**Pull request by Swapnil-Singh-99**
# Description

I have made the dashboard page of the website which user will be able to nagivate on after signing in to the website

route -> /dashboard

## Fixes #155 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by Swapnil-Singh-99** [comment]
@thestarsahil Please review and merge this

**Comment by Swapnil-Singh-99** [comment]
@thestarsahil ?

**Comment by thestarsahil** [comment]
we are looking around code 
Have patience !

**Comment by thestarsahil** [comment]
@Swapnil-Singh-99  drop your mail id !
I need have to talk personally with you

**Comment by Swapnil-Singh-99** [comment]
swapnilskumars99@gmail.com

**Comment by Swapnil-Singh-99** [comment]
> swapnilskumar99@gmail.com

swapnilskumar99@gmail.com

@thestarsahil 
Here is the correct mail ID

**Comment by Swapnil-Singh-99** [comment]
@thestarsahil Please review

**Comment by Swapnil-Singh-99** [comment]
@thestarsahil I have made the changes to the code

**Comment by Swapnil-Singh-99** [comment]
@thestarsahil The code is ready.
Please review it
The environment variables part has been fixed

You just need to add env variables value and it will start working

**Comment by Swapnil-Singh-99** [comment]
I have a new PR with all the updates >
Kindly Check
https://github.com/Counselllor/Counsellor-Web/pull/264

**Pull request closed without merging**
