### PR TITLE
Enhanced Contact us page

### LINKED ISSUE #849: Want to enhance join us page and Fix COntact us page design
**Is your feature request related to a problem? Please describe.**
I want to Enhance the join us page by following ways : 
1. By doing proper formatting
2. by giving proper margin it is looking messy right now 
3. by adding some colors to the heading 
4. by adding navbar 
5. Creating the dark mode for the website 

Also want to fix design issue in contact page  the message title and button is overlapping with the input field
**Describe the solution you'd like**
I want to do all these things

https://github.com/Counselllor/Counsellor-Web/assets/118350936/2987a977-c488-4b0f-8fba-fbad813e1dfe

Screenshot 2024-07-03 213224

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have enanced the contact us page in following ways : 
- Added a gradient button 
- Added dark mode for contact page 
- Added border
- fix the positioning issues with overlappign of message and textarea

## Screenshots

https://github.com/Counselllor/Counsellor-Web/assets/118350936/c3805181-b846-4c50-9463-48e3a7f9e04d

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-07 20-25-52

I want this colro pattern and button as same as search button

**Comment by Ayushmaanagarwal1211** [comment]
Ok doing

**Comment by thestarsahil** [comment]
Try , if work then okay

**Comment by Ayushmaanagarwal1211** [comment]
> Try , if work then okay

ok

**Comment by Ayushmaanagarwal1211** [comment]
image
@thestarsahil  i created the button but input fileds are looking like this so should i revert it or its fine

**Comment by thestarsahil** [comment]
Do one thing  apply whole background to white and text color should same as color of send color

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil   sir like that i chanegd the whole background to white and text color also white same as send color
image

**Comment by thestarsahil** [comment]
come on vc i'll tell u

**Comment by Ayushmaanagarwal1211** [comment]
Ok joining

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  I joined

**Comment by thestarsahil** [comment]
@Ayushmaanagarwal1211 Made it ?

**Comment by Ayushmaanagarwal1211** [comment]
> @Ayushmaanagarwal1211 Made it ?

YEs sir

**Comment by Ayushmaanagarwal1211** [comment]
> > @Ayushmaanagarwal1211 Made it ?
> 
> YEs sir

I updated please check the video

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i created a new pr for this

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  #939  Please check this

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Please check is this working or not 
And i am starting working on creating a contact form as you given above

**Comment by thestarsahil** [comment]
Effecting to whole website not working

**Comment by thestarsahil** [comment]
Closed this PR

**Pull request closed without merging**
