### PR TITLE
Solved Issue308

### LINKED ISSUE #308: In Signup page there is only one show password field in password but not in confirm password [GSsoc'23]
**Describe the bug**
As you can see that there is only one eye button/password shower which handles both the password and confirm password field.
It is not a convenient way to show password both password and confirm password must have its own password shower.

I will add that functionality to confirm password field and will make it more user friendly!!

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome

Active contributor [GSsoc'23]

### PR DESCRIPTION
**Pull request by Monilprajapati**
# Description

Solved that password show field for confirm password and made it more user friendly

## Screenshots
image

### CODE REVIEW

**Comment by thestarsahil** [comment]
https://github.com/Counselllor/Counsellor-Web/assets/84167034/7daa8ccc-eb20-4361-a1c3-1cb2b1d92cab

Solve this Bug

**Comment by Monilprajapati** [comment]
Resolved that Text selection Issue Now you can re-check it but do not double click to toggle as it select text which is normal behavior of browser.

Preview:

https://github.com/Counselllor/Counsellor-Web/assets/99136041/28572536-f27d-4f3c-9ee7-13446c61d168

**Comment by Monilprajapati** [comment]
I created one another issue for enhancing the footer:: Issue#327 
Assign me that issue I will complete it by Tomorrow :)

**Comment by thestarsahil** [comment]
Test Cases failed Try once Again with all test cases passed

**Comment by Monilprajapati** [comment]
Ok now it's done

**Comment by thestarsahil** [comment]
Again 
Test Cases failed Try once Again with all test cases passed


12:13:11 PM: [vite:esbuild] Transform failed with 1 error:
12:13:11 PM: /opt/build/repo/src/components/SignUp/SignUp.jsx:84:2: ERROR: Unexpected }
12:13:11 PM: file: /opt/build/repo/src/components/SignUp/SignUp.jsx:84:2
12:13:11 PM: 
12:13:11 PM: Unexpected }
12:13:11 PM: 82 |        return { ...prev, ...errObj };
12:13:11 PM: 83 |      });
12:13:11 PM: 84 |    };
12:13:11 PM:    |    ^
12:13:11 PM: 85 |
12:13:11 PM: 86 |    function writeUserData(userId, email, userInfo) {

**Comment by Monilprajapati** [comment]
i have created new PR for it please check it out #340

**Pull request closed without merging**
