### PR TITLE
Improved Dark mode color scheme 

### LINKED ISSUE #779: Improving the color scheme in Dark Mode
**Is your feature request related to a problem? Please describe.**
Improving the color scheme in Dark Mode for better visual appeal. The current color code looks quite dull because of which the user might ignore some functionalities 

image

The current blue color is very dark which does not complement with the dark mode 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Amruta7203**
# Description

Improvised the Dark mode color scheme:
1. Change the font color to bright blue to highlight the components
2. Changed the text color in college location to white for better visibility 
3. Created seperate style for dark mode in index.css using css variables 

## Fixes #779 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

before:
image

after:
image

before:
image

after:
image

## Checklist

- [x ] Tests have been added or updated to cover the changes
- [x ] Documentation has been updated to reflect the changes
- [x ] Code follows the established coding style guidelines
- [x ] All tests are passing

### CODE REVIEW

**Comment by Amruta7203** [comment]
@thestarsahil I have brightened the color and added the dark mode variables. I have also changed the text color to white in dark background for better visibility as shown in the screenshots above. If there are any other requirements then you can suggest.

**Comment by Amruta7203** [comment]
@thestarsahil Suggest some requirements from your side..

**Comment by thestarsahil** [comment]
Did you pull the latest changes right now ?

**Comment by Amruta7203** [comment]
> Did you pull the latest changes right now ?

Yes

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-06 12-55-49
Fix this

**Comment by Amruta7203** [comment]
@thestarsahil I am not Able to see any error at my side:
image

image

**Comment by thestarsahil** [comment]
why your navbar is not updated ?

**Comment by Amruta7203** [comment]
I resolved the merge conflicts and pulled the recent changes. It looks like this now:
image

**Pull request closed without merging**
