### PR TITLE
Student detail page

### LINKED ISSUE #860: [Feat] : Redesign college detailed page
**Is your feature request related to a problem? Please describe.**

@thestarsahil 

we can redesign college deatiled page

image

something like this

image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

[Feat] : Redesign college detailed page #860
@thestarsahil 

- when we click on particular student we got detailed section of that student

## Fixes #860(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

https://github.com/user-attachments/assets/133635ba-f949-4562-a2e9-f8d2e0ff2e78

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly check this and merge it

**Comment by dhruv8433** [comment]
if you need any modifications please inform me

responsive

image

**Comment by thestarsahil** [comment]
Fix the gap bw navabar and college section(7)

Fix this

**Comment by dhruv8433** [comment]
@thestarsahil 

as you said i updated my code 
please review it

image

**Comment by thestarsahil** [comment]
pull the latest change , its your turn now

**Comment by thestarsahil** [comment]
and slight reduce the font size

**Comment by dhruv8433** [comment]
@thestarsahil 

i update font size and make it bit smaller and fetched upstream 
now you can merge it

image

**Comment by dhruv8433** [comment]
@thestarsahil 

when you become free please check this and merge it

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
