### PR TITLE
[Feat:] Update The Navbar in below tablet(768px) view

### PR DESCRIPTION
**Pull request by SrinivasDevolper**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

When the user clicks the nav item of the navbar, the navbar closes.

## Fixes #(issue_no) :- #687

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

**Actual Behaviour:-**

https://github.com/Counselllor/Counsellor-Web/assets/121508628/a3d927ae-9555-4e82-9d3f-f1b518695237

**Extecpeted Behaviour:-**

https://github.com/Counselllor/Counsellor-Web/assets/121508628/5ac48943-30b9-4552-840a-7b5e03b75fcf

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [X] Code follows the established coding style guidelines
- [X] All tests are passing

**If it's not good, please assign me again I will do it better**

### CODE REVIEW

**Comment by thestarsahil** [comment]
resolve conflict i am merging this

**Comment by thestarsahil** [comment]
Screenshot from 2024-06-28 19-38-22
Screenshot from 2024-06-28 19-38-38

Resolve this

**Comment by SrinivasDevolper** [comment]
ok

**Comment by SrinivasDevolper** [comment]
Do not copy my code to add in this PR. Merge my code, I'll make a pull request if you agree for that.

**Comment by SrinivasDevolper** [comment]
**Actual Behaviour**

https://github.com/Counselllor/Counsellor-Web/assets/121508628/aaa9da12-7190-43db-93ff-276d659ee4dd

**Expected Behaviour**


https://github.com/Counselllor/Counsellor-Web/assets/121508628/c208b52a-840e-40ff-9622-f4c8eb44e66d

**Pull request closed without merging**
