### PR TITLE
Added the Career Support page

### LINKED ISSUE #794: Creating a career support page
**Is your feature request related to a problem? Please describe.**
I want to add a career support page where user will have multiple options to look forward.

### PR DESCRIPTION
**Pull request by ayush-848**
# Description

Added the Career Support page

## Screenshots
image
image
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil check this

**Comment by thestarsahil** [comment]
Working Fine but fil the color according to project theme colors !

**Comment by ayush-848** [comment]
> Working Fine but fil the color according to project theme colors !

Ohhh ok, the deep bluish colour??

**Comment by ayush-848** [comment]
@thestarsahil 
image

check

**Review by thestarsahil — APPROVED** [review]
Working good !

**Pull request merged**
