### PR TITLE
Want To Make Profile Page Dynamic #908

### LINKED ISSUE #908: Want To Make Profile Page Dynamic
**Is your feature request related to a problem? Please describe.**
Currently profile page is not dynamic i want to make it dynamic

**Describe the solution you'd like**
It Should Show The Logged In User Details and Will Fix some Ui bugs of this page as well

**Describe alternatives you've considered**

**Additional context**

image

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #908 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

Screenshot 2024-07-13 115309
Screenshot 2024-07-13 115318
Now Data is Coming From Backend

## Checklist

- [X ] Tests have been added or updated to cover the changes
- [X ] Documentation has been updated to reflect the changes
- [ x] Code follows the established coding style guidelines
- [X ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-13 13-58-56

Why this set name is default set ?

**Comment by nishant0708** [comment]
hey @thestarsahil actually the the username in profile page is set using usestate so i was just trying to set there.. we can also set this info outside useEffect as well

**Comment by nishant0708** [comment]
but if we set there as well it should not be a problem

**Comment by thestarsahil** [comment]
You can set a placeholder effect

**Comment by thestarsahil** [comment]
Hiye can you setup the things , when user create new id , then the automatically placeholder name change to username logged in

**Comment by nishant0708** [comment]
okay i will look into it

**Comment by nishant0708** [comment]
hey @thestarsahil it should be fine now added placeholder effect as well
Screenshot 2024-07-14 230154

**Pull request merged**
