### PR TITLE
Fix performance issues

### PR DESCRIPTION
**Pull request by Hrishita-Paul**
# Description
Removed unnecessary imports and duplicate imports, unused variables and props using arrow functions.
## Checklist

- [yes ] Code follows the established coding style guidelines
- [ yes] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Pull the latest changes and then push again 
packages and set of line updated

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-22 12-45-13

Haven't yet

**Comment by Hrishita-Paul** [comment]
@thestarsahil  kindly review it now

**Comment by thestarsahil** [comment]
Working on

**Pull request closed without merging**
