### PR TITLE
Added the import data button

### LINKED ISSUE #1028: Adding option to Dynamically updating the profile by adding a import data option
The user can import his profile details and the profile card will update as per it

### PR DESCRIPTION
**Pull request by ayush-848**
# Description
Added the import data option for user to add pre-existing data

## Screenshots

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil check it

**Comment by thestarsahil** [comment]
Why the user want need to import data ?

**Comment by ayush-848** [comment]
> Why the user want need to import data ?

Well here the profile data is not connected to his firebase
i.e, not synced with account

so if he try to open in another server then his data will be reinstated

**Comment by ayush-848** [comment]
@thestarsahil When you will introduce the proper backend system then this featured can be replaced by mongodb's data
and also it will be synced with his google account

**Comment by thestarsahil** [comment]
Connect with firebase 
no need to import , its getting too much hetic for user

**Comment by ayush-848** [comment]
> Connect with firebase no need to import , its getting too much hetic for user

can it be connected without mongodb?

**Comment by thestarsahil** [comment]
It can be work for firebase also 
Right ?

**Comment by ayush-848** [comment]
> It can be work for firebase also Right ?

I am not sure.
Let me try and see.

**Comment by ayush-848** [comment]
@thestarsahil Thank you for this great suggestion. It works. 
I do not knew it can be done this way.

Thanks a lot.

**Comment by ayush-848** [comment]
@thestarsahil I will remove the 'import' option and will add data to firebase
Let me commit

**Comment by ayush-848** [comment]
@thestarsahil done. Please check it now

**Comment by thestarsahil** [comment]
show how the data working

**Comment by ayush-848** [comment]
> show how the data working

image
image
image
@thestarsahil

**Comment by ayush-848** [comment]
@thestarsahil I have removed the unnecessary console.log statements now
coz they were only for you to see the data working

**Comment by thestarsahil** [comment]
Let's connect on vc to discuss in further more

**Comment by ayush-848** [comment]
> Let's connect on vc to discuss in further more

Sure when??

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-15 01-29-15

Work on this :
Default phone can't be set without modifying profile section 
Default College can't be set 
Default year can't be set

**Comment by ayush-848** [comment]
@thestarsahil i have seen #1052 of @nishant0708 
I think my  way would generate some kind of error
But @nishant0708 has done it properly using firebase

I am not so familiar with backend stuff

**Comment by ayush-848** [comment]
@nishant0708 my approach was to set it to local storage and then retrieve it if user not connected or update if user is connected in firebase.

Can you tell me more about the approach u did, coz I think that my approach's main problem is the setting data to local storage??

**Comment by nishant0708** [comment]
Umm @ayush-848 see what I am doing is setting data in users data and updating it whenever user click on edit it's simple if you know database just remember in firebase get is get post is set and ref stands for reference

**Comment by ayush-848** [comment]
> Umm @ayush-848 see what I am doing is setting data in users data and updating it whenever user click on edit it's simple if you know database just remember in firebase get is get post is set and ref stands for reference

Won't getting mongodb a better choice, or can firebase hold large user data??

**Comment by nishant0708** [comment]
> > Umm @ayush-848 see what I am doing is setting data in users data and updating it whenever user click on edit it's simple if you know database just remember in firebase get is get post is set and ref stands for reference
> 
> Won't getting mongodb a better choice, or can firebase hold large user data??

Brother valorant and twitch is made on firebase so no there should not be any issues I guess

**Comment by nishant0708** [comment]
> > Umm @ayush-848 see what I am doing is setting data in users data and updating it whenever user click on edit it's simple if you know database just remember in firebase get is get post is set and ref stands for reference
> 
> Won't getting mongodb a better choice, or can firebase hold large user data??

And compare to mongodb firebase has faster retrieval and storage access of data

**Comment by ayush-848** [comment]
> > > Umm @ayush-848 see what I am doing is setting data in users data and updating it whenever user click on edit it's simple if you know database just remember in firebase get is get post is set and ref stands for reference
> > 
> > 
> > Won't getting mongodb a better choice, or can firebase hold large user data??
> 
> Brother valorant and twitch is made on firebase so no there should not be any issues I guess

Oh, didn't know that.

**Comment by ayush-848** [comment]
> > > Umm @ayush-848 see what I am doing is setting data in users data and updating it whenever user click on edit it's simple if you know database just remember in firebase get is get post is set and ref stands for reference
> > 
> > 
> > Won't getting mongodb a better choice, or can firebase hold large user data??
> 
> And compare to mongodb firebase has faster retrieval and storage access of data

Oh, ok.
Thanks @nishant0708 bhai for it.
I did get to learn something new.

**Comment by nishant0708** [comment]
> > > > Umm @ayush-848 see what I am doing is setting data in users data and updating it whenever user click on edit it's simple if you know database just remember in firebase get is get post is set and ref stands for reference
> > > 
> > > 
> > > Won't getting mongodb a better choice, or can firebase hold large user data??
> > 
> > 
> > And compare to mongodb firebase has faster retrieval and storage access of data
> 
> Oh, ok. Thanks @nishant0708 bhai for it. I did get to learn something new.

Arey no issues bhai if you need any help just dm me 👍

**Pull request closed without merging**
