### PR TITLE
[UPDATED] Enhanced Login Page UI

### LINKED ISSUE #70: [UPDATE] Enhancing the UI of Login page
Hello, I am Mahima Churi, a proud contributor of GSSoc ' 23.

I would like to work on this project, by enhancing the UI of the Login page.

Things I would be working on:
📌Linking Login and Sign Up page so that the User can be directly directed to the login page
📌Enhancing the UI of the Login Page
📌Making the Login with social icons clickable

If you think it is legit then do assign me the issue under GSSoC '23 with the level of the PR as well

### PR DESCRIPTION
**Pull request by Mahitej28**
# Description

- Enhanced the UI of login Page
- Changed color of `form-container`
- Made Social Icons `Clickable`

## Fixes #70 

- This PR is created in reference to Issue No.: #70

## Screenshots

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by omkarguravv** [comment]
@Mahitej28  Wow, I must say, you've done an outstanding job redesigning the page! The improvements you've made are truly remarkable. The layout is now much more visually appealing and user-friendly. 
But we have redesigned the login and signup page with both mobile as well as desktop view.
Can you check out the new design once?

**Comment by Mahitej28** [comment]
@omkarguravv you would have let me know once so that I would had worked accordingly

**Comment by omkarguravv** [comment]
@Mahitej28  Checkout #145 

Make Sure to join Discord server and Slack Channel for latest updates.

**Comment by Mahitej28** [comment]
Ok so what should I do now further ?

**Comment by omkarguravv** [comment]
Similar issue is being raised #145 you can work on it , no further changes will be done in new design template you can work on it.

**Comment by Mahitej28** [comment]
Ok

**Pull request closed without merging**
