### PR TITLE
Go back to Home button is redirecting to login page even when user is logged in #1251

### LINKED ISSUE #1251: Go back to Home button is redirecting to login page even when user is logged in
image

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #1251 

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [ X] Tests have been added or updated to cover the changes
- [ X] Documentation has been updated to reflect the changes
- [X ] Code follows the established coding style guidelines
- [X ] All tests are passing

### CODE REVIEW

**Comment by nishant0708** [comment]
Hey @thestarsahil i have Fixed Error page darkmode as well in this pr 
image
so please assign it level 2

**Comment by thestarsahil** [comment]
Checking ✔️

**Review by thestarsahil — APPROVED** [review]

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-26 20-50-02

Work for this

**Comment by nishant0708** [comment]
Okay @thestarsahil

**Pull request merged**
