### PR TITLE
Enhanced the joinus page

### LINKED ISSUE #1268: Parts of join us page are not readable in light mode
Parts of join us page are not readable in light mode

image
image

### PR DESCRIPTION
**Pull request by ayush-848**
# Description
Enhanced the joinus page

## Screenshots
image
image
image
image
image
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by ayush-848** [comment]
@thestarsahil now check

**Comment by ayush-848** [comment]
@thestarsahil also what were the other pages you told me to work on????

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-28 20-42-18

This kind of layout i want on 

Screenshot from 2024-07-28 20-43-00

**Comment by ayush-848** [comment]
image
image

@thestarsahil please check

**Comment by ayush-848** [comment]
@thestarsahil can you **upgrade the issue** level.
This box sizing were really hard to match

**Pull request merged**
