### PR TITLE
Want to Write Backend Of Contact Page #980

### LINKED ISSUE #980: Want to Write Backend Of Contact Page
**Is your feature request related to a problem? Please describe.**
In This i want when user submits his message should get stored in realtime database In Queries Section

**Describe the solution you'd like**
image

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

Career Queries Data Getting Stored in Database And Made emailjs Service as well to Send Acknowledgment Mail

## Fixes #980 

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [ X] Tests have been added or updated to cover the changes
- [X ] Documentation has been updated to reflect the changes
- [X ] Code follows the established coding style guidelines
- [ X] All tests are passing

### CODE REVIEW

**Comment by nishant0708** [comment]
Hey @thestarsahil to make Email Js Work you need to add your Credentials here
Screenshot 2024-07-30 120503
https://www.youtube.com/watch?v=qxWDVRyc95E refer to this Video For setting up Credentials if required

**Comment by nishant0708** [comment]
And Please Assign it Level 2. Not Level 3

**Comment by thestarsahil** [comment]
U had pushed your Auth cred. remove that

**Comment by nishant0708** [comment]
hey @thestarsahil done

**Review by thestarsahil — APPROVED** [review]

**Pull request merged**
