### PR TITLE
Enhanced Blog page

### LINKED ISSUE #828: Enhancing a blogs page
**Is your feature request related to a problem? Please describe.**
I want to enhance the blogs page 

**Describe the solution you'd like**
I will make a dark mode for that .
I will add shadows for that
Now the card is looking messy so i will fix that 
Add footer to that 
Screenshot 2024-07-02 193818

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I have enhanced the blogs page by following ways :- 
1. Added Navbar to it 
2. Added different color for text
3. Implemented for dark mode
4. Made it more responsive 
5. Add box shadow
6. Added hover effect
7. added Fade up animation
8. Added Amazing stylish Read more button
9. Changed the color of heading in the card 

## Screenshots

https://github.com/Counselllor/Counsellor-Web/assets/118350936/09137150-130e-498e-b0b7-d8822d0eec34

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
Color them should be same , not more extra effect need to put on 
Work on that !

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  can you please explain a little bit more like what exactly i have to do

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  can you please explain a little bit more like what exactly i have to do

**Comment by thestarsahil** [comment]
As you can see in readme file , the elements we designed that should you have to make it !

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Yes actually in the read me file i am not seeing the blogs page Can you please tell me where it is

**Comment by thestarsahil** [comment]
@Ayushmaanagarwal1211 I think the page design is fine , you can do : Fix the marging , padding , context alignment 
Do that all !

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Please review i reverted the text so now it have navbar , footer , hovering animation , Popup animation ad the changed design of read more button

**Comment by thestarsahil** [comment]
Screenshot from 2024-07-05 21-53-42
As you can see the context is blur when cursor move on it !

**Comment by Ayushmaanagarwal1211** [comment]
Ok i am removing the shadow

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  fixed

**Review by thestarsahil — APPROVED** [review]
Box Shadow have to remove !

**Comment by Ayushmaanagarwal1211** [comment]
> Box Shadow have to remove !

Ok i will remove it in next pr

**Pull request merged**
