### PR TITLE
Added Dark Mode Toggle

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #586 

image

@thestarsahil I changed the color

### CODE REVIEW

**Comment by thestarsahil** [comment]
/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:87
                throw new Error(
                      ^

Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:87:9)
    at Object.<anonymous> (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:96:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
  Require stack:
  - /workspaces/Counsellor-Web/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
      at Module._load (node:internal/modules/cjs/loader:986:27)
      at Module.require (node:internal/modules/cjs/loader:1233:19)
      at require (node:internal/modules/helpers:179:18)
      at requireWithFriendlyError (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:69:10)
      at Object.<anonymous> (/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js:96:76)
      at Module._compile (node:internal/modules/cjs/loader:1358:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
      at Module.load (node:internal/modules/cjs/loader:1208:32)
      at Module._load (node:internal/modules/cjs/loader:1024:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [ '/workspaces/Counsellor-Web/node_modules/rollup/dist/native.js' ]
  }
}

Node.js v20.14.0

**Comment by Hemashree21** [comment]
@thestarsahil I resolved the conflicts can you please check once now? In my system it's running correctly

**Comment by thestarsahil** [comment]
Screenshot from 2024-06-16 20-26-01

This module containig problem as i can see that lastest changes didn't pull

**Comment by Hemashree21** [comment]
@thestarsahil I updated the branch

**Comment by thestarsahil** [comment]
Screenshot from 2024-06-17 10-48-22

This is Effecting to toaster notification , you also have to work on this and implement the dark mode in every section of page , not only just in dasboard page

**Comment by Hemashree21** [comment]
image

@thestarsahil I implemented the dark mode in the Login and Signup page as well but since there is an image, I couldn't change the background properly so I used invert filter for the dark mode

**Comment by thestarsahil** [comment]
@Hemashree21 Dear , its not working on login and signup page 
Don't work on images we will see later on and the color should remain according to theme color !

**Pull request closed without merging**
