### PR TITLE
Scroll To Top widget improved

### LINKED ISSUE #580: [Enhance] scrolltotop widget
i wish to improve the UI of the scrolltotop widget

### PR DESCRIPTION
**Pull request by sau-mili**
# Description

improved the scroll to top widget
## Fixes #580 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots
Screenshot 2024-05-31 013035
ignore high contrast

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Review by thestarsahil — APPROVED** [review]
Working Good !

**Comment by thestarsahil** [comment]
One more updation , update the navbar property on all other pages with same properties and working same as dashboard page !

**Comment by sau-mili** [comment]
Will do that tonight!

**Comment by thestarsahil** [comment]
> Will do that tonight!

Sorry for the late reply did you made it ?

**Comment by sau-mili** [comment]
Which one? The navbar? I am on it right now

**Comment by thestarsahil** [comment]
yes !

**Pull request merged**
