### PR TITLE
Feat: 404 notfound page redesigned

### LINKED ISSUE #811: Feat: redesign the error page
**Is your feature request related to a problem? Please describe.**
image
**Describe the solution you'd like**

we can ad some image or gifs to make it more attractive
**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
# Description

404 notfound page redesigned

## Fixes #811 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots
image

responsive
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
hi @thestarsahil review the PR

**Comment by thestarsahil** [comment]
Its not working good in website look for more simple or you can choice another problem statements !

**Comment by RamakrushnaBiswal** [comment]
Screenshot_2024-07-02-18-56-54-18_40deb401b9ffe8e1df2f1cc5ba480b12
Hi @thestarsahil what about this

**Comment by thestarsahil** [comment]
Ya that's a error page which reflects you are in wrong page

**Comment by thestarsahil** [comment]
May be you could try to solve college pages css

**Pull request closed without merging**
