### PR TITLE
feat: Added About Page

### LINKED ISSUE #221: About Page
**Is your feature request related to a problem? Please describe.**
Adding details in the about page and making it properly.
**Describe the solution you'd like**
We could add a description about what the app is and put it on the homepage itself to make it easier.
**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by JiyaGupta-cs**
# Description

I have Added About Page as per the website's current style

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
The Ui of about page not good as expected ! 
The mistake you did , you created a about page on navbar instead the about page is already there in footer page , so mention the path from footer page and cancel down the about page from navbar

**Comment by JiyaGupta-cs** [comment]
@thestarsahil
I have updated the About Page UI
Made it look attractive
and I have also added animations to it

**Comment by thestarsahil** [comment]
Nice Work  ! but about page have to open in every section either in any page 
You mentioned to open when dashboard open , please change the navigation and this also conflicting with other pages 
Fix it also

**Comment by JiyaGupta-cs** [comment]
@thestarsahil 
I will do that once the number of page increases since the website has only dashboard and about page till now
Later I will make a navbar component which could be imported in all
Please merge it for now
I need points for my IWOC

**Comment by thestarsahil** [comment]
Screenshot 2024-01-31 095628
Screenshot 2024-01-31 095754

First pic is original ones but after adding the about page its effect in all overall pages ( second pic )

**Comment by JiyaGupta-cs** [comment]
I'll fix it in my next PR @thestarsahil

**Comment by JiyaGupta-cs** [comment]
@thestarsahil I have added About Page in footer component so it will be automatically imported wherever Footer is imported
Please merge it

**Comment by JiyaGupta-cs** [comment]
@thestarsahil 
I have made the changes as you said
Kindly review it

**Comment by thestarsahil** [comment]
Can you check the changes done by some other contributor made for about page

**Comment by JiyaGupta-cs** [comment]
@thestarsahil I have already corrected what you said

**Comment by thestarsahil** [comment]
The page added sucessfully but the code having problem which effect other , but we sort it later 
Now I am merging

**Comment by JiyaGupta-cs** [comment]
@thestarsahil Can I start working for Contact page now?

**Comment by thestarsahil** [comment]
Sure and please make sure that contact page not to conflict with other pages

**Pull request merged**
