### PR TITLE
Student Achievements

### LINKED ISSUE #1185: [Feat] : Add Detailed about student achievements
**Is your feature request related to a problem? Please describe.**

@thestarsahil 

when we click on achievements we can display particular student's achievements in popup

image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by dhruv8433**
# Description

@thestarsahil 

[Feat] : Add Detailed about student achievements #1185

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #1185(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

https://github.com/user-attachments/assets/2d3ca412-844d-45a7-bc1f-f2e041023b8f

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by dhruv8433** [comment]
@thestarsahil 

kindly please check this and merge it

**Comment by thestarsahil** [comment]
@dhruv8433 Its not working as expected as student having alot more data !
So we need to create a page of students and all information show inside that student page 
Can you do that 
It will change to level 3

**Comment by dhruv8433** [comment]
@thestarsahil 

Sure it will complete till today night

**Comment by dhruv8433** [comment]
@thestarsahil ,

please tell me if you need any modifications

image

image

**Comment by dhruv8433** [comment]
@thestarsahil 

when you become free, please review it and inform me if you need any kind of modifications

**Comment by dhruv8433** [comment]
@thestarsahil 

i updated code and now when we click on student 

image

it will redirected to `/student/:id/:name/achievements` page

image

**Comment by dhruv8433** [comment]
@thestarsahil 

please check this too
in this pr, i completed the achievements part of the student section

https://github.com/user-attachments/assets/a37f3289-12d8-46b1-a0ff-96761ef4dc30

**Comment by dhruv8433** [comment]
image

**Comment by dhruv8433** [comment]
@thestarsahil 

please add level

**Comment by dhruv8433** [comment]
@thestarsahil 

If you think my code is good enough to get `level 3` please add it

**Comment by dhruv8433** [comment]
@thestarsahil

If you think my code is good enough to get level 3 please add it

**Comment by dhruv8433** [comment]
@thestarsahil sir,

please add level in this pr

**Pull request merged**
