### PR TITLE
[Feat:] Add text No Search Results Found of searchbar

### PR DESCRIPTION
**Pull request by SrinivasDevolper**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

To enhance the search bar experience Added the text No Search Results Found on the search bar and  Added a wrong icon button near the search bar

## Fixes #(issue_no) :  #689

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

Uploading no res co - Made with Clipchamp.mp4…

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

**If it's not good, please assign me again I will do it better**

### CODE REVIEW

**Comment by thestarsahil** [comment]
resolve conflict and update the lastest changes and then push again

**Comment by thestarsahil** [comment]
Have you run this changes on localhost machine as per mine machine it is not running and apperaing too much errors need to be fix

**Comment by thestarsahil** [comment]
Screenshot from 2024-06-24 18-28-19

**Comment by SrinivasDevolper** [comment]
Counsellor error1

It is fine in my code there is nothing to change

**Comment by SrinivasDevolper** [comment]
How did you add no results found text on search results without merging my code

**Comment by thestarsahil** [comment]
@SrinivasDevolper look your packages and code effecting the whole codebase , that's why i have to work on it !
You can look into another problem , but make sure not to effect the other code structure !

**Comment by SrinivasDevolper** [comment]
If there are problems with Anthor's code, I will correct them, why did you copy my code? You shouldn't do that
If there are some effects in the code, you should reassign to me

**Pull request closed without merging**
