### PR TITLE
College Social By default redirecting to footer It should open from top +Fixed Some Darkmode Bugs  #1289

### LINKED ISSUE #1289: College Social By default redirecting to footer It should open from top
image

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #1289

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

https://github.com/user-attachments/assets/d494d6d7-690f-4748-9317-6cbc7203458b

DarkMode Fixes

Screenshot 2024-07-29 005850
Screenshot 2024-07-29 010120
Screenshot 2024-07-29 010515

## Checklist

- [X ] Tests have been added or updated to cover the changes
- [ X] Documentation has been updated to reflect the changes
- [X ] Code follows the established coding style guidelines
- [X ] All tests are passing

### CODE REVIEW

**Comment by thestarsahil** [comment]
@nishant0708 Resolve conflct

**Comment by nishant0708** [comment]
hey @thestarsahil done

**Comment by thestarsahil** [comment]
Pull the latest changes and push again 
some changes not relecting @nishant0708

**Comment by nishant0708** [comment]
hey @thestarsahil  Sir what changes  is Not reflecting because this branch is completely up to date

**Comment by nishant0708** [comment]
hey @thestarsahil  please assign it level 2 . Level 3 is not justified in this case

**Pull request merged**
