### PR TITLE
enhanced the search bar

### LINKED ISSUE #570: Enhancing the Search Bar
**Is your feature request related to a problem? Please describe.**
The search bar does not look good. The placeholder text needs to be more lighter. The background should have been much more lighter or as the same as that of the website

**Describe the solution you'd like**
I would like to manage the background of the navbar and if permitted I would like to add hover effect on the search button

### PR DESCRIPTION
**Pull request by ayush-848**
# Description

Changed the coloring of the search bar

## Screenshots

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Review by thestarsahil — APPROVED** [review]
Perfect !

**Comment by thestarsahil** [comment]
@ayush-848 It is showing locally merged but globally haven't 
Check counsellor.social , the contribution does'nt reflected Please check once !

**Comment by ayush-848** [comment]
@thestarsahil Yeah, its not showing in socials.

**Comment by ayush-848** [comment]
@thestarsahil I unforked and then forked your repo again. After cloning the changes are present in Dashboard.css

**Pull request merged**
