### PR TITLE
fix: Added styles.yml File in GitHub Issue Templates

### LINKED ISSUE #298: [feat]: Add styles.yml File for Raising Enhancement, Styling related Requests Separately
**Is your feature request related to a problem? Please describe.**
**style.yml (Custom ISSUE_TEMPLATE):**
- The style.yml file, on the other hand, serves as a custom ISSUE_TEMPLATE for issues related to coding style, code formatting, and linting rules within your GitHub repository. This template helps contributors or users report code style-related concerns or seek guidance on adhering to the project's coding standards.
- The contents of style.yml might include specific questions or prompts related to coding style, requesting users to provide examples of code snippets that need formatting adjustments or explanation. Additionally, you might include instructions on how to check code against the project's style guidelines and best practices.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
- I want to work on this Issue Under GSSOC'23

### PR DESCRIPTION
**Pull request by NarendraKoya999**
# Description
- **Created styles.yml File in GitHub ISSUES TEMPLATES Folder.**
- **In that, I have added Suitable Code for styles.yml File.**

## Fixes #298 

Replace #298  with the issue number which is fixed in this PR

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by NarendraKoya999** [comment]
Hi @thestarsahil . Please Review on this PR and add Valid Level Labels under GSSOC'23.

**Comment by thestarsahil** [comment]
Can you send the output SS of template

**Comment by NarendraKoya999** [comment]
Hi @thestarsahil . Not possible to Share Screenshot. But, I can check YAML Validation. No Errors See on that File Code.
Please taken my Request into Consideration. Kindly Merge and add Valid Level Labels Under GSSOC'23 Contributor. If any Mistakes happen on my side, then Please Quote Me. I am always gives best result to Your Project.

**Review by thestarsahil — APPROVED** [review]
Look's Good template

**Pull request merged**
